### ISSUE TITLE
خطا: TypeError: cannot use 'in' operator to search for "success" in ""

### ISSUE THREAD

**Issue by zarvan9** [alireza0/s-ui#100]
من هر بار گزینه ذخیره رو میزنم مینویسه
خطا: TypeError: cannot use 'in' operator to search for "success" in ""

و کانفیگ ها هم کار نمیکنن

**Comment by alireza0** [comment]
لطفا اطلاعات کاملتری ارسال کنید. نوع مرورگر و لاگهای سرور برای پیدا کردن مشکل لازمه
