### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by NimaTarlani** [alireza0/s-ui#101]
دورد.
اماکانش هست برای config.json یه outbound بسازین که وارپی که از اسکریپت زیر رد میشه رو اضافه کنه به outbound ها؟

`bash <(curl -sSL https://raw.githubusercontent.com/hamid-gh98/x-ui-scripts/main/install_warp_proxy.sh)`

**Comment by alireza0** [comment]
درود بر شما
برای وارپ نیازی به اسکریپت ندارید، خروجی wireguard در سینگ باکس پشتیبانی میشه.
هنوز بخش خروجی ها و قوانین مسیریابی به این پنل افزوده نشده، ولی شما میتونید دستی اون ها رو توی config.json ویرایش کنید.

**Comment by NimaTarlani** [comment]
ممنونم.
میتونین یکم راهنمایی کنین که چیکار باید بکنم؟
داکیومنت sing-box رو دیدم. تنها کاری که باید بکنم اینه که اوتباند وایرگارده وارپ بسازم تو config.json و ترافیک رو از اونجا رد کنم؟

**Comment by NimaTarlani** [comment]
` FATAL[0000] create service: parse outbound[0]: WireGuard is not included in this build, rebuild with -tags with_wireguard`
این ارور رو میگیرم وقتی تو اوتباند وایرگارد اضافه میکنم

**Comment by NimaTarlani** [comment]
مشکلشو حل کردم. یکم وقت گیر بود ولی حل شد.
هسته رو با این تگ ها از اول بیلد کردم.
وایرگارد برای وارپ و v2ray_api با quic برای هیستریا بودن.  
`go build -tags "with_wireguard with_v2ray_api with_quic" ./cmd/sing-box`

اگه شد فک کنم هسته رو باید با وایرگارد بیلد کنین تو اپدیت بعدی.
و اینکه یه نکته که بهش برخوردم این بود که برای رد شدن تمامیه ترافیک از وایرگارد باید اتصال دایرکت رو از اوتباند حدفش کنیم:
```
    {
      "tag": "direct",
      "type": "direct"
    }
```

**Comment by alireza0** [comment]
هسته موجود در نسخه آخر فقط با استفاده از تگ های` with_v2ray_api with_clash_api with_grpc with_quic with_ech` بیلد شده.
در نسخه های بعدی تگ های دیگه رو هم اضافه میکنم

**Comment by mahsamcse** [comment]
با درود
ضمن تشکر مجدد از آقای علیرضا و بقیه دوستان کمک کننده به این پروژه خفن
من بالاخره مهاجرت کردم به این پنل بسیار کارآمد و خوب
الان روی نسخه 1 یه راهنمایی کنید لطفا که چطوری وارپ بزنیم ممنون میشم

**Comment by alireza0** [comment]
درود بر شما @mahsamcse 
کافیه اطلاعاتی که از وارپ دارید رو توی خروجی وایرگارد قرار بدید.
