### ISSUE TITLE
غیرفعال شدن هسته سینگ باکس

### ISSUE THREAD

**Issue by m3hdiclub** [alireza0/s-ui#102]
درود استاد
هر چند روز یکبار و یا حتی یک روز در میون هسته سینگ باکس غیرفعال میشه و باید از طریق ssh سینگ باکس رو ریستارت کنم تا اوکی بشه، حتی حالت اجرای خودکار سینگ باکس رو هم فعال دارم ولی بازم خودش فعال نمیشه..
ارور های توی لاگ

Apr 14 13:30:53 incandescent-berry1.aeza.network /usr/local/s-ui/sui[24939]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"

Apr 14 13:28:02 incandescent-berry1.aeza.network runSingbox.sh[30714]:         /home/runner/go/pkg/mod/github.com/sagernet/sing@v0.3.2/common/task/task.go:91 +0x107
Apr 14 13:28:02 incandescent-berry1.aeza.network runSingbox.sh[30714]: created by github.com/sagernet/sing/common/task.(*Group).RunContextList in goroutine 5288515
Apr 14 13:28:02 incandescent-berry1.aeza.network runSingbox.sh[30714]:         /home/runner/go/pkg/mod/github.com/sagernet/sing@v0.3.2/common/task/task.go:75 +0x198

**Comment by alireza0** [comment]
درود بر شما
این مشکل مربوط به هسته است و باید برای اون مخزن گزارش کنید.
لاگهای ارسالی مربوط به سرویس s-ui هست و نمیتونه مشکل رو نشون بده.
برای گرفتن لاگهای sing-box باید از دستور زیر استفاده کنید:

```bash
journalctl -u sing-box
```

**Comment by alireza0** [comment]
باگ هسته است و میتونید براشون گزارش کنید.
البته ممکنه از نسخه بعد از اینی که داریم استفاده میکنیم حل شده باشه.
