### ISSUE TITLE
Edit the expiration time of the latest client after setting up Chinese, and the expiration time disappears after submission

### ISSUE THREAD

**Issue by chenxudong2020** [alireza0/s-ui#105]
![1713692368720](https://github.com/alireza0/s-ui/assets/61214170/e57a5612-4d48-4b31-9bfa-fc0a3027af6d)
Click submit and the expiration time disappears as shown in the following image
![1713692414522](https://github.com/alireza0/s-ui/assets/61214170/bf2e94e6-a24b-4f9b-b1a4-3c4c4b4a7cf2)

**Comment by alireza0** [comment]
Thank you for your report.
It is fixed now. Please wait till next release.
