### ISSUE TITLE
Incomplete translation issue when set to Chinese

### ISSUE THREAD

**Issue by chenxudong2020** [alireza0/s-ui#106]
![image](https://github.com/alireza0/s-ui/assets/61214170/5c613193-1358-449e-b89c-552f31f180c3)
The running status of this page has been changed to: Ready

![1713692605768](https://github.com/alireza0/s-ui/assets/61214170/d7727016-a707-435c-94fd-9e0270c003c9)
This page is not translated
Masquerade only needs to fill in the running status of any port, which is no

![image](https://github.com/alireza0/s-ui/assets/61214170/927f19d2-b8f4-4527-8972-57e969e546be)
This page has not been translated. Professional terms can be retained, but some can be translated

The current deployment environment is: debain12 x-ui, the latest version

**Comment by alireza0** [comment]
Languages are now implemented more.
I need some native people to correct them.

Regarding Masquerade, please read [this](https://sing-box.sagernet.org/configuration/inbound/hysteria2/#masquerade)
