### ISSUE TITLE
Suggestion: S-UI logs can be displayed on web pages with a running status of no, making it inconvenient to view logs on the server

### ISSUE THREAD

**Issue by chenxudong2020** [alireza0/s-ui#107]
S-UI logs can be displayed on web pages with a running status of no, making it inconvenient to view logs on the server

**Comment by alireza0** [comment]
Don't rush ;)
It is in progress.
Inside backend, I deployed lots of reports and features which are not in panel's view yet :) 
I am still waiting for more support in client apps

**Comment by chenxudong2020** [comment]
***@***.***
 
From: Alireza Ahmadi
Date: 2024-04-22 05:33
To: alireza0/s-ui
CC: chenxudong2020; Author
Subject: Re: [alireza0/s-ui] Suggestion: S-UI logs can be displayed on web pages with a running status of no, making it inconvenient to view logs on the server (Issue #107)
Don't rush ;)
It is in progress.
Inside backend, I deployed lots of reports and features which are not in panel's view yet :)
I am still waiting for more support in client apps

**Comment by alireza0** [comment]
It is already added in last version
