### ISSUE TITLE
Panel exposing information such as ip , etc ! 

### ISSUE THREAD

**Issue by Alexander-McQuen** [alireza0/s-ui#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://www.youtube.com/watch?v=Ix1gEQ_KHjs

**Comment by alireza0** [comment]
Don't share wrong information. It is not true

**Comment by alireza0** [comment]
درود بر شما
بررسی کردم و در موردش جاهای مختلف اطلاع رسانی شده.
