### ISSUE TITLE
Suggestion: The default subscription path in settings and the username of new users in user management are not filled in by default. Use UUID to generate subscription links or nodes to prevent them from being scanned for enhanced security

### ISSUE THREAD

**Issue by chenxudong2020** [alireza0/s-ui#109]
The default subscription path in settings and the username of new users in user management are not filled in by default. Use uuid to generate subscription links or nodes to prevent them from being scanned for enhanced security. Please consider
![image](https://github.com/alireza0/s-ui/assets/61214170/87bf8068-91bd-41fd-b087-31906864a686)

![image](https://github.com/alireza0/s-ui/assets/61214170/decfdadc-efcd-481b-aff9-d90b8c8fb9a3)

Generate uuid in the case of default not filling in as shown in the above figure

**Comment by alireza0** [comment]
Default sub path could be defined in install script.
The default new client name will be deployed soon.
