### ISSUE TITLE
مشکل DNS در IOS

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#110]
درود علیرضا جان خوبی ؟ 
ببخشید یه سوال دارم ، توی اندروید Hy2 رو دارم با سرعت خوب و بدون مشکل توی NekoBOX استفاده میکنم ( البته با فعال کردن تیک FAKE DNS توی تنظیمات خود اپلیکیشن ) 
ولی توی IOS با برنامه Streisand همه چیز خوبه به جز اینستاگرام و واتس اپ که اونم مشکل از DNS هست ، برای حل مشکل میام توی قسمت DNS خود برنامه میزارم روی 1.1.1.1 مشکل حل میشه ولی فقط برای چند ثانیه یا چند دقیقه ، دوباره اینستا همینطور لودینگ میزنه و چیزی باز نمیشه !
خواستم ببینم چطوری باید مشکل رو حل کنم ممنون میشم راهنماییم کنی 
راستی برای IOS فقط برنامه Streisand جواب میده  ؟

**Comment by NimaTarlani** [comment]
فیک dns تو اپدیت بعدیه nekobox قراره حل بشه

**Comment by roozbehalamdari** [comment]
> فیک dns تو اپدیت بعدیه nekobox قراره حل بشه

آها ممنون ولی الان مشکل من با IOS و  Streisand هست برای اون باید چکار کرد ؟
