### ISSUE TITLE
auto use cert

### ISSUE THREAD

**Issue by agczsz** [alireza0/s-ui#113]
Automatically use panel certificates and domain names when the tls option is turned on

**Comment by alireza0** [comment]
It needs a part of application which is not deployed yet.
Please wait till full version release

**Comment by roozbehalamdari** [comment]
> It needs a part of application which is not deployed yet. Please wait till full version release

درود علیرضا جان ، لطفا پنل رو آپدیت کن واقعا حیفه این پنل به این خوبیه ( لطفا روش بیشتر وقت بزار 🥺 دمت گرم  )
یه سری مشکلات داره اگر فیکس بشه واقعا توووووووووپ میشه  ( جای یه سری قابلیت ها خیلی خالیه )
خلاصه که چشم انتظار یه آپدیت خفن و حرفه ای هستیم 🤤
بازم سپاس از همه ی زحمت هایی که بدون هیچ چشم داشتی میکشی ، خیلی آقایی ❤️

**Comment by alireza0** [comment]
@roozbehalamdari 

درود بر شما
این پروسه در حال انجامه و خب تغییرات خیلی زیادی لازمه که تنهایی و چند روزه قابل انجام نیست.
از طرف دیگه، چون کلاینت ها هنوز پروتکل ها رو پشتیبانی نمیکنن عجله کردن هم خیلی فایده ای نداره.
به خیلی از مفاهیم به شکل پایه‌ای فکر شده و اجراش باید دقیق باشه. هرچه بیشتر متمرکز و کاملتر باشه، طول عمر نرم‌افزار بیشتر میشه و قابلیت های بیشتری رو در آینده پشتیبانی میکنه

**Comment by roozbehalamdari** [comment]
> @roozbehalamdari
> 
> درود بر شما این پروسه در حال انجامه و خب تغییرات خیلی زیادی لازمه که تنهایی و چند روزه قابل انجام نیست. از طرف دیگه، چون کلاینت ها هنوز پروتکل ها رو پشتیبانی نمیکنن عجله کردن هم خیلی فایده ای نداره. به خیلی از مفاهیم به شکل پایه‌ای فکر شده و اجراش باید دقیق باشه. هرچه بیشتر متمرکز و کاملتر باشه، طول عمر نرم‌افزار بیشتر میشه و قابلیت های بیشتری رو در آینده پشتیبانی میکنه

به امید اون روز که هرچه سریعتر برسه 😍 ( مشتاقانه منتظر آپدیت های حرفه ای شما هستیم )
در مورد کمک کردن توی پروژه واقعا از دست من کاری بر نمیاد چون متاسفانه اطلاعاتم در اون حد نیست و بلد نیستم وگرنه از خٌدام بود بتونم کمک کنم که سریعتر به بهترین راه بتونیم برسیم ، ولی از دوست خوبم [نیما](https://github.com/NimaTarlani) کمک های خوبی بر میاد اونم مثل خودت کار درست و دلسوز و با تجربه هست پیشنهاد میکنم حتما باهم در ارتباط باشین ، بازم سپاس از شما بزرگوار ♥

**Comment by alireza0** [comment]
It is implemented and in next version you can use it
