### ISSUE TITLE
subconverter form

### ISSUE THREAD

**Issue by agczsz** [alireza0/s-ui#114]
The transport type did not contains tcp,thus subconverter couldn't recoginize

**Comment by agczsz** [comment]
> There os no TCP trasport type in SingBox. When transport is disabled, is will be pure TCP

well,even there is no tcp option,but the subscribe link should add the tcp,otherwise client or subconverter will not recoginze the url as the right link.
here is the log in nekoray:
s-ui:vless://183f7ab9-a025-4bdf-925a-dcf74492f9db@hk.ag.now.cc:10086/?type=none&security=tls&sni=hk.ag.now.cc&flow=xtls-rprx-vision#%E9%A6%99%E6%B8%AFvless
![image](https://github.com/alireza0/s-ui/assets/121206519/a43e3ce5-3596-457c-9da5-cf6e29d9e20e)
the x-ui link:vless://98a2a883-c286-41c9-af9e-9acea5aad03a@hk.ag.now.cc:49716?**type=tcp**&security=tls&sni=hk.ag.now.cc&flow=xtls-rprx-vision&fp=chrome#a|9sAu.love@xray.com

**Comment by infernalLab** [comment]
cant edit http Response and Response header

**Comment by alireza0** [comment]
It is only Nekoray!
All other xray based clients (specially old one) uses 'none' as type.
Actually it is an unsupported feature in Nekoray!

As far as they support tcp as type as well, I will change it.

**Comment by alireza0** [comment]
It is fixed now. Please wait till next version.
