### ISSUE TITLE
tuic

### ISSUE THREAD

**Issue by zuntax** [alireza0/s-ui#116]
سلام
پس از ساختن tuic در برنامه نکو باکس پیغام connection refused نمایش داده میشه.

**Comment by zuntax** [comment]
![IMG_20240505_160628](https://github.com/alireza0/s-ui/assets/134101464/19e5ea40-ee3a-4154-8188-913eb853699a)

**Comment by NimaTarlani** [comment]
![Screenshot 2024-05-08 184825](https://github.com/alireza0/s-ui/assets/87723729/db084120-6822-4b44-a99e-dce31e9c195a)

برای tuic باید حتما از ssl استفاده کنین و سرتیفیکیت بگیرین
 میتونین تنظیمات رو مثل من انجام بدین و کار کنه.
