### ISSUE TITLE
Bugs and Improvements

### ISSUE THREAD

**Issue by Shellgate** [alireza0/s-ui#12]
از کار افتادن کانفیگ با استفاده از Udp fragment

عدم اعمال Erly data  در کانفیگ خروجی و نهایی مانند ?ed=2048

عدم توانایی در اضافه کردن rule ها و outbound ها

موارد بسیاری هستند که باید رسیدگی شود

عدم پشتیبانی کلاینت ها از mixed

عدم نمایش نسخه استفاده شده sing box

**Comment by alireza0** [comment]
لطفا برای هرکدوم، اول مطمئن بشید که باگ هست و بعد یک ایشو با مشخصات کامل بذارید.

**Comment by Shellgate** [comment]
کلی یکجا گزاشتیم‌ مواردی باگ هستن مواردی باید اضافه بشن

**Comment by alireza0** [comment]
برای اولین نسخه، کار کردن پروتکل ها برای من مهمتر بود.
در مورد باگها شما باید بدونید که این باگ مربوط به پنل میشه و یا نرم افزارهای سرور و کلاینت.
مثلا udp fragment توسط کلاینت های موجود پشتیبانی نمیشن!

استاندارد ?ed=... برای کلاینت های مبتنی بر xray استفاده میشه. با وجود اینکه توی تست های من با این هسته متصل شده، ولی هنوز از عملکرد Early data مطمئن نیستم! این مورد رو میشه توی نسخه های بعد اضافه کرد.

اینکه کلاینت ها از پروتکلی ساپورت نکن، مشکل این پنل نیست! ولی جهت اطلاعتون، mixed یعنی ترکیبی از socks و http که نیازی به نرم افزار ندارید برای اتصال. خود مرورگرها و سیستم ها میتونن مستقیم ازش استفاده کنن.

نسخه سینگ باکس استفاده شده در توضحیات ریلیز هست. با پیش زمینه پنل های دیگه نمیشه مدل کار این پنل رو تحلیل کرد.

پ.ن.: همه این موارد باگ نیستند. و تنها موردی که میشه روش فکر کرد بحث erly data است که کم کم باید بررسی و اضافه بشه

**Comment by alireza0** [comment]
لطفا ایشو رو باز نگه دارید تا در زمان مناسب بررسی بشه.
تگ اولویت پایین برای همین مورد اضافه کردم
