### ISSUE TITLE
s-ui cannot start in version 0.0.3

### ISSUE THREAD

**Issue by NimaTarlani** [alireza0/s-ui#121]
s-ui log:

```
May 15 05:47:52 heavenly-quilt.aeza.network systemd[1]: Started s-ui Service.
May 15 05:47:52 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Main process exited, code=exited, status=127/n/a
May 15 05:47:52 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Failed with result 'exit-code'.
May 15 05:48:02 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Scheduled restart job, restart counter is at 1.
May 15 05:48:02 heavenly-quilt.aeza.network systemd[1]: Stopped s-ui Service.
May 15 05:48:02 heavenly-quilt.aeza.network systemd[1]: Started s-ui Service.
May 15 05:48:02 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Main process exited, code=exited, status=127/n/a
May 15 05:48:02 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Failed with result 'exit-code'.
May 15 05:48:13 heavenly-quilt.aeza.network systemd[1]: s-ui.service: Scheduled restart job, restart counter is at 2.
May 15 05:48:13 heavenly-quilt.aeza.network systemd[1]: Stopped s-ui Service.

```

_I tested with Ubuntu 22 and 24._

**Comment by alireza0** [comment]
@NimaTarlani You can test these new files till finding the final way. They are built from latest source.

**Comment by NimaTarlani** [comment]
Everything is ok now
Warp connects well.
Rules can be applied well
But the only problem that has not been solved yet is DNS, which we must turn on fakeDNS.
If we do not turn it on, all traffic will be directed to 10.10.34.35.
If you can give me some advice in this matter so that I can solve it
I set and changed all DNS. Both in the panel and in the server itself. But none of them worked

**Comment by alireza0** [comment]
Thanks a lot for tests and nice feedback.
If you are using Nekobox or same client apps, it is exactly the app's problem that don't use proxy as dns's outbound!
It should be fixed by client developers

**Comment by NimaTarlani** [comment]
thank you. But there is a script that I think you worked with: ezpz-reality
This script does not have such a problem. I also checked the entire configuration and applied everything according to it in s-ui, but it didn't work...

**Comment by NimaTarlani** [comment]
```
  "dns": {
    "servers": [
    {"address": "tcp://1.1.1.1", "detour": "internet"},{"address": "tcp://1.0.0.1", "detour": "internet"}
    ],
    "strategy": "prefer_ipv4"
  },
.
.
.
  "outbounds": [
    {
      "type": "direct",
      "tag": "internet"
    },
    
    {
      "type": "block",
      "tag": "block"
    }
  ],
  "route": {
    "final": "internet",
    "rules": [...]
  }
```

**Comment by alireza0** [comment]
I didn't check that project till now.
If you mean using `detour`, it is implemented in s-ui as well, But you should use the right outboundTag.

If your server is inside GFW filtered zone, you must not to use direct outbound for dns!
