### ISSUE TITLE
Unimportant tables in db

### ISSUE THREAD

**Issue by NimaTarlani** [alireza0/s-ui#122]
Is it possible to delete the **"changes"** and **"stats"** tables from the database?
Because it has increased the amount of data and I feel that it can be deleted every week
Does this cause a problem?

**Comment by alireza0** [comment]
Stats table is the base of traffic report's graph in Inbound,Outbound and Client pages. It could be limited in settings or disabled by setting `Traffic Maximum Age` to 0.

Changes will be displayed in the future for reporting when changes happened. And also when multi admin feature is added, we need it for sure. It does not contain a lot of data ( in comparison with stats ), but could be handled in the future.

In the plan for backup/restore is it reserved to have choice to backup/restore these tables or not.
