### ISSUE TITLE
TUIC نحوه کانفیگ کردن 

### ISSUE THREAD

**Issue by arp7vpn** [alireza0/s-ui#125]
سلام یه توضیحی برای ایجاد کانفیگ TUIC میدین؟ بین پروتکل های سینگ باکس این شاید پرکاربردترین شون باشه و در حال حاضر هم خوب کار میکنه، اما با این پنل من نتونستم بفهمم چیا رو باید کانفیگ کنیم تا به درستی کار کنه، در صورتی کانفیگ هایی که این اسکریپت می سازه کار می کنن
aleskxyz/reality-ezpz
ممنون میشم اگر یه توضیح مختصری بدین.

**Comment by NimaTarlani** [comment]
https://github.com/alireza0/s-ui/issues/116#issuecomment-2100834949

این شاید کمکت کنه
