### ISSUE TITLE
appreciation, and a question

### ISSUE THREAD

**Issue by Amin2460** [alireza0/s-ui#126]
just wanted to thank you for making this wonderful panel. it's very appreciated, and I hope you continue developing it and supporting more features, such as reality protocol ( and if there's any other left that's not supported yet)

ty so much ❤️

btw I also have a question, is it possible to use geoip and geosite files? if yes then how?

**Comment by alireza0** [comment]
Thanks a lot.
I have one step more to have completed the base of s-ui panel. It is just a start journey :)

For goip/geosite, in Rules, you can define `local` type of `Ruleset` or just using a url to have dynamic one in `remote` type.

**Comment by Amin2460** [comment]
> For goip/geosite, in Rules, you can define `local` type of `Ruleset` or just using a url to have dynamic one in `remote` type.

thanks, got it working 👍
