### ISSUE TITLE
عدم اجرای نسخه جدید

### ISSUE THREAD

**Issue by rbsdotnet** [alireza0/s-ui#128]
درود وقت بخیر
نسخه جدید رو در 2 تا سرور ابونتو 22.4 نصب کردم اما در مرورگر هیچ صفحه ای باز نمیشه
اما پنل قبلی خودتون یا سنایی رو نصب میکنم بدون هیچ مشکلی اجرا میشه
ممنون میشم راهنمایی کنید

s-ui state: Running
Start automatically: Yes
sing-box state: Running
Start automatically: Yes

**Comment by NimaTarlani** [comment]
درود.
امکانش هست لاگ رو هم بفرستین؟
دستور s-ui رو وارد کنین و بعد عدد 15 بزنین و لاگ رو بفرستین
