### ISSUE TITLE
ریست کردن ترافیک مصرفی 

### ISSUE THREAD

**Issue by hossein1200github** [alireza0/s-ui#129]
با سلام امکان ریست کردن ترافیک برای کلاینت ها روی نمی بینم . 
دوباره حجم مصرفی صفر بشه .

**Comment by NimaTarlani** [comment]
درود.
تا اضافه شدن این آپشن میتونین یوزرنیم کلاینت رو از اول بسازین و قبلیو پاک کنین.
اینجوری کلاینت شما با اپدیت کردن لینک ساب قبلی میتونه کانفیگ هاشو اپدیت کنه و مجدد وصل شه

**Comment by alireza0** [comment]
درود برشما
راه پیشفرض اینه که شما ترافیک جدید رو به ترافیک های قبلی اضافه کنید.

**Comment by roozbehalamdari** [comment]
> درود برشما راه پیشفرض اینه که شما ترافیک جدید رو به ترافیک های قبلی اضافه کنید.

درود علیرضا جان 
اول از همه خواستم تشکر کنم از تلاشهای شما و نیما جان بابت بهتر و بهتر شدن پنل‌ ‌دمتون گرم که این همه زحمت میکشید .
بابت آپدیت هم سپاس  🌹🙏

خواستم بگم لطفا قابلیت ریست کردن ترافیک یوزر ها رو به این پنل هم مثل X-UI اضافه کنید واقعا کمبودش خیلی احساس میشه و کار رو سخت کرده 🙄 بازم ممنونم ‌.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی شما

ویژگی های اینچنینی پس از کامل شده نرم افزار و خارج شدن از حالت تست، اضافه خواهد شد.

**Comment by alireza0** [comment]
این ویژگی اضافه شده و در نسخه بعد قابل استفاده است.
