### ISSUE TITLE
نصب نشدن روی سرور هتزنر

### ISSUE THREAD

**Issue by rezajafari0970** [alireza0/s-ui#13]
روی سرور هتزنر نصب نمیشه 
Connected to mirror.hetzner.com (185.12.64.3)]

**Comment by ErfanTech** [comment]
من روی هتزنر بدون مشکل نصب کردم 
سرور اوبونتو۲۰ x86

**Comment by MrAli-Code** [comment]
اوبونتو 22 و سرور با منابع ضعیف هم براحتی نصب میشه .

**Comment by liamnees** [comment]
> روی سرور هتزنر نصب نمیشه Connected to mirror.hetzner.com (185.12.64.3)]

برای منم همین ارور را میده!

**Comment by vahidkazemi1989** [comment]
روی سرورت وارپ فعال کردی به خاطر اونه 
وارپ حذف کن اوکی میشه
