### ISSUE TITLE
Panel local connection error HTTP ERROR 404

### ISSUE THREAD

**Issue by pak160404** [alireza0/s-ui#130]
I install s-ui 0.0.3 in Debian 11 LXC on Proxmox. The system works fine in CLI but I cannot connect to the panel using local IPv4. It keeps report HTTP ERROR 404. I have tried to change the port, change the IP, uninstall, reinstall, lower to 0.0.2, disable firewall but still not work. I can confirm my Router and Internet have no problems because PiHole and 3X-UI works just fine.
I use only Ipv4, no Ipv6

Please looks into this thanks.

![image](https://github.com/alireza0/s-ui/assets/131251759/076ec290-3eca-415b-a2ed-facad74f9d0f)

**Comment by NimaTarlani** [comment]
http://192.168.2.197:2095/app/

You need to add /app/ as path

**Comment by NimaTarlani** [comment]
http://192.168.2.197:2095/app/

You need to add /app/ as path

**Comment by pak160404** [comment]
Thanks for you help, I'm able to login now. Sorry for making such a newbie mistake

**Comment by pak160404** [comment]
Thanks for you help, I'm able to login now. Sorry for making such a newbie mistake
