### ISSUE TITLE
可不可以支持hy2协议的端口跳跃？

### ISSUE THREAD

**Issue by wyr121** [alireza0/s-ui#131]
**您的功能请求与问题相关吗？请描述。**
可不可以支持hy2协议的端口跳跃？
https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/?h=%E7%AB%AF%E5%8F%A3

![image](https://github.com/alireza0/s-ui/assets/72083417/891a5b9c-7e93-43a0-9a16-3ff7d96ac6e6)

**Comment by alireza0** [comment]
sing-box doesn't support this feature
