### ISSUE TITLE
کپی نشدن کانفیگ

### ISSUE THREAD

**Issue by Hossein-M98** [alireza0/s-ui#132]
سلام و عرض تشکر بابت این پروژه خوب
من همین حالا پنلم رو به ورژن v0.0.4 آپدیت کردم و متوجه شدم کانفیگ از روی QR Code کپی نمیشه. با مرورگرهای کروم و فایرفاکس، روی ۲ تا سرور مختلف تست کردم و مشکل وجود داره.
لطفا در آپدیت بعدی مشکل رو فیکس کنید. (اگر رشته متنی کانفیگ جدا نمایش داده بشه هم خوبه)
در انتها بازم از شما ممنونم که کمک میکنید به اینترنت آزاد دسترسی داشته باشیم

**Comment by NimaTarlani** [comment]
درود.
از قسمت ادیت یوزر، تب لینک رو بزنین. کانفیگ ها اونجا قابل نمایشه

**Comment by Hossein-M98** [comment]
> درود. از قسمت ادیت یوزر، تب لینک رو بزنین. کانفیگ ها اونجا قابل نمایشه

بله درسته اصلا حواسم به اون قسمت نبود.
خیلی ممنون

**Comment by alireza0** [comment]
درود بر شما
مشکل تایید میشه و احتمالا به دلیل بروزرسانی پکیج های frontend بوجود اومده.

**Comment by alireza0** [comment]
مشکل حل شده و در نسخه بعد قابل استفاده خواهد بود.
