### ISSUE TITLE
Subscribsion

### ISSUE THREAD

**Issue by polons123** [alireza0/s-ui#134]
Hello!
By the link https://host:port/default-path/user I can't access the .a json file with the settings for the client. In browser I get blanc page. The port,, defaul path, and username are correct.

**Comment by polons123** [comment]
Hello.
The URL is correct, an attempt to download the sing-box config to a computer or mobile phone is an EOF error. Via wget, a zero-size file. What log files can I provide?

**Comment by alireza0** [comment]
EOF error is on client side.
You can check your logs via `s-ui` command and choose s-ui logs option.
If it returns no error, then your client is not configured for an inbound. Please check your client configuration for this.
Check your links tab in client edit modal as well. It should have a link per selected inbound.

**Comment by alireza0** [comment]
Using sing-box json in client is added and you can use it from next version
