### ISSUE TITLE
When the sing-box core crashes, I hope it can restart automatically.

### ISSUE THREAD

**Issue by dycwuxing** [alireza0/s-ui#135]
**Is your feature request related to a problem? Please describe.**

I have encountered sing-box kernel crash before, but I did not keep the log. From the container point of view, the sing-box container is running, but when I actually enter the container and see the status of sing-box, it is stopped.

**Describe alternatives you've considered**
Hope to be able to add a daemon-like process
Expectation: When sing-box stops, the sing-box core can be restarted

**Comment by dycwuxing** [comment]
I found some pictures
![image](https://github.com/alireza0/s-ui/assets/44988562/f4bac17c-ae45-4537-9000-90aea6ab6bd8)
![image](https://github.com/alireza0/s-ui/assets/44988562/fa2caf77-e1e9-4787-a7e7-85f61580255c)

**Comment by alireza0** [comment]
It is now added. Please wait for next release
