### ISSUE TITLE
Can I directly upgrade from x-ui panel to s-ui panel?

### ISSUE THREAD

**Issue by HereNoAg300L** [alireza0/s-ui#137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arlcrow** [comment]
no, this is different software

**Comment by leic4u** [comment]
> Can I export from x-ui like this and then import it with s-ui?

No, you can't.
x-ui uses xray core, while s-ui uses sing-box core.
It's a large gap between x-ui and s-ui.

You must config your inbounds in s-ui panel manuly.
