### ISSUE TITLE
add other sing-box options for each protocol

### ISSUE THREAD

**Issue by tryeverything91** [alireza0/s-ui#138]
for example there is no reality option
or Masquerade option for hysteria2
or ech
or other switches
please add all sing-box capacity

**Comment by alireza0** [comment]
Despite Sing-box hasn't a good documentation, it has some limitaitions and should be configured acurately.
I tried to add all paramethers, bot sometimes won't run correctly!
Masquerade is in Hysteria2 Inbound's option. Just click on options button.

For ech, tls and reality, I had a plan which is not implementd yet.
We cannot save all the paramthers in config.json to rely on for client's configuration ( unlike v2ray/xray ).

I am trying to implement a new module for these client-server variables

**Comment by tryeverything91** [comment]
thanks for your attention.
yes it has Masquerade option. i think it added in new release

**Comment by alireza0** [comment]
ech is added. But you can use it in next vesion with json-sub ( using sing-box client )
