### ISSUE TITLE
S-UI 's outbound,       hy2sterria   can't  build handshake to another hy2 inbound

### ISSUE THREAD

**Issue by marcuccilli** [alireza0/s-ui#139]
Confirm  all  parameters is right
Server A and Server B,  
A inbound port =11111,outbound=12222,  setting  inbound=11111 and outbound=12222 in  Rules
B inbound =12222

Confirm  can build connect by hysteria2 to A and B
but  when I set outbound in hysteria2 to Server B,  in Client v2rayN,it report that , 
"the  SSL connetion could not be established,see inner exception"

**Comment by alireza0** [comment]
Where is the bug ?

**Comment by marcuccilli** [comment]
> Where is the bug ?

OK~fine,I do fix it by use  direct to hysteria2 instead hysteria2 to hysteria2
