### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by Rulio723** [alireza0/s-ui#14]
Can you add Chinese support? Very much needed, thank you very much

**Comment by alireza0** [comment]
Sure!
Hopefully it is designed for Multi-language support.
I will do it soon. But my periority is to make it stable and full.

**Comment by Rulio723** [comment]
Thank you

**Comment by Rulio723** [comment]
Thank you very much

**Comment by Rulio723** [comment]
Okay, good work

**Comment by Rulio723** [comment]
Excuse me, is there an official TG channel for resumes
