### ISSUE TITLE
اشکال در تغییر نام کلاینت

### ISSUE THREAD

**Issue by rezhacker** [alireza0/s-ui#140]
زمانی که کلاینت رو ادیت میکنم و نام را تغییر میدم ارور Duplicate Data: Name میده. در صورتی که اسم کلاینت تکراری نیست.

**Comment by alireza0** [comment]
از گزارش شما سپاسگزارم
این مشکل تایید میشه و در نسخه بعد درست خواهد شد

**Comment by alireza0** [comment]
تغییرات انجام شد و در نسخه بعد قابل استفاده خواهد بود.
