### ISSUE TITLE
Allow Insecure

### ISSUE THREAD

**Issue by arash1959** [alireza0/s-ui#143]
سلام چطور میشه گزینه Allow Insecure  رو داخل کانفیگ فعال داشته باشم برای هیستریا۲

**Comment by NimaTarlani** [comment]
درود‌.
روشن کردن allow insecure پیشنهاد نمیشه. بهتره از دامنه و سرتیفیکت معتبر استفاده کنید

**Comment by alireza0** [comment]
درود بر شما
این ویژگی به زودی ارائه میشه
ولی در نظر داشته باشید که اکثر نرم افزار های کلاینت به دلایل امنیتی این ویژگی رو قبول نمیکنند
