### ISSUE TITLE
نحوه بک اپ از یوزرها

### ISSUE THREAD

**Issue by Aronablade** [alireza0/s-ui#144]
سلام ، فعلا برای بک اپ از لیست کاربران چیکار میشه کرد ؟
و اینکه اگه ایتم بک اپ رو هم اضافه کنید خیلی خوب میشه .
سوم اینکه تایلهایی که تو صفحه اول فعال میکنم ، هر بار اوگین میکنم پریده و نمیمونه .

چرا جدیدا دیگه پنلها محدودیت تعداد اتصال کاربر رو برداشتن ؟ دلیلی داره ؟

پنل فوق العاده ایی هستش ، واقعا کلی دنبالش بودم . عالیه

**Comment by alireza0** [comment]
درود بر شما
پشتیبان گیری و بازیابی در نسخه های بعد اضافه میشه
کاشی ها فقط روی کوکی های مرورگری که لاگین کردین میمونه.
محدودیت اتصال یه مدل ساختگیه و هیچکدوم از هسته ها ازش پیشتیبانی نمیکنن.
سپاسگزارم
