### ISSUE TITLE
Is it possible to set limitation for concurrent user connection ? 

### ISSUE THREAD

**Issue by m0jtabaebrahimi** [alireza0/s-ui#145]
Hi Alireza,
First of all thanks for your great work.

Is it possible to set limitation for concurrent user ? I mean, suppose that user01 can only connect concurrently from just one device.

Thanks

**Comment by alireza0** [comment]
Hi @m0jtabaebrahimi ,

It is not implemented in sing-box core and not an interesting feature considering our goals.
