### ISSUE TITLE
failed to run command: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by APPX-Studio** [alireza0/s-ui#147]
centos9 aws

failed to run command: wait: remote command exited without exit status or exit signal

  Upgrading        : centos-stream-repos-9.0-26.el9.noarch                     132/467 
  Upgrading        : centos-stream-release-9.0-26.el9.noarch                   133/467 
  Upgrading        : setup-2.13.7-10.el9.noarch                                134/467 
warning: /etc/shadow created as /etc/shadow.rpmnew

  Running scriptlet: setup-2.13.7-10.el9.noarch                                134/467 
  Upgrading        : shadow-utils-2:4.9-8.el9.x86_64                           135/467 
  Upgrading        : openldap-2.6.6-3.el9.x86_64                               136/467 
  Upgrading        : libcurl-7.76.1-29.el9.x86_64                              137/467 
  Upgrading        : libldb-2.9.0-1.el9.x86_64                                 138/467 
  Upgrading        : curl-7.76.1-29.el9.x86_64                                 139/467 
  Upgrading        : rpm-4.16.1.3-29.el9.x86_64                                140/467 
  Upgrading        : rpm-libs-4.16.1.3-29.el9.x86_64                           141/467 
  Upgrading        : policycoreutils-3.6-2.1.el9.x86_64                        142/467 
  Running scriptlet: policycoreutils-3.6-2.1.el9.x86_64                        142/467 
  Upgrading        : selinux-policy-38.1.38-1.el9.noarch                       143/467 
  Running scriptlet: selinux-policy-38.1.38-1.el9.noarch                       143/467 
failed to run command: wait: remote command exited without exit status or exit signal

**Comment by APPX-Studio** [comment]
centos9 aws

**Comment by alireza0** [comment]
It seems it stopped before the main job of script in OS updating process.
Please update your OS before running script.
