### ISSUE TITLE
تمدید حساب کاربر

### ISSUE THREAD

**Issue by gorbesiah** [alireza0/s-ui#148]
سلام
ممنون از زحماتت
یه باگی که تو نسخه ۰.۰.۴ (0.0.4) بهش برخوردم اینه که وقتی یوزر حجمش یا تاریخش تموم میشه و تاریخ و حجم رو به صورت دستی بهش اضافه میکنی و ذخیره میکنی، کاربر نمیتونه متصل بشه و با ریستارت پنل و هسته هم درست نشد اما با یکبار خاموش کردن (Statistics) و ذخیره کردن و دوباره فعال و ذخیره کردن درست میشه.
صرفا خواستم گزار بدم
بازم ممنون از این پنل فوق‌العاده

**Comment by alireza0** [comment]
درود بر شما
این مشکل مربوط میشه به اینکه باید بعد از افزایش حجم، کاربر رو به صورت دستی فعال کنید.
البته یه مشکل دیگه هم داره که توی خود صفحه کلاینت اگر فعالش کنید، این تغییرات اعمال نمیشه و حتما باید توی صفحه ویرایش باشه. این مشکل رو با [fix toggle enable client](https://github.com/alireza0/s-ui/commit/aca870e78f2876003cf54f464ad94e756c60241f) حل کردم و در نسخه بعد برطرف میشه

**Comment by alireza0** [comment]
این مشکل در نسخه جدید برطرف شده. لطفا بررسی کنید و در صورت وجود مشکل در ایشو جدید مطرح کنید.
