### ISSUE TITLE
Does s-ui support TCP Brutal?

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#149]
I created a trojan with TCP Brutal, like this:

![Clip_2024-06-02_21-39-16](https://github.com/alireza0/s-ui/assets/32786903/4740d120-83df-4ef1-bc06-08e8c18b351c)

And I add it to Clash meta configuration, like this:

![Clip_2024-06-02_21-41-29](https://github.com/alireza0/s-ui/assets/32786903/d21b2360-4b82-4611-80ba-755248d092c0)

It doesn't work anymore.

Does s-ui support TCP Brutal? Or just I config it incorrectly?

By the way, the trojan URI which s-ui provided doesn't include the brutal field.

**Comment by alireza0** [comment]
Everything in s-ui is based on sing-box documentation which is very poor!
You can take a look on config.json, if the configuration is correctly stored by s-ui.
Otherwise, core is responsible if it is not working properly.

**Comment by leic4u** [comment]
> Everything in s-ui is based on sing-box documentation which is very poor! You can take a look on config.json, if the configuration is correctly stored by s-ui. Otherwise, core is responsible if it is not working properly.

Thanks bro. I checked the config.json and it is correct.

And I created a issue in sing-box repo, see https://github.com/SagerNet/sing-box/issues/1823 .
