### ISSUE TITLE
Future of X-UI, what's the purpose of S-UI and what's the difference of these two?

### ISSUE THREAD

**Issue by Kenya-West** [alireza0/s-ui#15]
With this release of S-UI, what's the future of [X-UI](https://github.com/alireza0/x-ui)? 

Is S-UI a kind of refactor of X-UI? 

What are their differences?

Will they both be supported, or only one in the future?

**Comment by X-Oracle** [comment]
well the big one is their core. 
x-ui -> xray-core
s-ui -> sing-box-core

**Comment by alireza0** [comment]
> Will they both be supported, or only one in the future?

I am trying to support and upgrade all panels in my free times :)

**Comment by CyrusTheV** [comment]
Sing-box does not support tls fragmentation
But Thanks Alireza jan

**Comment by X-Oracle** [comment]
> Sing-box does not support tls fragmentation
> But Thanks Alireza jan

Tls fragmentation is an outbound feature. not useful for server side.
