### ISSUE TITLE
آموزش کامل پنل

### ISSUE THREAD

**Issue by rbsdotnet** [alireza0/s-ui#152]
درود بر شما
امکانش هست یک آموزش کامل از پنل و امکاناتش رو بزارید
سپاس

**Comment by alireza0** [comment]
درود بر شما
تا الان تمرکز من روی تمام کردین این ویژگی های پایه بود.
برای آموزش هرکسی اقدام کنه حتما همکاری میکنم.

**Comment by alireza0** [comment]
جناب آقاپور اولین کسی بودن که با من تماس داشتن و ویدئو ها رو دارن آماده میکنن.
