### ISSUE TITLE
مشکلات فعلی پنل

### ISSUE THREAD

**Issue by Nima786** [alireza0/s-ui#154]
سلام، امروز یکی دو ساعتی تست کردم این ورژن حدید رو و به مواردی برخورد کردم، اینایی که یادم هست رو میگم،
۱) بعضی اوقات یه اینباند می‌سازیم چند تا اضافه میشن ( توی ساخت tuic) این اتفاق برام افتاد 
۲) وقتی بعضی اینباند ها رو پاک میکنیم تعداد اینباند برای کاربر همون قبلی رو نشون میده، مثلا سه تا اینباند داده بودم به کاربر، دو تا اینباند رو کلا پاک کردم ولی هنوز عدد سه رو میزنه برای تعداد اینباند برای یوزر.
۳) حذف اینباند برای قسمت تنظیمات کاربر عمل نمیکنه، مثلا دو‌ تا اینباند دادم به کاربر وقتی ادیت میکنم یه اینباند رو برمیدارم و آپدیت میزنم ، اون اینباند از کاربر حذف نمیشه و همچنان هست.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از گزارشتون
در مورد مشکل اول، چندین بار گزارش شده، ولی هیچوقت برای خودم پیش نیومده که بتونم تحلیل کنم.
حدس من تاثیر اختلال اینترنت بود که هرجوری شبیه سازی کردم باز هم مشکل رو متوجه نشدم.
یک سری تغییرات در نسخه قبل دادم که ظاهرا موثر نبوده و اشکال از پکیج های وابسته باید باشه.
اینبار هم چندین بخش رو تغییر دادم و امیدوارم مشکل حل بشه.

در مورد اشکال دوم و سوم، حق با شماست و کد رو اصلاح کردم.
