### ISSUE TITLE
docker Panel warning

### ISSUE THREAD

**Issue by dycwuxing** [alireza0/s-ui#155]
**Describe the bug**
After updating to 0.0.5, the original configuration cannot be viewed in the S-UI panel, including inbound, outbound, routing, users, etc.

**To Reproduce**
1. docker-compose pull
2. docker-compose down 
3. docker-compose up -d or docker-compose up -d --force-recreate

**Expected behavior**
After downgrading to 0.0.4, it can run normally without any changes

**Screenshots**

**Desktop (please complete the following information):**
 - CentOS7

**Additional context**
Logs:
2024/06/11 05:30:33 WARNING - failed :sql: Scan error on column index 3, name "config": unsupported Scan, storing driver.Value type string into type *json.RawMessage; sql: Scan error on column index 3, name "config": unsupported Scan, storing driver.Value type string into type *json.RawMessage
2024/06/11 05:30:22 WARNING - failed :sql: Scan error on column index 3, name "config": unsupported Scan, storing driver.Value type string into type *json.RawMessage; sql: Scan error on column index 3, name "config": unsupported Scan, storing driver.Value type string into type *json.RawMessage
2024/06/11 05:29:59 INFO - Sub server run http on[::]:2096
2024/06/11 05:29:59 INFO - web server run http on[::]:2095

**Comment by alireza0** [comment]
Douplicate issue: #153
Please update your `docker-compose.yml` file before pulling 0.0.5 version.

**Comment by dycwuxing** [comment]
Thanks
