### ISSUE TITLE
افزودن اوت باند

### ISSUE THREAD

**Issue by Nima786** [alireza0/s-ui#156]
سلام، تا جایی که من دیدم اوت باند جدید باید دستی ساخته بشه برخلاف چیزی که توی پنل x-ui داریم، امکاناش هست که این رو هم مثل اون پنلها طوری طراحی کنید که بشه کانفیگ‌ رو از جای دیگه کپی و بعد پیست کرد؟

**Comment by alireza0** [comment]
درود بر شما
بله. تا این نسخه تمرکز من روی ویژگی های پایه ای بوده و برای نسخه های بعدی، ویژگی های اینچنینی اضافه میشه

**Comment by alireza0** [comment]
فابلیت ایجاد خروجی با استفاده از لینک اضافه شد.
در نسخه بعد قابل استفاده خواهد بود.

**Comment by tTFrpsvV7MHCUEEunVj3** [comment]
سلام و درود برای نسخه بعدی API و راهنمای درخواست دادن رو برای ساخت کلاینت اگر میشه اضافه کنید
