### ISSUE TITLE
پنل با دامنه و پروکسی روشن

### ISSUE THREAD

**Issue by arash1959** [alireza0/s-ui#158]
سلام پنل من با دامنه و پروکسی روشن هست در کانفیگ هیستریا جای آدرس آی پی میزارم ولی باز نهایت دامنه قرار میگیره و باید دستی تغییر بدم

**Comment by alireza0** [comment]
درود بر شما
هنوز این ویژگی به پنل اضافه نشده.
منتظر نسخه های بعد باشید
