### ISSUE TITLE
[Bug]: "missing address_resolver"

### ISSUE THREAD

**Issue by radiumatic** [alireza0/s-ui#159]
**Describe the bug**

The panel doesn't add "address_resolver" property to DNS specified by User, resulting in the error "missing address_resolver" and sing-box refusing to start.

**To Reproduce**
1. Try to set a DNS server that isn't IPv4/IPv6. Eg. DoH

**Expected behavior**

DNS being set and sing-box running.

**Screenshots**

**Desktop (please complete the following information):**

[Irrelevant]

**Smartphone (please complete the following information):**

Not smartphone, but s-ui version v0.0.5. 

**Additional context**

**Comment by alireza0** [comment]
It is added to the project. You can use it in next version.
