### ISSUE TITLE
panel performance

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/s-ui#16]
hi.
thanks for dedicating your time in building a sing-box based panel.

I see we have separate backend and frontend. does having separate backend and frontend make it more resource consuming in servers compared to x-ui?

**Comment by alireza0** [comment]
Hello @X-Oracle ,
Actually this design will help to have less server resources consumption.
As you can see in API module, all requests are defined in minimum possible way.
Frontend is using Vue3 which moves all processes out of backend to the client browser.

**Comment by X-Oracle** [comment]
Oh I see . I didn't know how Vue works. Thanks for info
