### ISSUE TITLE
The proxies URI doesn't contain the mux params even though I have configured it in the inbound

### ISSUE THREAD

**Issue by leic4u** [alireza0/s-ui#162]
**Describe the bug**
The proxies URI doesn't contain the mux params, even though I have configured it in the inbound, in s-ui v0.0.5.

**To Reproduce**
1. Go to 'inbound'
2. Add a new inbound (trojan or vmess or vless)
3. Config the Multiplex params and the other params, then save it
4. Go to 'Clients'
5. Add the inbound tag to a user
6. check the Links for this user

**Expected behavior**
While the Multiplex of inbound was configured, the proxy URI contains mux params.

**Comment by alireza0** [comment]
There is no standard way to define mux in proxy url.
Some client apps has their own prefonfigured mux and some others has nothing.
The only way to provide some config parts like mux is to use JSON with clients which support JSON config.

**Comment by alireza0** [comment]
Json SUB is now added to S-UI. If you configure mux in inbound, it will be in json-sub as well.
Please wait for next release
