### ISSUE TITLE
add External Proxy like x-ui

### ISSUE THREAD

**Issue by mobohes** [alireza0/s-ui#163]
کانفیگ ws +tls ساختم روی پنل ولی نمیتونم آدرس کانفیگ رو از طریق پنل تغییر بدم و آی پی های کلود فلر رو قرار بدم
یا حتی برای تانل کردن هم این مشکلو دارم و باید خودم دستی آی پی رو تغییر بدم
ممنون میشم این مشکلو برطرف کنید تا نیاز به تغییرات به صورت دستی نباشه

**Comment by alireza0** [comment]
این بخش هنوز به پنل اضافه نشده. منتظر نسخه های بعد باشید

**Comment by iMajid7** [comment]
> کانفیگ ws +tls ساختم روی پنل ولی نمیتونم آدرس کانفیگ رو از طریق پنل تغییر بدم و آی پی های کلود فلر رو قرار بدم
> 
> یا حتی برای تانل کردن هم این مشکلو دارم و باید خودم دستی آی پی رو تغییر بدم
> 
> ممنون میشم این مشکلو برطرف کنید تا نیاز به تغییرات به صورت دستی نباشه

ابن مشکل تغییر آدرس فقط این پنل هست با تمام x-ui ها این مشکل دارند؟

**Comment by alireza0** [comment]
این مورد اضافه شده و در نسخه جدید میتونید استفاده کنید.
