### ISSUE TITLE
出站设置增加anyconnect/Outbounds add anyconnect(ocserv)

### ISSUE THREAD

**Issue by mysoft999** [alireza0/s-ui#164]
您好，我在出站设置里面只看到socks/WireGuard之类的 协议，没有看到cisco的协议，请问您以后有计划支持cisco协议吗？谢谢

Hello, I only saw protocols such as Socks/WireGuard in the outbounds settings and did not see Cisco protocols. Do you have plans to support Cisco protocols in the future? thanks

**Comment by alireza0** [comment]
Hello,
This panel is only a configuration provider for sing-box.
If they support it, then we can add it.
