### ISSUE TITLE
I hope to migrate the outbound addition method of 3x-ui to s-ui

### ISSUE THREAD

**Issue by Faramitas** [alireza0/s-ui#168]
I need to forward traffic to my other VPS to implement some functions, but the current method of adding outbound traffic is too slow and cannot be imported directly. I also hope to use geosite and geoip, which will make it much more convenient to configure rules.

**Comment by alireza0** [comment]
Regarding outbound, I will add an option for converting a link to outbound soon.

For using geosite/geoip, you should define `rule_set` which is already implemented.
