### ISSUE TITLE
Failed to run journalctl command!

### ISSUE THREAD

**Issue by arstum** [alireza0/s-ui#169]
**Describe the bug**
Failed to run journalctl command!

**To Reproduce**
run follow command in vps:
mkdir s-ui && cd s-ui
docker run -itd \
    -p 2095:2095 -p 2096:2096 -p 443:443 -p 80:80 \
    -v $PWD/db/:/usr/local/s-ui/db/ \
    -v $PWD/cert/:/root/cert/ \
    --name s-ui --restart=unless-stopped \
    alireza7/s-ui:latest

**Expected behavior**
Failed to run journalctl command!

**Screenshots**
![2024-06-21-122509_982x574_scrot](https://github.com/alireza0/s-ui/assets/14139978/65e1c97d-d52a-4690-97be-12d1b8c3feb5)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - firefox
 - 22

**Smartphone (please complete the following information):**

**Additional context**
Without any other command.

**Comment by arstum** [comment]
systemctl start s-ui
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by alireza0** [comment]
Log view is not available for sing-box in docker yet!
I will update it in proper time

**Comment by arstum** [comment]
Thanks.
