### ISSUE TITLE
Reality is missing the μTLS (Fingerprint) and SpiderX configuration items

### ISSUE THREAD

**Issue by lingbaoboy** [alireza0/s-ui#173]
Reality is missing the μTLS (Fingerprint) and SpiderX configuration items, and the generated subscription link also lacks the corresponding configuration. As a result, the singbox client fails to start due to the absence of μTLS.

**Comment by alireza0** [comment]
UTLS is now fixed as an option.
SpiderX is not supported by singbox.
In xray, It will be a random value if you don't set it.
