### ISSUE TITLE
استفاده همزمان از x-ui و s-ui

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#174]
سلام خسته نباشید میگم بهتون
امکان استفاده همزمان از s-ui و x-ui وجود داره ؟ میخوام کاربران رو کم کم به پنل جدید منتقل کنم که خیلی ساده تر و راحت تره. 
ممنونم از شما

**Comment by alireza0** [comment]
درود بر شما
لطفا قبل از ایجاد ایشو جستجو کنید. قبلا چندین بار توضیح داده شده.
هیچ مشکلی نیست، فقط باید مراقب پورت های تکراری باشید.
