### ISSUE TITLE
Failed to run journalctl command!

### ISSUE THREAD

**Issue by anvar68** [alireza0/s-ui#176]
Hello!
Docker s-ui is running on a Mikrotik router.
The panel reports a sing-box error:
"Failed to run journalctl command!"
Is there a solution to the problem?

**Comment by joismine** [comment]
same issue

**Comment by alireza0** [comment]
Logs are not accessible inside docker.
You should configure more complex configuration to simulate it.
BTW: I already have a solution and will implement it in proper time.

**Comment by hzdlive** [comment]
version 1.0.0

![20240705152117](https://github.com/alireza0/s-ui/assets/3319136/6c7c2899-f823-4ea5-bb8a-6ec3a885bcd3)

**Comment by alireza0** [comment]
The change in docker version could be done separately.
First I should develope main features, then update the docker version.
I will update it soon. Please be informed that docker-compose.yml file may need to be changed.

> s-ui | WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.176.3:1080: connect: connection refused"

If you setup your complete solution in a correct way, then availibility of sing-box core could be accepted by calling api.
If there is no api, then s-ui will check the process and if it is not available, it will trying to find errors in log.

IMPORTANT: If you configure your setup in a way that s-ui could reach sing-box v2ray-api, this error will be disappear!

**Comment by hzdlive** [comment]
> The change in docker version could be done separately. First I should develope main features, then update the docker version. I will update it soon. Please be informed that docker-compose.yml file may need to be changed.
> 
> > s-ui | WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 192.168.176.3:1080: connect: connection refused"
> 
> If you setup your complete solution in a correct way, then availibility of sing-box core could be accepted by calling api. If there is no api, then s-ui will check the process and if it is not available, it will trying to find errors in log.
> 
> IMPORTANT: If you configure your setup in a way that s-ui could reach sing-box v2ray-api, this error will disappear!

If I try to add an outbound, s-ui gives an error
![1720577748565](https://github.com/alireza0/s-ui/assets/3319136/f37c7479-d31f-4bc9-80af-25c7dc1317be)

**Comment by alireza0** [comment]
This issue will be completely solved in next release.
Please update your docker-compose.yml file after new release
