### ISSUE TITLE
عدم اضافه شدن کانفیگ های سینگ باکس در نرم افزار اندروید سینگ باکس

### ISSUE THREAD

**Issue by mrmemrmemrme** [alireza0/s-ui#177]
با سلام، درود و دستخوش
کانفیگ های بر پایه سینگ باکس مثل هیستریا 2 ساخته شده با S-UI در نرم افزار اندروید سینگ باکس، اضافه نمیشوند. چه با اسکن QR چه کپی Json چه لینک سابسکریبشن. لازم به ذکره که این کانفیگ ها براحتی در نرم افزار V2rayN اضافه میشن و کار میکنن. 
لینک گیت هاب پروژه سینگ باکس و نرم افزار اندرویدش رو قرار میدم تا مشخص کنم دقیقا منظورم کدوم نرم افزار هستش
https://github.com/SagerNet/sing-box/releases
بعنوان مثال هنگام اسکن QR کد با نرم افزار اندروید، با خطای زیر مواجه میشویم.
![0](https://github.com/alireza0/s-ui/assets/127270912/8ecfa16c-7e9d-43d4-b3e5-58d3fb539299)
با تشکر

**Comment by alireza0** [comment]
برای نرم افزار کلاینت سینگ باکس شما به ساب جیسون نیاز دارید که در نسخه بعد اضافه میشه.
این نرم افزار از لینک ها پشتیبانی نمیکنه.
