### ISSUE TITLE
پاک نشدن inbound و client

### ISSUE THREAD

**Issue by Aronablade** [alireza0/s-ui#178]
با سلام . من به مشکل عجیبی برخوردم امروز ، یه client اضافه کردم که یهو پنل شروع کرد به اررور دادن وقتی لوگ رو نگاه کردم دیدم میگه inbound 4 پسورد نداره ، در صورتی که قبلش همه چیز اوکی بود ، اونو پاک کردم به بعدی گیر داد و همینجور تا چندتا Inbound رو پاک کردم و اوکی شد وقتی میخواستم دوباره اضافه کنم بازم شروع میکرد error و جالب اینکه هرچقدر inbound ها رو پاک میکردم بازم برمیگشت . انگار اصلا پاک نمیشد .

الان دیگه به ناچار دارم رو یه سرور دیگه نصب میکنم و مجبورم دستی تمام کاربرا رو انتقال بدم . ایکاش یه راه بک اپ اضافه میکردید . خیلی واجبه خدایی ، مخصوص برای ورژن های اولیه که هر ان ممکنه همچین مشکلی پیش بیاد . 

و اینکه وقتی پنل رو اپدیت بزنم کل دیتا پاک میشه ؟ یا مثل x-ui همه چیز سر جاش میمونه ؟

**Comment by alireza0** [comment]
درود بر شما
دست شما برای هر تنظیمی ( حتی اشتباه ) بازه و بهتره بدونید که مشکل از کجاست و درستش کنید.
اینباند شماره ۴ میشه پنجمین ورودی شما، بهتره به جای پاک کردن مشکلش رو حل کنید.

گاهی به دلیل عدم تنظیم مناسب و یا مشکلات ناشناخته، تنظیمی به مشکل میخوره.
این حالت رو میشه با یکبار ویرایش و ذخیره اون اینباند حل کرد.
روال های ذخیره هر مودال، همه کاربرها و تنظیمات مربوطه رو از اول تصحیح میکنه.
