### ISSUE TITLE
مشکل tls در vless, tuic, hysteria, trojan

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#179]
سلام من چند نمونه کانفیگ برای تست ایجاد کردم
کانفیگ vmess با tls کار میکنه
ولی کانفیگ های tuic و hysteria و vless و trojan کار نمیکنن با Tls
ممنون میشم راهنمایی کنید
![image](https://github.com/alireza0/s-ui/assets/22216895/42f6f445-11dc-4478-b2b8-ade40a3a8863)
![image](https://github.com/alireza0/s-ui/assets/22216895/65652bf7-08c2-472c-b8d4-c6ba1fe750ab)

**Comment by alireza0** [comment]
درود بر شما
مشکل نحوه تنظیم به پنل ارتباطی نداره.
بهتره بدونین هر پروتکل از چه تنظیمی باید استفاده کنه.
مثلا استفاده از disable SNI و  Allow Insecure همه جا پشتیبانی نمیشه.
اگر نرم افزار سمت کاربر شما هسته سینگ باکس نداشته باشه، تنظیمات هم مناسب با اون محدود میشه.
پیشنهاد میکنم چند مدل تنظیم رمزنگاری داشته باشید و حالت ها رو عوض کنید تا بهترین حالت رو بتونید برای هر پروتکل تنظیم کنید.
