### ISSUE TITLE
sing-box error | failed to run journalctl command!

### ISSUE THREAD

**Issue by mohamad47geek** [alireza0/s-ui#180]
سلام علیرضا . من پنل را داخل یک کانتینر داکر میکروتیکی که سیستم عاملش دبیان 12 هستش نصب کردم و این ارور میگیرم . اما روی x-ui خودت مشکلی ندارم روی این کانتینر . فکر میکنم مشکل از journalctl باشه که روی ایمیج داکری که هست نصب نمیشه و به ارور میخوره پنل . میشه کاری کرد که الزامی نباشه استفاده از journalctl داخل پنل که هسته سینگ باکس به ارور نخوره و ران بشه ؟

![Screenshot 2024-06-29 115445](https://github.com/alireza0/s-ui/assets/124453742/05050734-dbcb-4f38-ba9a-a39c48ef4fc6)

**Comment by alireza0** [comment]
درود بر شما
این خطا زمانی نمایش داده میشه که سینگباکس در دسترس نباشه.
راه حل های زیادی برای استفاده در داکر هست که یک مدلش رو توی پروژه رها استفاده کردم.
این مورد رو در زمان مناسب انجام میدم
