### ISSUE TITLE
Bug in remove user inbounds

### ISSUE THREAD

**Issue by Hossein-M98** [alireza0/s-ui#181]
Hello and thank you for this useful project
I have some troubles with this panel (v0.0.5); one is removing user inbounds.
When I want to remove some inbounds from a user, there is no save button on the "Clients" page to save changes. After refreshing the page, I do not see any changes in user inbounds.

**Comment by alireza0** [comment]
This panel has two step saving in add/edit functions.
Please take a look on top-end of your page for (overall) save button.

**Comment by Hossein-M98** [comment]
Thanks for the quick response

The problem is that the button you mentioned does not appear! I save the settings in step one, but there is no save button for step 2. I have 2 servers, one works correctly and I can save step 2, but the other does not.

In general, the behavior of the second server is strange and one of the problems is the mentioned bug. Let me describe the process of encountering the problem.
For the reasons that I will say below, I uninstalled the S-UI from this server according to the [README.md](https://github.com/alireza0/s-ui/blob/main/README.md) and installed it again. Next, I created 3 different Hysteria and Hysteria2 inbounds and assigned them to the first user, and everything was working fine. Later, I added a few more users in the same way, suddenly all configs and users stopped working while the Sing-Box core was running. Next, I tried to disable some inbounds so that the problem might be solved, but I ran into the second-step save button bug. I tried to delete users one by one, but that didn't work either. Even I tried to re-install and configure the S-UI, but it didn't work again!

It seems to me that inbounds are not assigned to users correctly in some cases, but I can not find the pattern of encountering this problem. In my case, even reinstalling the S-UI does not solve the problem. So I decided to report the current issue, may the whole problem be fixed.

**Comment by lingbaoboy** [comment]
I have encountered the same issue. In the user interface, when adding inbound rules, saving works fine. However, when trying to delete certain inbound rules for users, it does not save properly.

**Comment by alireza0** [comment]
Please test the new version which if error exists

**Comment by lingbaoboy** [comment]
It's work now.

**Comment by Hossein-M98** [comment]
Yes, It's working.
Thanks for your attention.
