### ISSUE TITLE
Recommendations regarding Docker images

### ISSUE THREAD

**Issue by lingbaoboy** [alireza0/s-ui#182]
I suggest referring to the 3xui project, bundling s-ui and singbox into a single Docker image. This image should allow for changing the singbox kernel version through a web interface, with the network mode set to host mode. This is because using a panel may require opening random ports, which can be inconvenient with the -p mode.

**Comment by alireza0** [comment]
Adding singbox as an internal process has a lot of disadvantages.
But for docker, if you want to use only one image with two processes, it is not a clean way.

Using host mode is also possible for both containers without any problem.
