### ISSUE TITLE
تفاوت آدرس و دامنه

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/s-ui#183]
سلام علیرضا جان وقتت بخیر

یک سوال از بخش پیکربندی داشتم که برام مبهم بود، میخواستم بدونم تفاوت آدرس و دامنه در کجاست؟

داخل بخش دامنه باید ساب دامنه (ex.site.com) رو قرار بدیم، درسته؟
کاربرد بخش آدرس چی هست؟

ممنون از شما.

**Comment by alireza0** [comment]
درود بر شما
آدرس به IP ای که اون سرویس ( در مثال شما ساب ) قراره فقط به همون گوش بده اشاره میکنه.
دامنه در ساب و پنل هم همینطور. به دامنه ای که اون سرویس فقط باید به اون گوش بده اشاره میکنه.
وقتی خالی باشند یعنی به همه آدرس/دامنه هایی که به سرویس اشاره میکنن جواب میدن.
