### ISSUE TITLE
مشکل در آدرس اینباند ها

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#184]
سلام و خسته نباشید
در قسمت آدرس اینباند من IP سرور رو وارد میکنم و نمیخوام از دامنه استفاده کنم ولی همچنان سابسکریپشن ها از دامنه استفاده میکنن
![image](https://github.com/alireza0/s-ui/assets/22216895/e9943291-bf34-41a5-98bf-3c6dbb51d191)

**Comment by alireza0** [comment]
درود بر شما
بخش آدرس در ایجاد لینک تاثیری نداره. فقط برای اینه که روی کدوم آدرس سرور به ترافیک گوش بده.
در نسخه ۱.۰.۰ به بعد میتونید از multi domain برای تغییر آدرس استفاده کنید. در غیر اینصورت آدرس دامنه ای که باهاش پنل رو باز کردید ذخیره میشه.

**Comment by MoSi8160** [comment]
ممنون از شما 
نسخه ۱ چه زمانی ریلیز میشه

**Comment by alireza0** [comment]
ریلیز شده
