### ISSUE TITLE
خطای سینگ باکس پس از ساخت اکانت

### ISSUE THREAD

**Issue by skydarklord** [alireza0/s-ui#185]
با عرض سلام خدمت شما دوستان گرامی
 
من s-ui رو نصب کردم بعد از ساختن inbounds موقع ذخیره ارور سینگ باکس دریافت می کنم . و این باعث میشه سینگ باکس غیر فعال بشه . چند بار اسکریپت رو حذف و دوباره نصب کردم اما این مشکل رفع نشده .

متن خطا 

خطا در سینگ باکس 
Jul 04 19:43:58 greedy- network 
runSingbox.sh[1142197]: FATAL[0000] 
start service: initialize inbound٫ 
vmess[vmess-1]: listen tcp 
0.0.0.0:24175: bind: address already in 
use 

ممنون میشم راهنمایی کنید .
![Uploading singbox.png…]()

**Comment by alireza0** [comment]
درود بر شما
شما از پورت 24175 در سرورتون استفاده میکنید.

**Comment by skydarklord** [comment]
سلام 
ممنون پورت رو عوض میکنم امیدوارم مشکل رفع بشه .
