### ISSUE TITLE
ADD dns.rules

### ISSUE THREAD

**Issue by tou-7** [alireza0/s-ui#188]
dns Unlock ChatGPT
dns Unlock Netflix
Please excuse my poor English expression.
Thank you!

**Comment by PashaGH8101** [comment]
You can do it manually:

1. Create an outbound type "WireGuard" tag "warp". For the "private key" and "peer public key," you can use this Telegram bot "@generatewarpplusbot" to create a new Warp Plus config and get these keys needed. Leave other settings as default.

2. In the rules menu, add a new ruleset: Type "remote," tag "geoip-openai," and use this URL: "https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-openai.srs".

3. Add a new rule: In Rule Options, select "Rulesets." In Outbound, select "warp" (the outbound you created in step 1), and finally, select "geoip-openai" in Rulesets. Click save.

For using other Rulesets, I personally use this sing-box template:  
https://github.com/ByteMysticRogue/sing-box-templates/blob/main/Inbound-Outbound%20sample/server_side.json

**Comment by tou-7** [comment]
Bandwagonhost VPS Free DNS (172.31.255.2) Unlock ChatGPT
So, no need WARP+ ( useing WARP+, Open the chatgpt website, human-machine verification is required)
Thank you Guide! @PashaGH8101
