### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by emadtoranji** [alireza0/s-ui#189]
سلام علیرضا عزیز

اگر امکان اضافه کردن این مورد باشه به نظرم خیلی میتونه کاربردی باشه و بخش API رو ساده بکنه.
یک بخش داخل پنل قرار داده بشه که بشه یک API KEY باهاش ساخت و از این طریق درخواست هامون رو به سمت سرور ارسال کنیم.
اینجوری برای استفاده از API نیاز به لاگین کردن و ذخیره کوکی نیست.

ممنون بابت زحماتت

**Comment by alireza0** [comment]
#24
