### ISSUE TITLE
Vless

### ISSUE THREAD

**Issue by sinaNJN** [alireza0/s-ui#19]
سلام.
من موقع ساخت  vless متوجه شدم وقتی  tls ست میکنیم کانفیگ بصورت tcp ساخته نمیشه و خروجی نمیده. بدون tcp  عملا غیرقابل استفادست کانفیگ
این باگ هست یا در روند ساخت کانفیگ من اشتباهی کردم ؟

**Comment by alidxdydz** [comment]
دوست عزیز ترنسپرت tcp ، تنظیمات tls قبول نمیکنه. مگر اینکه بخواید همراه با reality استفاده کنید.
در ضمن این ترنسپرت فقط بصورت دایرکت کاربرد داره و پشت cdn نمیره.

**Comment by alireza0** [comment]
درود بر شما
وقتی transmission  رو غیر فعال میکنید، از مدل tcp استفاده میشه.
ولی سینگ باکس مدل انتقال tcp رو شبیه xray نداره و فقط مدل های انتقال های خاصی رو پشتیبانی میکنه
