### ISSUE TITLE
تعداد کاربران برای هر یوزر چند تا هست ؟

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#190]
سلام خسته نباشید . 
1. چه تعداد کاربر میتونن همزمان متصل بشن ؟ 
2. اگر تعدادش نامحدود هست خوب اگر من یک یوزر رو به 2 نفر بدم و هردو بخوان به یک اینباند متصل بشن امکان پذیر هست ؟

**Comment by alireza0** [comment]
درود بر شما
بله هیچ محدودیتی برای تعداد اتصال وجود نداره.
