### ISSUE TITLE
Failed to run journalctl command error

### ISSUE THREAD

**Issue by shahrooz1397** [alireza0/s-ui#191]
من رو اوبونتو ۱۸ با داکر نصب کردم داخل پنل که وارد میشم هر چند لحظه یه بار ارور 
failed to run journalctl command 
میاد
![image](https://github.com/alireza0/s-ui/assets/40915185/55170596-247f-47f0-8462-2e479de0bbc2)

**Comment by alireza0** [comment]
#176
