### ISSUE TITLE
sing-box error

### ISSUE THREAD

**Issue by dahraf** [alireza0/s-ui#192]
درود روی ubuntu 24.04 نصب کردم بار اول ipv6 رو شناسایی نکرد و خطا میداد هر چند ثانیه و هسته ریست میشد بار دوم Ipv6  رو شناسایی کرد ولی هنوز هم خطا داره و هسته مرتبط ریست میشه همچنین سرتیفیکت ها رو شناسایی نمیکنه سمت کلادفلر و داخل پنل تنظیمات حتی بعد از ذخیره میپره و درست بارگذاری نمیشه که بخاطر ریست شدن مرتب هسته هست 

![image](https://github.com/alireza0/s-ui/assets/103100108/98634d7f-7669-4b79-b966-94f35d0596d2)

**Comment by alireza0** [comment]
درود بر شما
گزارش های سینگ باکس رو باید چک کنید. اونجا ایراد تنظیمات شما کاملا مشخصه.
اینکه درست تنظیم نکردید مربوط به پنل نمیشه.

**Comment by dahraf** [comment]
![image](https://github.com/alireza0/s-ui/assets/103100108/5b372660-5763-429d-9118-fc6adb961143)

![image](https://github.com/alireza0/s-ui/assets/103100108/74b338e3-06eb-4a4b-8b07-d36f1c51a837)

![image](https://github.com/alireza0/s-ui/assets/103100108/ed87d878-d837-4a31-afe1-cb7dce546fdf)


نسخه ubuntu 20.04 رو نصب کردم بهتر شد وضعیت ولی هنوز cert سمت کلادفلر برای proxy کردن اوکی نمیشه چند اینباند ساختم روی 443 خطایی دریافت نکردم ولی هسته مجدد ریست میشه اینباند هارو پاک کردم و تنظیمات رو به حالت پیش فرض برگردوندم ولی هنوز هسته ریست میشه

**Comment by alireza0** [comment]
من هیچ خطایی نمیبینم توی این لاگ ها.
اینکه هسته بدون خطا ریستارت میشه، به دلیل تغییرات میتونه باشه. شما هر تغییری در تنظیمات بدید، مجبور به ریستارت شدن هسته هستیم که این کار رو پنل مدیریت میکنه.
مشکل گواهی رو شما اینجا ازش چیزی نذاشتین.
ولی یادتون باشه، هسته سینگ باکس متفاوته. مثلا برای گواهی، متن های اول و آخر گواهی رو باید بذارید.
برای مثال یکبار گواهی از خود پنل بگیرید تا متوجه بشید چطوری باید متن رو وارد کرد.
در ضمن برای هر گواهی بهتره sni رو فعال کنید.

**Comment by alireza0** [comment]
![image](https://github.com/alireza0/s-ui/assets/12573084/fdfd52aa-e068-4b2c-ab9c-1a30032a1925)
