### ISSUE TITLE
بالا نیومد با دامنه 

### ISSUE THREAD

**Issue by shahrooz1397** [alireza0/s-ui#194]
بعد راه اندازی از قسمت تنظیمات تی ال اس دامنمو اضافه کردم که اوکی بود 
ولی بعد از اینکه از تنظیمات مقادیر دامنه رو ست کردم:
![image](https://github.com/alireza0/s-ui/assets/40915185/d9f3d552-66d7-4739-9d5c-6cdef9adc3ca)

دیگه نه با ای پی و نه با دامنه بالا نیومد تا اینکه از ترمینال ریستارت کردم الان با ای پی پنل بالا میاد ولی با دامنه بالا نمیاد با اینکه مقادیری که از تنظیمات ست کرده بودم پاک و ریستارت کردم چندین بار 
حتی از تنظیمات تی ال اس دامنه رو پاک و دوباره تنظیم کردم ولی بازم با دامنه بالا نمیاد
![image](https://github.com/alireza0/s-ui/assets/40915185/c4e25f97-e427-4f0d-af99-9d443b874e99)

![image](https://github.com/alireza0/s-ui/assets/40915185/1037f5f7-4941-4a76-8b33-1b666fdc75c3)

**Comment by PashaGH8101** [comment]
لطفا در قسمت setting بخش interface گزینه "address" رو خالی نگه دارید.
 من با تنظیمات مثل تصویری که آپلود میکنم بدون مشکل با دامنه میتونم از پنل استفاده کنم :
![domain](https://github.com/alireza0/s-ui/assets/67472462/98cf2e1d-9898-47cc-ba93-c02792569c5a)

**Comment by shahrooz1397** [comment]
> لطفا در قسمت setting بخش interface گزینه "address" رو خالی نگه دارید. من با تنظیمات مثل تصویری که آپلود میکنم بدون مشکل با دامنه میتونم از پنل استفاده کنم : ![domain](https://private-user-images.githubusercontent.com/67472462/346321612-98cf2e1d-9898-47cc-ba93-c02792569c5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDg1NjAsIm5iZiI6MTcyMDM0ODI2MCwicGF0aCI6Ii82NzQ3MjQ2Mi8zNDYzMjE2MTItOThjZjJlMWQtOTg5OC00N2NjLWJhOTMtYzAyNzkyNTY5YzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDEwMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYmViZDcyM2Y3ZjA2NGMxOWMzNTQ1Yjk5YTgzOTU2NjU3MjFiOTRiODE0OGMyNjBkODFhMDMwZWYxMjgxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j8uKPWSSKB0fq_30LdU5_McdZeRpAgk_ec4yJ4kx4Zo)

ممنونم این اصلا باگ نبود
همونطور که گفتید مشکل حل شد تشکر
کاش یه صفحه ویکی داکیومنتی چیزی بود که همه چی رو توضیح میداد
