### ISSUE TITLE
Rules & Rulesets

### ISSUE THREAD

**Issue by dahraf** [alireza0/s-ui#195]
درود و خداقوت من پنل رو نصب کردم و سرتفیکت رو گرفتم و پشت cdn قرار دادم اینباند رو ساختم و کلابنت هم همینطور اما فقط با ساب برای من کار میکنه و وقتی ساب جیسون رو اضافه میکنم و یا سینگ باکس متصل نمیشه و فقط آیپی ایران رونشون میده 

میخاستم سایت های ایرانی رو بلاک کنم تو قسمت تنظیمات و ساب جیسون مسیر های ایران رو بلاک کردم ولی همونطور که گفتم ساب جیسون به درستی کار نمینه 

در ادامه طبق ویدیو آموزشی ایمان در قسمت rulesets لینک رو اضافه کردم ولی هسته شروع به ریست شدن کرد و مجبور شدم برای اداکه قانون رو پاک کنم و سرور رو ریبوت کنم 

![Screenshot 2024-07-07 153039](https://github.com/alireza0/s-ui/assets/103100108/eee9a678-4f49-4b1a-9217-b4ad93368e98)

![Screenshot 2024-07-07 153759](https://github.com/alireza0/s-ui/assets/103100108/915b1d83-5496-4fa4-b291-8ea80c665f42)

![Screenshot 2024-07-07 154338](https://github.com/alireza0/s-ui/assets/103100108/c67dd6de-2e2b-45b2-8efc-ea84dc034e55)

**Comment by dahraf** [comment]
https://github.com/Chocolate4U/Iran-sing-box-rules/blob/main/README.fa.md
https://cloud.lvlv.fun:8443/repo/MetaCubeX-meta-rules-dat-sing/geo/geosite/?q=ir

از اینجا لینک مسیریابی رو کپی کردن سایت دوم رو نیما معرفی کرد هردو رو تست کردم و eof دریافت کردم و هسته شروع به ریست میکرد تا اینکه کلا مسیر یابی هارو پاک کنم و سرور رو ریبوت کنم در حالت عادی مشکلی نداشت ولی هدف من عدم دسترسی کاربر به سایت های ایرانی هست حالا نمیدونم ارتباطی با cdn داره یا waf که فقط ایران اکسس کردم دامین رو ولی waf هم تغییر دادم و تست کردم مجدد همین اتفاق افتاد

**Comment by PashaGH8101** [comment]
ابتدا برای اینگه اصلا بتونه به درستی از اون RuleSet استفاده بشه داخل هسته Sing-Box اول باید به درستی آن RuleSet را بنویسید مانند تصویر زیر 
![image](https://github.com/alireza0/s-ui/assets/67472462/8495af98-19b8-4fb7-88e7-a5aa6f516b20)


در تصویری ارسالی شما اولین ایراد این هستش که outbound را "block" انتخاب کردید یعنی اصلا اجازه نمیدی به دانلود آن RuleSet 
**باید OutBound را Direct انتخاب کنید تا بتونه دانلود کنه!**

مرحله دوم برای اینکه بتونید از این RuleSet به درستی استفاده کرد باید یک Rule جدید ایحاد کنید مانند تصویر زیر:
![image](https://github.com/alireza0/s-ui/assets/67472462/fa577fe5-ec5d-4b2c-b75b-9fb083ff191a)
ابتدا یک Rule جدید را انتخاب کنید سپس از گزینه Rule Option اخرین گزینه یعنی RuleSets را انتخب کنید و آن Ruleset ای که قبلا ساختید "geosite-ir" برای تصویری که من ساختم و برای شما میشه "ir-ip" 
حالا اینحا باید OutBound را Block انتخاب کنید 


مراحلی که گفتم اول تمام ای پی هایی که داخل آن RuleSet (به عنوان مثال اینجا آی پی های ایران)  را Load میکنه  . سپس توی آن rule ای که ایجاد کردیم تمامی ان آی پی هارو بلاک میکنه که دیگه از سرور خارج ما استفاده نکنه و آی پی ما لو نره

**Comment by PashaGH8101** [comment]
لاگ هایی که ارسال کردید را که خوندم احساس من بر اینه که مشکل از همین جا باشه 
هسته Sing-Box میخواد اون RuleSet را دانلود کنه **ولی چون توی تگ Block  را براش به اشتباه انتخاب کردید** نمیتونه و به اصطلاح Crash میکنه!

**Comment by dahraf** [comment]
درود ممنونم از راهنمایی خوبت دقیقا همینطور بود من ویدیوی ایمان رو تو یوتیوب دیدم کلا اشتباه زدم سپاس از شما فقط الان تنها مشکلم اینه که JSON Subscription و SING-BOX برای من کار نمیکنه روی برنامه موبایلی که SING-BOX رو با QR اضافه میکنم اوکیه ولی با لینک نه اضافه نمیشه . با QR  بعد اتصال هم دیتایی ندارم اینو روی هیدیفای تو ویندوز هم تست کردم که بعد اتصال آیپی ایران سیستم خودمو فقط نشون میده و کار نمینه SING-BOX گوشی اندرویدی نسخه 1.9.3 هم که کلا بعد اتصال ترافیکی ندارم ممنون میشم اگه در این مورد هم اطلاع داری منو راهنمایی کنی 

![image](https://github.com/alireza0/s-ui/assets/103100108/aa372253-8dc8-4be0-950b-04c6f5e60cd8)

![image](https://github.com/alireza0/s-ui/assets/103100108/e7cc55ce-db90-4b11-bff7-d1e344b05c3f)

**Comment by alireza0** [comment]
@dahraf 

نرم افزار کلاینت سینگ باکس یه مشکلی با dns داره که میتونید با فعال کردن dns توی بخش تنظیمات ساب جیسون حلش کنید.
این مشکل با تنظیم سرور dns کلی روی پروتکلی غیر از udp حل میشه. مثلا tcp در مثال زیر:
![image](https://github.com/alireza0/s-ui/assets/12573084/e4af8fc4-29cb-4889-be08-d288ce10663d)

**Comment by dahraf** [comment]
وقت به خیر بله این قسمت رو فعال کردم هم با این دی ان اس و هم با کلادفلر تست کردم ولی روی کلاینت سینگ باکس بعد اتصال ترافیکی ندارم

**Comment by alireza0** [comment]
> وقت به خیر بله این قسمت رو فعال کردم هم با این دی ان اس و هم با کلادفلر تست کردم ولی روی کلاینت سینگ باکس بعد اتصال ترافیکی ندارم

اگر به صورت بدون پروتکل مثل `1.1.1.1` یا `udp://1.1.1.1`  تنظیم کنید ترافیک لوپ میشه.
حتما از پروتکل های دیگه مثل tcp یا https استفاده کنید

**Comment by dahraf** [comment]
بله همون فرمتی که گفتید وارد کردم حتی با https بازم لاگ مثل قبل هست 
ارتباطی به این قسمت نداره ؟ و اینکه اگه ممکنه یک مثال از این قسمت و کاراییش بگین 

![image](https://github.com/alireza0/s-ui/assets/103100108/52b4c669-cb19-4363-85bb-792769e8dbac)

**Comment by alireza0** [comment]
توی لاگهاتون به نظر میاد ارتباط اصلا برقرار نمیشه!

**Comment by dahraf** [comment]
درود من بارکد آخر رو روی سیستم عامل IOS و android و روی برنامه های  sing-box و Karing و hiddify و streisand و v2box تست کردم روی هیچ کدوم متصل نمیشه یا اصلا خونده نمیشه مثل karing روی خود sing-box حتما باید با QR اسکن بشه که تو ios امکانش نیست و لینک هم که اضافه میشه خطا میده و لینک رو نمیخونه تنظیمات dns رو در حالت های مختلف تغییر دادم به جز udp که فرمودین هرچند اصلا از udp هم استفاده نمیکنم تو کلاینت ولی بازم اتصالی برقرار نشد . گفتم بهتون اطلاع بدم که در جریان باشید

**Comment by alireza0** [comment]
بارکد آخر فقط برای اسکن توسط نرم افزار سینگ باکس هست که فعلا فقط در نسخه اندروید پشتیبانی میشه.
برای بقیه مدل ها باید از کپی کردن لینک ساب جیسون استفاده کنید.
اینکه خطا میده رو متوجه نمیشم. لطفا اگر تنظیماتتون خطا داره تصحیح کنید وگرنه باید بفرمایید که چطور و در چه حالتی بوجود میاد.
اتصال ها اگر توی برگه Groups از کلاینت سینگ باکس هیچ پینگی نداره، یعنی یه جای گانفیگتون و یا دسترسی به سرورتون مشکلی وجود داره.

یک نکته مهم: آیا شما پنل رو از نسخه قبل بروزرسانی کردید و اینباندها رو هیچ تغییری ندادید ؟

**Comment by dahraf** [comment]
![image](https://github.com/alireza0/s-ui/assets/103100108/1e43ec45-6216-4b56-86bc-3d38ed2dd298)

https://sbsn-30dn4-frkft-p46.vpns4.com:2096/3s4aBsCr!b7iOn/q8C8O4PX?format=json

![image](https://github.com/alireza0/s-ui/assets/103100108/1427fded-b55c-4d17-bbb0-c3aba3c3a7a6)

sing-box://import-remote-profile?url=https%3A%2F%2Fsbsn-30dn4-frkft-p46.vpns4.com%3A2096%2F3s4aBsCr!b7iOn%2Fq8C8O4PX%3Fformat%3Djson#q8C8O4PX

@alireza0 

این خدمت شما از cdn کلاد استفاده میکنم اینباند ها GRPC , ws همگی tls دار و اسنیفینگ و مالتیپلکس روشن همچنین سمت کلاینت ها شبکه tcp و udp packet encoding روی هیچکدام و امنیت روی chacha20-poly1305 قرار داره و از multi domain برای اضافه کردن cnam ها استفاده میکنم و آدرس اصلی رو پاک کردم در این قسمت برای وب سوکت هم همینطور اینباند ها هم کلا 4 تا هست که اگه تو v2ray اضافه کنید میتونید جزئیات رو ببینید جسارتا لینک مجدد ذکر کنم که با ساب مشکلی ندارم و پینگ خوبی دارم و فقط ساب جیسون و سینگ باکس برای من متصل نمیشن 

لطفا لینک ها و بارکد رو بعد از دیدن کامنت یا کلا کامنت رو  پاک کنید یا منشن کنید بنده پاک کنم

**Comment by alireza0** [comment]
من که نمیتونم بازش کنم
![image](https://github.com/alireza0/s-ui/assets/12573084/f2a1b52d-cf12-4593-a57d-a9b273aafc10)

شما با مرورگر میتونید باز کنید؟

**Comment by dahraf** [comment]
@alireza0 
مجدد تست کنید لطفا 
بنده ایران اکسس کرده بودم

**Comment by alireza0** [comment]
هیچکدوم از کانفیگ های شما قابل اتصال نیستند.
تنظیمات شما خیلی اختصاصی برای اتصال مستقیم مناسبه و پشت کلادفلر به مشکل میخوره.
با حذف مولتیپلکس مشکلش برطرف میشه.

**Comment by dahraf** [comment]
صحیح با خاموش کردن مولیتپلکس مشکلم هر شد ولی فقط روی GRPC برای ws هنوز اتصال برقرار نمیشه راه حلی داره ؟

**Comment by alireza0** [comment]
بیشتر مشکلتون اینه که کلادفلر رو آوردین وسط. باید ببینید چه چیزهایی رو از کلادفلر نمیتونید رد کنید که باعث مشکل شده.
