### ISSUE TITLE
Sing-box not running

### ISSUE THREAD

**Issue by gigil2020** [alireza0/s-ui#197]
Hello,
Thank you for your efforts.
After installation, I encounter an error regarding the deactivation of Sing Box.
I have deleted the server twice and set it up from the beginning, but it still happens.
![2](https://github.com/alireza0/s-ui/assets/127210461/14ad10b3-9aea-4c0f-af6d-786223586a76)
![1](https://github.com/alireza0/s-ui/assets/127210461/7e698fdd-0e40-4608-b9fb-aa4825fdebce)

**Comment by alireza0** [comment]
Hello
Please check your sing-box logs in main page or via cli

**Comment by MistFenix** [comment]
Can't get certs, need good developer to create gui for sing-box

**Comment by draminz** [comment]
hi,
thank you for your amazing job.
I have the same issue! after tons of restarting the sing-box core and the s-ui panel.
still not runing!
![Capture](https://github.com/user-attachments/assets/574e6772-4f6e-499a-a475-949cb67d6f79)
![Capture2](https://github.com/user-attachments/assets/1920070b-1dd2-4153-82d6-d0fdc1b62384)
![Capture3](https://github.com/user-attachments/assets/2fd6cd53-4202-4f0b-8f72-1a030e05b116)

**Comment by alireza0** [comment]
@draminz 
Did you define ShadoTLS in 4th inbound?
Currently Shadowtls version3 has a problem reported in #199 .
Please remove it or use another version. I will fix it in next release
