### ISSUE TITLE
مشکل اسم اینباند

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#198]
سلام . مشکلی که وجود داره داخل بخش tag name در اینباند وقتی اسپیس میزاری به صورت %20 داخل کلاینت کاربر نشون داده میشه

**Comment by alireza0** [comment]
درود بر شما
مشکل نمایش اشتباه در سمت کلاینت مشکل کلاینت محسوب میشه.
اسم یا برچسب به شکل استاندارد منتقل میشه

**Comment by MoSi8160** [comment]
@alireza0 
کلاینت هم ویندوز هست هم گوشی
بعضی اینباند ها درست نمایش داده میشه و بعضی خراب 
![image](https://github.com/alireza0/s-ui/assets/22216895/b4e49783-be22-4cbc-af59-2066943abc72)
![image](https://github.com/alireza0/s-ui/assets/22216895/4c02b716-a605-4b19-8acc-579ac86d9849)

**Comment by alireza0** [comment]
چشم بررسی میکنم

**Comment by MoSi8160** [comment]
ممنونم از شما

**Comment by alireza0** [comment]
این مشکل حل شد و در نسخه بعد قابل استفاده خواهد بود.
بعد از بروزرسانی به نسخه جدید، یکبار اینباند مورد نظر رو ویرایش و بعد ذخیره کنید.

**Comment by MoSi8160** [comment]
ممنونم از شما
