### ISSUE TITLE
Unable to use shadowtls How to fix this?

### ISSUE THREAD

**Issue by Maneeha1234SL** [alireza0/s-ui#199]
root@ip-172-26-2-250:~# s-ui status
The OS release is: ubuntu
● s-ui.service - s-ui Service
     Loaded: loaded (/etc/systemd/system/s-ui.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-07-09 06:10:58 +0530; 8h ago
   Main PID: 5589 (sui)
      Tasks: 9 (limit: 1019)
     Memory: 31.5M
     CGroup: /system.slice/s-ui.service
             └─5589 /usr/local/s-ui/sui

Jul 09 14:14:48 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:14:58 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:08 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:18 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:28 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:38 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:48 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:15:58 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:16:08 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
Jul 09 14:16:18 ip-172-26-2-250 /usr/local/s-ui/sui[5589]: WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while diali>
lines 1-19/19 (END)

<img width="1217" alt="image" src="https://github.com/alireza0/s-ui/assets/83775004/d676f422-eea3-472e-998e-2cabcc0be125">
<img width="479" alt="image" src="https://github.com/alireza0/s-ui/assets/83775004/738ab4cc-9f9c-4441-83d0-f7a3d711d4bc">

The same problem occurs no matter which port is used.

OS: Ubuntu 22.04 LTS
s-ui Version: [1.0.0](https://github.com/alireza0/s-ui/releases/tag/1.0.0)
shadowtls Version: 3

**Comment by alireza0** [comment]
Thsnk you for your report.
I have checked it and found a type there. It will be fixed in next release.

**Comment by DeadSecure** [comment]
@Maneeha1234SL change port to 444 and save and save inbound, then edit and change to 443 - save - save - and test again

**Comment by alireza0** [comment]
It is fixed now and you can use it in next release
