### ISSUE TITLE
دستور reset panel settings 

### ISSUE THREAD

**Issue by smblue07** [alireza0/s-ui#2]
سلام وقت بخیر
لطفا دستور Reset Panel Settings اضافه بشه که بتونیم پنل رو مجدد تنظیم کنیم
الان من توی تنظیمات پنلم گواهی ssl رو اشتباه ست کردم
اصلا پنلم بالا نمیاد که بخوام ریست کنم
باید از محیط کنسول این دسترسی وجود داشته باشه
با تشکر

**Comment by 0fariid0** [comment]
سلام وقتی کاربر رو ایجاد میکنی اون گوشه بالا باید ذخیره کنی

**Comment by alireza0** [comment]
این ویژگی در نسخه جدید در خط فرمان اضافه شده.
