### ISSUE TITLE
مشکل در لینک سابسکریپشن

### ISSUE THREAD

**Issue by sinazlf** [alireza0/s-ui#200]
سلام و ارادت
من همچنان برای اد کردن لینک ساب به برنامه streisand مشکل دارم.لینک ساب من به شکل زیره

http://domain.com:2053/sub/username?format=json

**Comment by alireza0** [comment]
درود بر شما
این نرم افزار نمیتونه ساب جیسون مخصوص سینگ باکس رو بخونه
