### ISSUE TITLE
is it possible to use Tunnel? like X-ui panel reverse?

### ISSUE THREAD

**Issue by Reynarow** [alireza0/s-ui#203]
i use tunnel in your X-ray panel and it works well but i heard sing-box is better in ping and speed. I installed S-UI on my server but it does not have reverse like X-ray. 

Can you help me ?

**Comment by alireza0** [comment]
Sing-Box does not support reverse tunnel.
The best solution is to use xray-core and connect your sing-box core with a socks outbound.

Free internet <--> Xray freedom <--> Xray bridge --> Xray portal <--> Xray Socks <--> Singbox outbound <--> Singbox Inbounds
