### ISSUE TITLE
مشکل در کلایت sing-box

### ISSUE THREAD

**Issue by sinazlf** [alireza0/s-ui#204]
ارادت
جسارتا ممنون میشم راهنمایی کنید چطور مشکل عدم عملکرد در کلاینت sing-box رو حل کنیم چون خیلیا این مشکل رو دارن🙏🏻

**Comment by alireza0** [comment]
درود بر شما
مشکل عدم عملکرد یعنی چی ؟
اگر مشکل از کلاینت بوده، به خود اون نرم افزار گزارش بدید.
لطفا برای باز کردن ایشو اطلاعات کامل رو حتما ارسال کنید
