### ISSUE TITLE
use Single inbound port for all configs

### ISSUE THREAD

**Issue by The-Binary-0-1** [alireza0/s-ui#205]
hi. first of all I want to say thank you for creating this feature-full panel based on sing-box.
second of all... I'm keen to know if there is any way to use one port like 443 for all inbound configs. if not, do you have any plan or any solution to do that? tnx.

**Comment by alireza0** [comment]
Hello @The-Binary-0-1 ,
Unfortunately sing-box core has no feature like fallback.
You should use 3rd party apps like HAproxy or nginx to achieve this goal.
