### ISSUE TITLE
Inbound - Tun

### ISSUE THREAD

**Issue by anvar68** [alireza0/s-ui#207]
Hello!
Are you planning to add Inbound Tun mode?

**Comment by alireza0** [comment]
Hello,
I can't find any benefit to have tun in server.
But it is already deployed in json sub for clients.

**Comment by anvar68** [comment]
TUN mode is necessary to create an interface on a router, for example Mikrotik, to create a route for redirecting traffic to a proxy.

**Comment by alireza0** [comment]
Good reason!
But it needs to run two containers with shared storage!
How you can manage it inside Mikrotik ?

**Comment by anvar68** [comment]
What could be the problem?
Nowadays you have to edit sonfig.json manually, which sometimes leads to errors. I would like to have the ability to make settings through the UI.
Now I'm using the sing-box container according to these instructions with FakeIp.
https://buzheteng.org/archives/4.html
I am also attaching the conig file.
[config.json](https://github.com/user-attachments/files/16302277/config.json)

**Comment by alireza0** [comment]
It is tagged to de deployed soon.

**Comment by anvar68** [comment]
Thank you very much!

**Comment by alireza0** [comment]
Minimal tun inbound is now added. Lets see which kind of configuration we need for next release.
Please wait for next release for testing.

**Comment by alireza0** [comment]
Missing or enabled `auto_route` in tun may cause loop in servers. Therefore it is disabled by default now.
