### ISSUE TITLE
اضافه کردن اینباند یا کاربر تکراری

### ISSUE THREAD

**Issue by MajMajVPN** [alireza0/s-ui#209]
سلام گاهی وقتی داریم اینباند یا اوت باند یا کاربر می سازیم برامون ۲ نمونه می سازه - این باگ در ورژن نیم بود الان در ورژن یک هم گاهی پیش میاد همینطور در ورژن جدید لازم به زندن دکمه ذخیره نیست و تغییرات اعمال میشه - سوال اینه پس چرا هنوز این دکمه وجود داره؟

**Comment by alireza0** [comment]
درود بر شما
ساخت اینباند اضافی باگ پکیج های استفاده شده است و تا اونها تصحیح کنن و بروزرسانی بشن ممکنه این اشکالات ادامه داشده باشه.
دکمه ذخیره بیشتر برای اینه که همه تغییرات دلخواه یکجا اعمال بشن.
در مورد حذف کردن در برخی موارد باید درجا اعمال بشه تا مشکلی برای کل سیستم بوجود نیاد.
