### ISSUE TITLE
تغییر پروت پیشفرض

### ISSUE THREAD

**Issue by mohmmadreza0021** [alireza0/s-ui#21]
سلام
امکان عوض کردن پورت پبشفرض وجود داره قبل نصب پنل؟
سروری که من استفاده مبکنم از پورت های محدودی پشتیبانی میکنه و امکان نصب وجود نداره برام

**Comment by holms2012** [comment]
> بله از طریق تنظیماتش میشه پورت پنل و ساب رو عوض کرد



> سلام امکان عوض کردن پورت پبشفرض وجود داره قبل نصب پنل؟ سروری که من استفاده مبکنم از پورت های محدودی پشتیبانی میکنه و امکان نصب وجود نداره برام

من هم همین مشکلو دارم سرور NAT دارم

**Comment by alireza0** [comment]
این ویژگی در نسخه جدید افزوده شده
