### ISSUE TITLE
مشکل UUID و اتصال در IOS 

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#211]
**درود علیرضا جان اول از همه میخواهم ازت تشکر کنم بابت تمام زحمتهایی که میکشی و بابت آپدیت جدید پنل تشکر کنم ، دمت گرم ❤️**
دو تا مشکل توی پنل هست که خیلی اذیت میکنه ممنون میشم باگش رو فیکس کنی یا بهم بگی چطوی میتونم مشکل رو حل کنم .

1 - توی پنل وقتی یه تغییر حتی جزئی توی مثلا اینباند یا جای دیگه میدم خیلی از یوزر ها دیگه نمیتونن وصل بشن و همش اررور UUID میده ، من مجبورم تمام یوزر هایی که مشکل دارن رو دونه دونه اول بیام اینباند هایی که براش انتخاب کردم رو حذف کنم بعد دخیره رو بزنم ، دوباره انتخاب اینباندهای هر یوزر و مجددا دخیره تا مشکل اون یوزر حل بشه ( این کار واقعا خسته کننده شده و صدای یوزر ها هم در اومده )

![image](https://github.com/user-attachments/assets/b9ded7b6-af4c-4ffb-ae3b-80b67c9c821d)

![image](https://github.com/user-attachments/assets/47b6bc1b-5b8a-49f7-9077-bd0944e6e63e)

2 - توی IOS هم مشکلی که هست با برنامه بسیار خوب سینگ باکس هرکاری میکنم یوزر نمیتونه وصل بشه یا اگر وصل شد اینستاگرام برای یوزر لودینگ میزنه همش ! 
توی برنامه Streisand هم تست کردم همه چیز خوبه ولی متاسفانه واتس اپ مدام connecting میزنه همه چیز هم تست کردم ( همه ی DNS های 1.1.1.1 رو هم تست کردم ولی مشکل حل نشد ) 

ممنون میشم کمکم کنی مشکل رو حل کنم دمت گرم ❤️

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از گزارش و همراهی شما.
برای اینکه گزارش درستی ارسال کنید، به جز عکس از خطا، باید تمام جزئیات که ایجاد خطا میکنه رو اعلام کنید تا ما بتونیم مراحل طی شده توسط شما رو انجام بدیم و باگ رو ببینیم. من به هر روش و با هر پروتکلی تست کردم مشکلی نداشت! اینجوری وقت خیلی زیادی از من میگیره.
روش ارائه اطلاعات درست توی الگوی گزارش خطا هست که شما همه رو پاک میکنید و رعایت نمیکنید.

نرم افزار کلاینت sing-box یه مشکلی روی dns داره که برای حلش، تنظیم dns پیشفرض در تنظیمات ساب جیسون رو tcp://8.8.8.8 گذاشتم.
اگر بدون dns و یا با تنظیم dns با پروتکل udp ( معادل اینکه پروتکل نوشته نشه ) انجام بشه به مشکل میخوره.
اگر میخواید از dns کلادفلر استفاده کنید تنظیم کلی dns توی تنظیمات ساب جیسون رو روی tcp://1.1.1.1 بذارید.

**Comment by roozbehalamdari** [comment]
بله چشم حتما ، رعایت میکنم البته درست متوجه نشدم برای همین پاکش کردم الگو رو ، ولی چشم

**Comment by roozbehalamdari** [comment]
> درود بر شما سپاسگزارم از گزارش و همراهی شما. برای اینکه گزارش درستی ارسال کنید، به جز عکس از خطا، باید تمام جزئیات که ایجاد خطا میکنه رو اعلام کنید تا ما بتونیم مراحل طی شده توسط شما رو انجام بدیم و باگ رو ببینیم. من به هر روش و با هر پروتکلی تست کردم مشکلی نداشت! اینجوری وقت خیلی زیادی از من میگیره. روش ارائه اطلاعات درست توی الگوی گزارش خطا هست که شما همه رو پاک میکنید و رعایت نمیکنید.
> 
> نرم افزار کلاینت sing-box یه مشکلی روی dns داره که برای حلش، تنظیم dns پیشفرض در تنظیمات ساب جیسون رو tcp://8.8.8.8 گذاشتم. اگر بدون dns و یا با تنظیم dns با پروتکل udp ( معادل اینکه پروتکل نوشته نشه ) انجام بشه به مشکل میخوره. اگر میخواید از dns کلادفلر استفاده کنید تنظیم کلی dns توی تنظیمات ساب جیسون رو روی tcp://1.1.1.1 بذارید.



> درود بر شما سپاسگزارم از گزارش و همراهی شما. برای اینکه گزارش درستی ارسال کنید، به جز عکس از خطا، باید تمام جزئیات که ایجاد خطا میکنه رو اعلام کنید تا ما بتونیم مراحل طی شده توسط شما رو انجام بدیم و باگ رو ببینیم. من به هر روش و با هر پروتکلی تست کردم مشکلی نداشت! اینجوری وقت خیلی زیادی از من میگیره. روش ارائه اطلاعات درست توی الگوی گزارش خطا هست که شما همه رو پاک میکنید و رعایت نمیکنید.
> 
> نرم افزار کلاینت sing-box یه مشکلی روی dns داره که برای حلش، تنظیم dns پیشفرض در تنظیمات ساب جیسون رو tcp://8.8.8.8 گذاشتم. اگر بدون dns و یا با تنظیم dns با پروتکل udp ( معادل اینکه پروتکل نوشته نشه ) انجام بشه به مشکل میخوره. اگر میخواید از dns کلادفلر استفاده کنید تنظیم کلی dns توی تنظیمات ساب جیسون رو روی tcp://1.1.1.1 بذارید.

به چشم حتما ، رعایت میکنم البته درست متوجه نشدم برای همین پاکش کردم الگو رو ، ولی چشم
اول مشکل singbox رو حل کنیم برای اون یکی مشکل هم کامل طبق الگو میگم خدمتت 


![image](https://github.com/user-attachments/assets/b9d57e6b-3954-48e2-9d4d-a483752f6101)
الان این تنظیمات درسته ؟ دایرکت DNS رو چی بزارم علیرضا جان ؟

**Comment by alireza0** [comment]
تنظیم Global DNS درسته و باید کار کنه.
تنظیم direct DNS برای ایران زیاد کاربردی نداره.
در مورد حذف تبلیغات هم خیلی تجربه خوبی ندارم. تست کنید، ولی بهتره از سمت سرور بلاک بشه.

من سعی میکنم یه مدل فارسی برای گرازش خطا هم اضافه کنم

**Comment by roozbehalamdari** [comment]
در مورد باگ اول که فرمودین کامل تر توضیح بدم این خدمت شما : 

من هر تغییری توی اینباند ها یا مثلا وارپ یا جای دیگه میدم  بعد از تغییر و ذخیره تغییرات بیشتر یوزر ها دیگه نمیتونن وصل بشن و باید هر یوزر رو از اول این کارها رو انجام بدم که بتونن وصل بشن  

1 - برم توی یوزر ادیت رو بزنم و اینباند های فعال رو حذف کنم بعد ذخیره کنم ( توی تصویر زیر اینبان ها رو حذف کردم )


![image](https://github.com/user-attachments/assets/98911db8-4016-4108-8dc4-e987d0ec0b2d)

2 - دوباره برم همون یوزر رو ادیت بزنم و اینباند ها رو اضافه کنم بهش و ذخیره کنم 

![image](https://github.com/user-attachments/assets/e50643bb-f761-481e-ab2f-3d0323d97182)

3 - بعد بیام توی برنامه مثلا هوسی آپدیت ساب رو بزنم که اطلاعات جدید رو بگیره تا بتونه وصل بشه 


ارور هایی که دریافت میکنم :

> Failed:: create service: parse outbound[0]: invalid
> uuid: uuid: incorrect UUID length 9 in string
> "undefined"

> Failed: authentication failed, status code: 404

![image](https://github.com/user-attachments/assets/cf786eff-9404-4cbc-bafa-5e33ee0e2689)
![image](https://github.com/user-attachments/assets/51b55b77-5d6b-42fa-b53f-5d0f7ba4de0d)

**Comment by alireza0** [comment]
من نمیدونستم توی جه پروتکلی این مشکل هست.
هیستریا و توییک هر دو اینمشکل رو دارن؟ یا توی اینباند های دیگه تغییر میدید این پروتکل ها به مشکل میخورن؟
خیلی کلی گفتین و نمیشه مشکل رو خودم بسازم تا تست کنم.
روند کار از اول رو باید اعلام کنید. تنظیمات اینباند و تغییری که میدین مهمه.
توی لاگ تغییرات هم میتونید پیدا کنید کجا به این مشکل میخوره

**Comment by roozbehalamdari** [comment]
> من نمیدونستم توی جه پروتکلی این مشکل هست.
> هیستریا و توییک هر دو اینمشکل رو دارن؟ یا توی اینباند های دیگه تغییر میدید این پروتکل ها به مشکل میخورن؟
> خیلی کلی گفتین و نمیشه مشکل رو خودم بسازم تا تست کنم.
> روند کار از اول رو باید اعلام کنید. تنظیمات اینباند و تغییری که میدین مهمه.
> توی لاگ تغییرات هم میتونید پیدا کنید کجا به این مشکل میخوره

آها ببخشید بازم متوجه نشدم دقیقا منظورت چی‌ بود برای همین دوباره درست توضیح ندادم 🙏 

من فقط توییک و هیستریا میسازم روی پنل ، حقیقت میترسم ویلس بسازم یه وقت آی پی لو بره یا دامین رو محدود کنن وگرنه خیلی نیاز به ویلس دارم اگر هم بدونم در کنار این دو پروتوکل میتونم ویلس هم داشته باشم و مشکلی پیش نمیاره واقعا عالیه 😍 

کانفیگ هایی که تغییر میدم هم همین توییک و هیستریا بودن ( تغییر کلی هم نمیدم جزیی هستن مثلا تغییر ipv4 و ... ) 

علیرضا جان ممنون میشم اگر تلگرام بتونم پیام بدم که بشه سریع فیلم یا عکسی اگر لازمه رو همون موقع بفرستم خدمتت 🙏

**Comment by roozbehalamdari** [comment]
علیرضا جان ممنون میشم جوابم رو بدی بزرگوار 🙏

**Comment by alireza0** [comment]
متاسفانه هرجوری تست میگیرم مشکلی ندارم و به درستی کار میکنه.

**Comment by roozbehalamdari** [comment]
> متاسفانه هرجوری تست میگیرم مشکلی ندارم و به درستی کار میکنه.

بازم ممنونم از وقتی که گذاشتی🙏🌹
۳ تا سوال دیگه داشتم 

۱- فرمودی برای حذف تبلیغات از سرور اقدام کنم ، میشه لطفا بگی چجوری ؟ لطفا اگر دستوری داره بهم یدی ممنون میشم 

۲ - توی برنامه سینگ باکس راهی داره که اطلاعات حجم و زمان کاربر رو نشون بده ؟

۳ - من میخواهم هر ۳۰ دقیقه یکبار ساب کاربرها آپدیت بشه در اصل این رو توی ساب جیسون هم اعمال کنم ، لطفا راهنماییم میکنی چطوری باید اعمال کنم ؟

**Comment by alireza0** [comment]
یه تغییر توی نسخه بعدی دارم اضافه میکنم که توی اون برای کاربران غیرفعال هم لینک ها بروزرسانی میشه.
در نسخه ریلیز شده، اگر کاربر غیر فعال باشه، لینک هاش undefined دارن. این داستان با تغییرات جدید حل میشه.



> ۱- فرمودی برای حذف تبلیغات از سرور اقدام کنم ، میشه لطفا بگی چجوری ؟ لطفا اگر دستوری داره بهم یدی ممنون میشم

این تنظیم رو توی مجموعه ها در بخش قوانین ایجاد کنید:
```go
        {
          tag: "geosite-ads",
          type: "remote",
          format: "binary",
          url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs",
          download_detour: "direct"
        }
```
و یک قانون بسازید که این مجموعه رو به خروجی بلاک بفرسته.


> ۲ - توی برنامه سینگ باکس راهی داره که اطلاعات حجم و زمان کاربر رو نشون بده ؟

من راهی ندیدم، مگر اینکه در ادامه اسم کانفیگ بذاریم و یا با مدل دیگه ای شبیه سازی کنیم.

> ۳ - من میخواهم هر ۳۰ دقیقه یکبار ساب کاربرها آپدیت بشه در اصل این رو توی ساب جیسون هم اعمال کنم ، لطفا راهنماییم میکنی چطوری باید اعمال کنم ؟

برای این بخش هم اطلاعاتی ندیدم. اگر راهی وجود داشته باشه اضافه میکنم

**Comment by roozbehalamdari** [comment]
> ```go
> {
>   tag: "geosite-ads",
>   type: "remote",
>   format: "binary",
>   url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs",
>   download_detour: "direct"
> }
> ```

سپاسگذارم بابت توضیحاتت ♥
من این رولز رو ایجاد کردم تا حدودی هم تبلیغات رو حذف کرد ، ولی تبلیغات یوتیوب رو همچنان نشون میده ، کامل تر از اون رو داری علیرضا جان ؟ یا میشه بگی از کجا باید پیدا کنم ؟

**Comment by roozbehalamdari** [comment]
> تنظیم direct DNS برای ایران زیاد کاربردی نداره.

آیا راهی هست سایت ها و برنامه های ایرانی رو بتونم مستقیم کنم که از وی پی ان رد نشه ؟ ممنون میشم راهنماییم کنی  🙏

**Comment by alireza0** [comment]
متاسفانه دیتای کمی هست و باید بیشتر جستجو کنید.

برای اینکه سایت های ایرانی رو مستقیم کنید باید از ساب جیسون و کلاینت هایی که این مدل رو ساپورت میکنن استفاده کنید.

**Comment by roozbehalamdari** [comment]
> برای اینکه سایت های ایرانی رو مستقیم کنید باید از ساب جیسون و کلاینت هایی که این مدل رو ساپورت میکنن استفاده کنید.

سپاس از راهنماییت علیرضا جان ، بله از لینک ساب جیسون و برنامه سینگ باکس استفاده میکنم .
فقط لطفا بهم میگی چی رو چجوری باید تغییر بدم که بتونم دایرکت کنم آی پی ها و دمین های ایرانی رو ؟ ( منظورم تنظیمات درست هست ) 
سپاسگذارم

**Comment by alireza0** [comment]
توی بخش تنظیمات ساب جیسون، برای ایران تنظیم direct dns خالی باشه بهتره.
بلاک کردن تبلیغات هم روی کلاینت سینکباکس خیلی درست کار نمیکنه و باعث اختلال میشه.
این دو مورد رو عوض کنید، بقیه درست هستند.
