### ISSUE TITLE
مشکل لینک های ساب سینگ باگس

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#212]
درود علیرضا جان 
ببخشید یه مشکلی توی پنل هست ( قسمت ساب اسکریپشن ها ) وقتی که روی لینک ساب اسکریپشن ( QrCode ) Sing-Box میزنم متاسفانه لینک خراب داده میشه ، مثلا اینطوری :
[https%3A%2F%2Fauto.Domain.com%2F540ac8e9-e31a-49ff-94ea-7cebeadb3bbf%2F%3Fq%3DUnknow%3Fformat%3Djson#Unknown
](url)
چطوری میتونم مشکل رو حل کنم ؟ چون نمیتونم به کسی لینک ساب بدم 
سپاس

**Comment by alireza0** [comment]
درود بر شما
اگر میخواید لینک رو بفرستید باید ساب جیسون رو بفرستید.
بخش sing-box فقط برای اسکن توسط نرم افزار اندرویدی sing-box طراحی شده.
