### ISSUE TITLE
اضافه کردن سرور

### ISSUE THREAD

**Issue by roozbehsat** [alireza0/s-ui#213]
سلام علیرضا جان و واقعا خسته نباشین.
یک راهنمایی می خواستم. 
آیا میشه به پنل سرور اضافه کرد؟ و اگر این قابلیت هست میشه راهنمایی بفرمایید؟
ارادت.

**Comment by alireza0** [comment]
درود بر شما
این پنل فعلا برای اجرا روی یک سرور تنظیم شده.
فعلا برای اضافه کردن سرور دیگه برنامه ای ندارم و فکری نکردم

**Comment by roozbehsat** [comment]
سپاس و ممنونم علیرضا جان
