### ISSUE TITLE
درخواست ساخت کانفیگ ریلیتی

### ISSUE THREAD

**Issue by mzc1993** [alireza0/s-ui#214]
با سلام خدمت دولوپر محترم

پشتیبانی از قابلیت ریلیتی در s-ui وجود نداره؟

اگر دارد بنده ندیدم و متوجه نشدم چطور بسازم

اگه هم نداره بودنش خالی از لطف نیست

تشکر

**Comment by alireza0** [comment]
درود بر شما
از بخش گواهی ها (TLS) میتونید یک تنظیم ریلیتی بسازید و در بخش اینباند ها با فعال کردن tls از گزینه الگو استفاده کنید.

**Comment by mzc1993** [comment]
خیلی ممنونم اقا علیرضا گل 

پس قابلیت ریلیتی بصورت tcp و flow:xtls-rprx-vision وجود داره؟

یه چیزی که کم داره پشتیبانی از ربات تلگرام هست تا همه چی تموم بشه. آیا امکانش هست در نسخه های بعدی اضافه بشه؟

**Comment by alireza0** [comment]
فعلا برنامه ای براش ندارم.
کلی کار پایه ای هست که باید انجام بدم.
