### ISSUE TITLE
 block adult content

### ISSUE THREAD

**Issue by gigil2020** [alireza0/s-ui#215]
Hi
Good day
How can blocking malware and adult content?

Thanks

**Comment by alireza0** [comment]
Hi,
You can use dns solutions or using `rule_set` with proper srs file

**Comment by gigil2020** [comment]
Tnx
how can i do rule_set in panel?

**Comment by alireza0** [comment]
In Rules page, you can find new Ruleset button and configure it based on Sing-Box documentation.
