### ISSUE TITLE
مشکل اتصال واتس اپ در Hysteria و TUIC

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#219]
درود علیرضا جان 
توی گوشی آیفون روی برنامه Streisand  یوزر وی پی ان رو که کانکت میکنه چه با پروتوکل هیستریا چه TUIC متاسفانه مدام کانکتینگ میزنه چکار باید کرد که مشکل دارندگان IOS حل بشه ؟ ممنون میشم راهنماییم کنید . ( البته این مشکل روی اندروید وجود نداره فقط IOS )

توی پنل هم میخواهم لینک Sing-Box رو بدم لینک رو همش با % میزنه ، ممنونم میشم مشکل رو بگین چطوری میتونم حل بکنم 🙏 

الان تمام تنظیمات پنل رو هم خدمتت میفرستم ، اگر جایی مشکلی داره یا چیزی کم داره لطفا بهم بگید که فیکسش کنم ، یک دنیا سپاس 🙏❤️

### **Inbound Hysteria :** 
![image](https://github.com/user-attachments/assets/75819695-8dfe-4475-9ceb-e18cdc9632d6)
![image](https://github.com/user-attachments/assets/dd5ec829-b9a0-453b-953c-e3356dd9e3f8)

### **Inbound TUIC :**
![image](https://github.com/user-attachments/assets/68e94528-fbcb-4f66-b44e-ed82a6c83980)
![image](https://github.com/user-attachments/assets/8808df02-b69f-4aec-b207-e450c94a7013)

### **Inbound Direct :** 

![image](https://github.com/user-attachments/assets/efd2ac53-f883-428e-b0d2-0c14bbe78c7a)

### **Outband :** 

**DNS :** 
![image](https://github.com/user-attachments/assets/110ae768-08d1-4796-ba71-e9ee4acaab1a)
Warp : 
![image](https://github.com/user-attachments/assets/16410e03-1d02-4269-80ad-14214c910686)
Direct : 
![image](https://github.com/user-attachments/assets/fb8da82e-e0f1-4954-80c6-e442a9dbcda2)

### **Rules :** 

![image](https://github.com/user-attachments/assets/53d7b5f7-5d55-4f7f-8d46-362a10fa6c46)

### **TLS :** 

![image](https://github.com/user-attachments/assets/b7e9d773-e436-4b9d-bd42-827254646eb1)
![image](https://github.com/user-attachments/assets/d349d9a1-fcf5-4822-ae97-5cf8ea374629)

### **Settings :**

**Log :**
![image](https://github.com/user-attachments/assets/70175609-1e7a-4a45-95db-1ade6981ca02)

**DNS :** 
![image](https://github.com/user-attachments/assets/4bf08bfe-ff6f-4a0f-a7e0-a7ba9ae3c8fa)

**NTP :** 
![image](https://github.com/user-attachments/assets/125b7dc3-2b93-4c36-b770-ddb0827a50b3)

**Routing :** 
![image](https://github.com/user-attachments/assets/ee2b0703-46b3-4f64-96d0-928c9153fe75)

**Basic :** 
![image](https://github.com/user-attachments/assets/ee2b0703-46b3-4f64-96d0-928c9153fe75)

**Comment by alireza0** [comment]
درود بر شما
بیشتر تنظیماتی که انجام دادین اضافه هستن. امیدوارم دلیل خاصی داشته باشید.
نرم افزار streisand از ech پشتیبانی نمیکنه میتونه دلیل عدم اتصال باشه.
لینک مورد استفاده برای نرم افزار سینگ باکس فقط ساب جیسون میتونه باشه. تصویر qr-code سینگ باکس فقط برای اسکن توسط نرم افزار اندرویدی اضافه شده.

اگر تنظیم dns سرور رو به دلیل باگ کلاینت سینگ باکس تغییر دادید باید بگم جای اشتباهی رو تنظیم کردین. باید توی تنظیمات ساب جیسون اینکار رو انجام بدید.

**Comment by roozbehalamdari** [comment]
یک دنیا سپاس از راهنمایی های خوبت ، دمت گرم برم ببینم چه میکنم ☺️❤️
