### ISSUE TITLE
ایده طراحی برای هاست

### ISSUE THREAD

**Issue by Shellgate** [alireza0/s-ui#22]
سلام و خسته نباشید مدتی هست که یک روش خاص فکرم رو درگیر کرده

اگر ما بتونیم پنل رو برای وب سرور ها طراحی کنیم به طوری که مثلا قابل اجرا روی cpanel و wordpress و سایر مواردی که برای میزبانی وب طراحی شدن میشه از هاست برای سرور استفاده کرد و هزینه ها کاملا پایین میاد

**Comment by alireza0** [comment]
درود بر شما
این مورد رو باید خود هاستینگ ها انجام بدن. بعضیهاشون پنل های مختلفی رو ساپورت میکنن و اتوماتیک اجرا میکنن.
