### ISSUE TITLE
ادرس داخل اینباند

### ISSUE THREAD

**Issue by nimakol** [alireza0/s-ui#221]
سلام.موقع ساخت اینباند در قسمت ادرس میشه مثل external proxy ای پی تمیز وارد کرد؟چون وقتی وارد میکنم سینگ باکس غیر فعال میشه.نحوه وارد کردن ادرسی بغیر از ادرس خود پنل چیست؟

**Comment by DeadSecure** [comment]
بله میشه
وارد تب client side بشید
از قسمت Multi Domain میتونین هر تعداد دامین میخواین اضافه کنین
درضمن برای هر دامین هم میتونین گزینه MULTI DOMAIN OPTIONS رو بزنید تیک Remark رو بزنید تا بتونید برای اون آدرس یک نام هم انتخاب کنید که به اخر نام کانفیگ اضافه میشه.
