### ISSUE TITLE
S-UI restart upon adding new client

### ISSUE THREAD

**Issue by bjerfan** [alireza0/s-ui#226]
Hello dear alireza, great having S-UI fully released. 2 problems or rather features, One is that upon adding new clients, s-ui restarts causing every user to disconnect and reconnect again, and second, how can we make the configs limited users like in the other ui panel. is it going to be a feature or not?

**Comment by alireza0** [comment]
Hello @bjerfan ,
Thank you for your kind consideration.
Sing-box core hasn't  this ability to change on the fly ( like api ).
In next release I will use a better control for reloading sing-box which is more faster.
But still it is not - on the fly -

There is no connection limit planned to be run on this panel.
