### ISSUE TITLE
سیو نشدن

### ISSUE THREAD

**Issue by asd1asd00000** [alireza0/s-ui#227]
در ابونتو 22 تست کردم بدون دامنه یه ولس و وی مس خیلی ساده بدون تی ال اس ساختم اما وقتی گزینه اخر فعال کردن کنترل ترافیک را فعال میکنم پنل قادر به سیو کردن نیست و ارور 502 میدهد و سیو نمیشود
در صورتی که گزینه کنترل ترافیک را فعال نکنم سیو میشود و به درستی کار میکند

**Comment by alireza0** [comment]
لطفا برای گزارش صحیح و قابل درک باگ، اطلاعات درخواست شده رو حتما ارسال کنید.
