### ISSUE TITLE
The flow control settings of vless should be placed in the inbound settings rather than in the user settings.

### ISSUE THREAD

**Issue by lingbaoboy** [alireza0/s-ui#228]
The flow control settings of vless should be placed in the inbound settings rather than in the user settings. Currently, the flow control settings of vless are placed in the user settings. If there are two inbounds, one using vless+V2Ray+REALITY and the other using vless+REALITY+tcpbrutal, since using tcpbrutal means Vision cannot be used, the user can only choose between tcpbrutal and Vision, and cannot have both. If the flow control settings of vless are placed in the inbound settings, then a user can use both of these inbounds.

**Comment by alireza0** [comment]
Do you have any documentation or resource for this inconsistency ?

**Comment by alireza0** [comment]
Please provide a report with full data.
Thanks
