### ISSUE TITLE
rsyslog Error

### ISSUE THREAD

**Issue by hzdlive** [alireza0/s-ui#229]
syslog  | rsyslog appliance version 2018-06-26 (1530020232) - http://www.syslogappliance.de
syslog  | Copyright (C) 2018 by Rainer Gerhards and Adiscon GmbH - released under ASL 2.0
syslog  | 
syslog  | WARNING: this is an experimental container - do not use in production
syslog  | 
syslog  | Using rsyslog configuration file: /etc/rsyslog.conf
syslog  | ERROR: command not known: sh -c touch /config/container_config
syslog  | 
syslog  | docker run --read-only <container-name> command
syslog  | where command is one of:
syslog  | rsyslog     - run rsyslog (default)
syslog  | help        - display this help message
syslog  | show-work   - list the /work area
syslog  | show-config - display the current container config
syslog  | edit-config - edit container config (with vi editor, press <ESC>ZZ to quit)
syslog  | bash        - start an interactive shell (<CTL>-d terminates)
syslog  | 
syslog  | volumes:
syslog  | /log        - log file store (if used)
syslog  | /work       - rsyslog work files; do not share with multiple instances
syslog  | /config     - configuration files, can be mounted read-only once finalized
syslog  | 
syslog  | listening ports:
syslog  | 514/udp     - syslog (udp)
syslog  | 514/tcp     - syslog (plain tcp)
syslog  | 1601/tcp    - RELP
syslog  | 
syslog  | rsyslog appliance version 2018-06-26 (1530020232) - http://www.syslogappliance.de
syslog  | Copyright (C) 2018 by Rainer Gerhards and Adiscon GmbH - released under ASL 2.0
syslog  | 
syslog  | WARNING: this is an experimental container - do not use in production
syslog  | 
syslog  | Using rsyslog configuration file: /etc/rsyslog.conf
syslog  | ERROR: command not known: sh -c touch /config/container_config
syslog  | 
syslog  | docker run --read-only <container-name> command
syslog  | where command is one of:
syslog  | rsyslog     - run rsyslog (default)
syslog  | help        - display this help message
syslog  | show-work   - list the /work area
syslog  | show-config - display the current container config
syslog  | edit-config - edit container config (with vi editor, press <ESC>ZZ to quit)
syslog  | bash        - start an interactive shell (<CTL>-d terminates)
syslog  | 
syslog  | volumes:
syslog  | /log        - log file store (if used)
syslog  | /work       - rsyslog work files; do not share with multiple instances
syslog  | /config     - configuration files, can be mounted read-only once finalized
syslog  | 
syslog  | listening ports:
syslog  | 514/udp     - syslog (udp)
syslog  | 514/tcp     - syslog (plain tcp)
syslog  | 1601/tcp    - RELP
syslog  |

**Comment by alireza0** [comment]
New version is not released yet. Please wait till next release
