### ISSUE TITLE
تغییر رمز پنل

### ISSUE THREAD

**Issue by MasoudRahmani** [alireza0/s-ui#23]
باسلام
احتراما، با اینترنت ایران و بخصوص نبودن تنظیمات cli ریموت زدن به سرور و انجام تنظیمات کار بسیار دشواری و در حال حاضر امکان تغییر رمز پنل وجود نداره و این عامل اجازه نمیده پنل رو در دسترس عموم باز کرد و حتما باید ip خاص تنظیم کرد که دردسر داره، اگر امکانش هست تغییر رمز و پسورد آدمین رو اضافه فرمایید.

باتشکر

**Comment by oneoneishere** [comment]
> باسلام احتراما، با اینترنت ایران و بخصوص نبودن تنظیمات cli ریموت زدن به سرور و انجام تنظیمات کار بسیار دشواری و در حال حاضر امکان تغییر رمز پنل وجود نداره و این عامل اجازه نمیده پنل رو در دسترس عموم باز کرد و حتما باید ip خاص تنظیم کرد که دردسر داره، اگر امکانش هست تغییر رمز و پسورد آدمین رو اضافه فرمایید.
> 
> باتشکر

امکان تغییر رمز از طریق خود پنل فعلا فراهم نشده ولی خودتون میتونید داخل فایل دیتابیس دستی بدید

**Comment by MasoudRahmani** [comment]
ممنون. یک راهنمایی میفرمایید دیتابیس کجاست و با چی باز کنم؟

**Comment by oneoneishere** [comment]
> ممنون. یک راهنمایی میفرمایید دیتابیس کجاست و با چی باز کنم؟

مسیر دیبتابیس:
/usr/local/s-ui/db/

با sqllitestudio میتونید ویرایش کنید، رایگان هم هست
فقط حواستون باشه که حتما باید با یوزر روت تغییرات رو اعمال کنید

**Comment by MasoudRahmani** [comment]
ممنون

**Comment by alireza0** [comment]
این ویژگی در نسخه جدید در پنل و محیط متنی اضافه شده.
