### ISSUE TITLE
The inbound setting seems to lack the relevant settings of reality

### ISSUE THREAD

**Issue by soulwood** [alireza0/s-ui#230]
I originally wanted to set up the VLESS+reality inbound, but I didn’t see any related options aboud REALITY in the TLS column, and the template I set up in the TLS settings couldn’t be applied, so I wanted to know how to set it up, and whether I could put REALITY in a more prominent position.

**Comment by alireza0** [comment]
Which kind of configuration you need to setup which is not possible to apply ?

**Comment by soulwood** [comment]
I want a VLESS + REALITY inbound, and I can't find the REALITY settings.

**Comment by alireza0** [comment]
You should create a new TLS config and use it in vless invound
