### ISSUE TITLE
وارپ برای یک ورودی

### ISSUE THREAD

**Issue by dispel123** [alireza0/s-ui#231]
آیا امکانش هست که یک ورودی یا کاربر رو از وارپ رد کرد؟ اگه میشه ممکنه توضیح بدین؟

**Comment by alireza0** [comment]
بله.
میتونید از قوانین مسیریابی استفاده کنید و ترافیک کاربر و/یا اینباند خاص رو به خروجی مد نظرتون بفرستید.

**Comment by dispel123** [comment]
اینو متوجه هستم فقط بعد نصب وارپ روی vps چجوری outbound تنظیم کنم براش؟ باید از نوع socks باشه؟
