### ISSUE TITLE
نحوه بکاپ گرفتن از دیتابیس

### ISSUE THREAD

**Issue by H4m3d84** [alireza0/s-ui#233]
دروود و عرض خسته نباشید...
آیا راهی برای بکاپ گرفتن از دیتابیس وجود داره؟ مسیری که فایل دیتابیس اونجا قرار گرفته کجاست؟ آیا تمامی تنظیمات پنل تو این دیتابیس اومده و با ریستور کردنش میشه پنل رو روی سرور دیگه با همون تنظیمات و یوزرها بالا آوورد؟
ممنون از پاسخ

**Comment by armanpier** [comment]
باتوحه به شباحت ساختار فولدر بندی s-ui با X-ui من دیتا بیس رو پیدا کردم , که در این مسیر هست»
/usr/local/s-ui/db

اگر فرصت کردم تست میکنم ببینم درسته یا نه اگرم کسی تونست تست کنه خوبه

**Comment by ErfanTech** [comment]
> مسیری که فایل دیتابیس اونجا قرار گرفته کجاست؟

[`/usr/local/s-ui/db`](https://github.com/alireza0/s-ui/blob/39022c1b2deb355ed6b2dc946f8e778204268970/backend/config/config.go#L62)

**Comment by alireza0** [comment]
به جز مسیری که دوستان اشاره کردن، حتما باید فایل config.json هم کپی بگیرید. اطلاعات زیادی فقط همینجا ذخیره میشه.

```bash
/usr/local/s-ui/bin/config.json
```
