### ISSUE TITLE
مشکل در اجرا شدن singbox

### ISSUE THREAD

**Issue by f6rhad** [alireza0/s-ui#234]
دلیل این مشکل چیه؟؟
singbox تو پنل اجرا نمیشه
آیا راه حلی داره؟ سرور رو ریستارت کردم پنل رو آپگرید و داونگرید کردم درست نشد.

Jul 20 11:54:11 ubuntu systemd[1]: sing-box.service: Failed with result 'exit-code'.
Jul 20 11:54:11 ubuntu systemd[1]: Stopped sing-box service.
Jul 20 11:54:36 ubuntu systemd[1]: Started sing-box service.
Jul 20 11:54:36 ubuntu runSingbox.sh[2083]: FATAL[0000] decode config at config.json: inbounds[2].listen: ParseAddr("***.***shmarkets.online"): unexpected character (at "***.***shmarkets.online")
Jul 20 11:54:41 ubuntu runSingbox.sh[2081]: Sing-Box with PID 2083 crashed. Breaking the loop...
Jul 20 11:54:41 ubuntu systemd[1]: sing-box.service: Deactivated successfully.
-- Boot 8bb48dd77fdb441f9f754347ca9e26d8 --
Jul 20 11:55:34 ubuntu systemd[1]: Started sing-box service.
Jul 20 11:55:35 ubuntu runSingbox.sh[1089]: FATAL[0000] decode config at config.json: inbounds[2].listen: ParseAddr("***.***shmarkets.online"): unexpected character (at "***.***shmarkets.online")
Jul 20 11:55:39 ubuntu runSingbox.sh[1087]: Sing-Box with PID 1089 crashed. Breaking the loop...
Jul 20 11:55:39 ubuntu systemd[1]: sing-box.service: Deactivated successfully.

**Comment by arashtaheri1988** [comment]
دقیقا منم همین مشکل دارم

**Comment by alireza0** [comment]
شما به جای آدرس IP ، دامنه گذاشتید.
بخش listen مربوط به دامنه نیست و باید توش یکی از IP های سرور رو بذارید و یا :: که به معنی همه IP های سروره.
