### ISSUE TITLE
bug!!

### ISSUE THREAD

**Issue by now04551** [alireza0/s-ui#236]
Hello, I really like the software you've developed, but I've discovered a serious bug. When I use the Shadowsocks protocol and simultaneously assign inbound connections to two users (same inbound node, different accounts/passwords), the UDP port allocation fails due to conflicting usage. I've verified this issue multiple times, and it's definitely a bug. Could you please assist in fixing this? Thank you.

**Comment by now04551** [comment]
Two users compete for UDP port allocation.

**Comment by alireza0** [comment]
Port allocation is not on client but inbound.

**Comment by now04551** [comment]
<img width="687" alt="BUG!!" src="https://github.com/user-attachments/assets/b75e802c-6a46-4576-9fbb-362c59a7c706">
![BUG!!3](https://github.com/user-attachments/assets/1b9f51b1-8069-4364-a63b-51db9965347f)
![BUG!!2](https://github.com/user-attachments/assets/91ff6221-a85a-41c1-9ff4-755ec705d6a3)
![BUG!!1](https://github.com/user-attachments/assets/d403e4df-8ad4-4d9e-9eb5-ed908d4b89e9)

**My inbound configuration is correct; it's a bug in the user system of this program. Please fix it.**

**Comment by now04551** [comment]
![BUG!!1](https://github.com/user-attachments/assets/1dd23082-c103-4ebf-b157-624c4ef7cbd6)
![BUG!!2](https://github.com/user-attachments/assets/df319257-6907-42c4-9d9c-9ffd3f17dad2)
![BUG!!3](https://github.com/user-attachments/assets/b016ebaf-769a-4cc2-b31d-d2181e3e5803)
