### ISSUE TITLE
فرگمنت

### ISSUE THREAD

**Issue by nimakol** [alireza0/s-ui#237]
سلام.این پنل قابلیت فرگمنت هم داره؟چیزی پیدا نکرم من

**Comment by alireza0** [comment]
درود بر شما
هسته سینگ باکس از قابلیت فرگمنت پشتیبانی نمیکنه

**Comment by MoSi8160** [comment]
@alireza0 
من یکی از کانکشن هایی که ساختم رو فرگمنت زدم از طریق [این آدرس](https://fragment.github1.cloud/) روی دامنه فیلتری که داشتم و کار میکرد
ایکاش شما هم این قابلیت رو بیارید که بتونیم کانفیگ های روی سابسکریپشن رو فرگمنت کنیم
