### ISSUE TITLE
My inbound configuration is correct; it's a bug in the user system of this program. Please fix it.

### ISSUE THREAD

**Issue by now04551** [alireza0/s-ui#242]
My inbound configuration is correct; it's a bug in the user system of this program. Please fix it.

**Comment by now04551** [comment]
<img width="687" alt="BUG!!" src="https://github.com/user-attachments/assets/da39de9c-0fea-417b-81f0-0c1f642d581b">
![BUG!!1](https://github.com/user-attachments/assets/480cc2d7-7c8c-4677-bc77-5cc9cda28a58)
![BUG!!2](https://github.com/user-attachments/assets/b4bb7ea7-9fef-41aa-93c7-85a59cdb2cc8)
![BUG!!3](https://github.com/user-attachments/assets/293f3a02-935b-4305-9dd3-9d4b2831b12a)

**Comment by now04551** [comment]
![BUG!!1](https://github.com/user-attachments/assets/e3b06809-882f-4a4f-940a-0cb492f701ee)
![BUG!!2](https://github.com/user-attachments/assets/26a78cd1-1d6c-4aae-95d5-e506a3d80c20)
![BUG!!3](https://github.com/user-attachments/assets/1ad9d2ae-b8f5-497e-a8c4-cbd37b70acc1)

**Comment by now04551** [comment]
Creating two users on the same line causes UDP port anomalies.

**Comment by alireza0** [comment]
It is not clear how did you configure the inbounds.
Thus, we can not re-produce your configuration to finding the error that you want to talk about.

To be able to help you, you should provide more data.
Could you please provide us the JSON configuraiton of your inbound ?

P.S. The connection is between core and client. Panel is only providing config. If there is any problem in config which could be better, just mention it or provide me a step by step guid to produce this problem.
If I can help to provide better configuration, all the users could use this benefit.
If it is related to upstream packages, then we cannot do anything. You should report it to the right package developer.

**Comment by now04551** [comment]
"I've set up 8 Shadowsocks inbound protocols. The outbound protocol points to an IPv4 internal network address, and through routing protocol, the inbound proxy protocol is directed to multiple IPv4 public network addresses bound to my server. I've created two users, each using these 8 Shadowsocks inbound points. When I use both users simultaneously, they compete for UDP protocol, causing abnormalities. When I disable UDP for one user, everything works fine, indicating an issue with S-UI panel's UDP allocation for users. The client-side proxy software is not the problem, as I've tried multiple clients and still encounter UDP issues on the server side."

**Comment by now04551** [comment]
When I keep only one user (disable other users), the UDP protocol communicates normally.

**Comment by now04551** [comment]
At the same node with the same configuration, this issue doesn't exist on your X-UI panel. However, there is an issue on the S-UI panel, likely due to differences in panel core architectures. (Very certain there is a bug).

**Comment by alireza0** [comment]
By your description, it is not related to the panel, but to the core/shadowsocks codes.
Please open an issue to the related repo
