### ISSUE TITLE
direct traffic by ip and domain

### ISSUE THREAD

**Issue by mmpma** [alireza0/s-ui#243]
درود برشما
آیا قابلیت دایرکت کردن ترافیک در پنل قرار گرفته؟ اگر بله ، لطفا بفرمایید به چه صورتی می باشد. آموزش های در سطح اینترنت باعث کرش کردن هسته میشود.

**Comment by alireza0** [comment]
درود بر شما
بله از نسخه های اولیه امکان ایجاد rule_set و rules وجود داشت.
این مخزن و ایشو ها بیشتر برای کدها استفاده میشه.
آموزش ها رو میتونید جستجو کنید.

**Comment by mmpma** [comment]
درود
بله طبق اموزش ها همگی انجام شده ولی وقتی تست میگیرم ، کماکان با ای پی سرور باز میکند.
![Screenshot_20240725_164514_Chrome](https://github.com/user-attachments/assets/b2fb941b-a7a8-41cc-9571-93a0c36c192a)
![Screenshot_20240725_164528_Chrome](https://github.com/user-attachments/assets/18bb5817-0f8c-4ce6-a835-0f1f29060f9c)


باتشکر

**Comment by alireza0** [comment]
ولی سوال شما دایرکت کردن پنل (سرور) بود.
اگر میخواید کلاینت دایرکت بشه باید از ساب جیسون استفاده کنید و توی بخش خودش تنظیم کنید

**Comment by mmpma** [comment]
غیر از ساب جیسون راه دیگه نیست؟
بعضی برنامه ها قبول نمیکنن

**Comment by alireza0** [comment]
هیچ راهی نیست مگر با تنظیم دستی توی کلاینت
