### ISSUE TITLE
tuic NOT work

### ISSUE THREAD

**Issue by mmpma** [alireza0/s-ui#244]
درود بر شما 
مرسی از زحمات
با تلاش های فراوان و تست های مختلف به هیچ وجه نمیتوانم از پروتکل tuic با دامنه استفاده کنم.
یا هسته کرش میکند و یا در اپلیکشن ها پینگی نمیگیرد.
از اموزش قرار گرفته در ایشو دیگر اشتفاده کردم ولی جاره ساز نبوئ

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
لطفا بیشتر جستجو کنید و از روش هایی که دوستان تنظیم کردن #116 استفاده کنید

**Comment by mmpma** [comment]
درود بر شما
بله مو به مو همانند آن ها انجام دادم ولی در کلاینت ، تایم اوت میدهد.
![Screenshot_20240725_164145_Chrome](https://github.com/user-attachments/assets/8018ebb3-9373-4b31-b2b6-4ae2eb808fd8)

**Comment by alireza0** [comment]
این نتیجه به خیلی عوامل بستگی داره!
ممکنه توی شبکه شما این پروتکل فیلتر باشه

**Comment by behroozvonly** [comment]
ببخشید، چطور میشه از پنل allow insecure رو روی کانفیگ ها فعال کرد؟

**Comment by alireza0** [comment]
@behroozvonly 
توی تنظیم گواهی ها (tls) میتونید تنظیم کنید

**Comment by mmpma** [comment]
> این نتیجه به خیلی عوامل بستگی داره! ممکنه توی شبکه شما این پروتکل فیلتر باشه

پس چرا با ezpz به راحتی وصل میشود؟

**Comment by alireza0** [comment]
تفاوت خروجی ها رو بررسی کنید متوجه میشید
