### ISSUE TITLE
بالا نیومدن پنل

### ISSUE THREAD

**Issue by ba6066** [alireza0/s-ui#245]
سلام دوستان
من پنل رو نصب کردم اما هنگامی که می خوام وار پنل از طریق مرورگر بشم صفحه سفید می مونه و باز نمیشه که بتونم رمز و نام کاربری وارد کنم؟ با مرورگر مختلف و دو اپراتور امتحان کردم باز نشد

**Comment by PashaGH8101** [comment]
برای اینکه پنل باز بشه دو مورد رو حتما چک کنید :
۱. با زدن `UFW status`  ( اگر از سیستم عامل Ubuntu استفاده میکنید) وضعیت firewall سیستم رو چک کنید اگر یک لیست براتون آورد یعنی فعال هستش و در حال اجرای قوانینی است که قبلا بهش گفته بودید 
میدونید برای رفع این مشکل از `UFW allow 2096` یا هر پورت دیگه ای که پنل دادید استفاده کنید 
۲. برای امنیت بیشتر پنل و دسترسی محدود تر افراد به پنل ، یک مسیر هنگام نصب ایجاد می‌کنه 
اگر تنظیمات پنل رو دستکاری نکرده باشد مسیر احتمالا /app/ می‌باشد که به این صورت شما میتونید بهش دسترسی داشته باشید: 
`Http://(server IP): (panel port)/app`
 مثلا اگر آی پی سرور من `۱.۱.۱.۱` باشه و پورت پنل` ۲۰۹۶` به این صورت من میتونم بهش دسترسی داشته باشم :
`Http://1.1.1.1:2096/app` 

برای دیدن مسیری که ایجاد شده داخل SSH سرور اگر `S-UI` رو بنویسید تنظیمات پنل براتون بالا میاد :
اول چک کنید که پنل در حالت running باشه ، بعد از طریق گزینه ها میتونید تنظیمات پنل رو مشاهده کنید .
برای دسترسی به تنظیمات مسیر و پنل فکر میکنم گزینه view panel credentials باشه که گزینه ۱۰ بود . ( دقیق حضور ذهن ندارم در حال حاضر) 

امیدوارم تونسته باشم مشکل شما رو برطرف کنم

**Comment by ba6066** [comment]
ممنون از راهنمایی شما
با فیلترشکن پنل بالا میاد اما بدون فیلترشکن نه

**Comment by ba6066** [comment]
مشکل دیگه ای که هست امروز هسته سینگ باس غیرفعال شده و رانینگ نمیشه

**Comment by PashaGH8101** [comment]
برای مورد اول که میفرمایید ، متأسفانه آی پی سرور شما به اصطلاح کثیف هستش و فیلتر عه 
یعنی اگر شما بخواید هر متد فیلترشکنی را روش اعمال کنید بعید بدونم به صورت مستقیم و ای پی وصل بشه ( مگر استفاده از روش تانل CloudFlared یا استفاده از CDN کلادفلر هستش )
[تانل کلاد فلر](https://ivpn.pro/how-to/vpn-with-filtered-ip-without-domain/)

برای قسمت دوم ابتدا باید Log هسته سینگ باکس رو مشاهده کنید که چه موردی باعث اختلال در کارش شده : 
![image](https://github.com/user-attachments/assets/9dccb7ad-b074-457e-b96c-12f555cb2828)
داخل پنل کنار گزینه لاگ را که بزنید اطلاعات لازم برای عیب یابی رو بهتون نشون خواهد داد.
