### ISSUE TITLE
Ability to return json config until first online

### ISSUE THREAD

**Issue by zoroky** [alireza0/s-ui#247]
سلام  علیرضا  جان 
یک  موضوعی که من در اکثر پنل ها دیدم  این بود که لینک سابی که  در اختیار کاربر قرار میگیره  میشه  بار ها  و بار ها باز بشه  حتی پخش  یا محتوای درونش  استخراج و  کنکاش بشه که  میتونه باعث لو رفتن دامین ای پی و... بشه  (درسته  که  ما محدودیت  حجم  رو  داریم ولی متاسفانه مثل اینکه  صرفا محدودیت حجم  از انتشار جلوگیری نمیکنه)  
راه حلی به نطرم میاد اینه که ریکوست از سمت کاربر تا وقتی بهش جواب برگرده که کاربر آنلاین نشده باشه 
و تا وقتی کاربر آنلاین نشده باشه بهش کانفیگ برگرده اینجوری تا حدودی هم میشه کانفیگ هارو تک کاربره کرد 
 ممنون میشم  این قابلیتو اضافه کنید.

**Comment by zoroky** [comment]
البته راه حل شخصی من برای  خودم  این بود که  یک متغیر (کانتر ) تعریف کردم که  محتوای لینک ساب هر کاربر رو  به تعداد عدد موجود در کانتر برمیگردونه و  اگه  صفر باشه خطاا میده توی وب هم بازش کنه پیغام تماس با پشتبانی رو  بر میگردونه .  یعنی مثلا  وقتی کار بر لینک خودشو وارد گوشی اول و  دوم  کرد عدد کانتر  از 2  به  صفر  میرسه  و دیگه  برای بار های بعدی لینک  باز نمیشه  تا عدد  رو  بالا تر  از  صفر ببریم  که در مواقع ایجاد تغییر و اپدیت  گذاشتن هم نیازه باز  که یک  کانتر 1 به  تمام کار بر ها بدم  تا بعد یه ساعت که  اپ گوشی شون  درخواست اپدیت  میکنه  اپدیت بهشون  برسه .
 البته  این  راه حلی بود که  من  تونستم  اجراش کنم. (البته  من از پنلی استفاده  نکردم  و روی یک  فلسک ساده  اینو اجرا  کردم )

**Comment by alireza0** [comment]
درود بر شما
لینک ساب باید بتونه بروزرسانی بشه و محدود کردنش کار درستی نیست.
برای امنیت بهتره با پارامترهای دیگه کار کرد.
