### ISSUE TITLE
سلام در اووبونتو 22 نصب شد با فایر وال خاموش روشن چک شد ه

### ISSUE THREAD

**Issue by armanem2** [alireza0/s-ui#25]
هنگام بالااوردن پنل صفحه تحت وب روی لودینگ میمونه وچیزی نمیاره در اوبونتو 22

**Comment by MasoudRahmani** [comment]
یک ریستارت بکن، مطمئن شو سرویس های سنگ باکس در حال اجراست و ببین پورت ها رو کس دیگه ای اشغال نکرده باشه.

**Comment by armanem2** [comment]
ری استارت جواب نداد یک ریبیلد میکنم دوباره تست میکنم

**Comment by MasoudRahmani** [comment]
جهت احتیاز یک بار هم uninstall بکن
```
systemctl disable sing-box --now
sudo systemctl disable s-ui  --now

rm -f /etc/systemd/system/s-ui.service
rm -f /etc/systemd/system/sing-box.service
systemctl daemon-reload

rm -fr /usr/local/s-ui
```

**Comment by armanem2** [comment]
داداش وضعیت سینگ باکس رانه چک کردم پاک کردم دوبتره ریختم بازم رو لودینگ گیر میکنه تو صفحه وب

**Comment by alireza0** [comment]
درود بر شما
لطفا اگر اطلاعات بیشتری دارید و مطمئن هستید که مشکل شما باگ هست، از تگ باگ استفاده کنید.
با داده های کمی که از مشکلتون فرستادین هیچکسی نمیتونه به شما کمک کنه.

**Comment by MasoudRahmani** [comment]
کنسول مرورگر رو باز کن ببین اونجا خطایی ننوشته، وب سرور مشکلی نداره؟

**Comment by armanem2** [comment]
الان با ریبید کردن واپدیت روی سیستم خام چک میکنم سسپاسگذارم

**Comment by armanem2** [comment]
ریبیلد کردم دوبتره نصب کردم این یک باگ هست چون در سه تا مرورگر چک کردم اگر اطلاعات خاصی نیاز دارید بگید تا از کجا میتونم براتون بفرستم تابررسی شود ممنون

**Comment by armanem2** [comment]
دوستان مشکل از سیستم بنده بود این تیکت رو میبندم
