### ISSUE TITLE
Is it possible to add a subscription import feature?

### ISSUE THREAD

**Issue by darcyg** [alireza0/s-ui#250]
Hi,
Currently, it is found that the S-UI panel does not have the ability to import subscriptions, only the ability to export them.

At present, SingBox does not have a Linux UI for the client side.
What is available are various GUI-based client software.
However, for lightweight service systems based on Armbian, most do not support a desktop or are used in systems without HDMI.
There is a need for a web-based client system similar to the v2raya service of v2ray/xray.
S-UI seems to provide a more complete set of SingBox web UI functionalities. But it is unclear how to add the subscription import feature.
It appears to only have the capability to generate subscriptions.
I am not sure if this feature can be added to make it more convenient for end users to use S-UI.
 Thank you.

**Comment by alireza0** [comment]
Hi
This panel is designed to work as a server rather than a client.
You can use sing-box core and just download json subscription and store it as config.json file beside core file.
