### ISSUE TITLE
مشکل در بلاک کردن آی پی های ایران

### ISSUE THREAD

**Issue by dispel123** [alireza0/s-ui#252]
سلام وقتی که در قسمت ruleset به صورت remote میخوام ip ایرانو بلاک کنم بعد اضافه کردن url مربوط به فایل srs آی پی های ایران هسته ی سینگ باکس از کار میفته از چند لینک فایل srs مختلف استفاده کردم و هیچکدوم کار نکردن و همین ارور رو میدن
log:
-- Logs begin at Wed 2024-07-31 08:31:23 UTC, end at Wed 2024-07-31 09:22:12 UTC. --
Jul 31 09:21:51 ovhdispel818xxxumfvue1vhv runSingbox.sh[52403]: INFO[0726] [4183626364 0ms] inbound/hysteria2[hysteria2-29727]: inbound connection from [::ffff:151.240.82.158]:63733
Jul 31 09:21:51 ovhdispel818xxxumfvue1vhv runSingbox.sh[52403]: INFO[0726] [4183626364 0ms] inbound/hysteria2[hysteria2-29727]: [e3DJt3KG] inbound connection to connectivitycheck.gstatic.com:80
Jul 31 09:21:51 ovhdispel818xxxumfvue1vhv runSingbox.sh[52403]: INFO[0726] [4183626364 0ms] outbound/direct[direct]: outbound connection to connectivitycheck.gstatic.com:80
Jul 31 09:22:10 ovhdispel818xxxumfvue1vhv runSingbox.sh[52355]: Signal received: restart
Jul 31 09:22:10 ovhdispel818xxxumfvue1vhv runSingbox.sh[52355]: Terminating singbox PID=52403
Jul 31 09:22:11 ovhdispel818xxxumfvue1vhv runSingbox.sh[55619]: INFO[0000] router: updated default interface ens3, index 2
Jul 31 09:22:11 ovhdispel818xxxumfvue1vhv runSingbox.sh[55619]: INFO[0000] v2ray-api: grpc server started at 127.0.0.1:1080
Jul 31 09:22:11 ovhdispel818xxxumfvue1vhv runSingbox.sh[55619]: INFO[0000] inbound/hysteria2[hysteria2-29727]: udp server started at [::]:29727
Jul 31 09:22:11 ovhdispel818xxxumfvue1vhv runSingbox.sh[55619]: INFO[0000] outbound/block[block-1hn]: blocked connection to cloud.lvlv.fun:8443
Jul 31 09:22:11 ovhdispel818xxxumfvue1vhv runSingbox.sh[55619]: FATAL[0000] start service: initialize rule-set[0]: initial rule-set: rs-Ksf: Get "https://cloud.lvlv.fun:8443/repo/MetaCubeX-meta-rules-dat-sing/geo/geosite/category-ir.srs": EOF

**Comment by alireza0** [comment]
درود بر شما
باید مطمئن باشید، لینکی که ازش استفاده میکنید توی سرور قابل دانلود باشه.
تنظیمات رو هم باید درست انجام بدید و توی ruleset از خروجی direct استفاده کنید
