### ISSUE TITLE
تجاری

### ISSUE THREAD

**Issue by Masouddhojaei** [alireza0/s-ui#253]
درود وقت بخیر
بسیار ممنون از توسعه پنل خوبتون
لطفا در صورت امکان قابلیت های مهم برای استفاده تجاری از این پنل رو هم اضافه بفرمایید، مثل بکاپ گرفتن، فعال شدن با اولین اتصال، ربات تلگرام و...
پروتکل های بسیار خوب و با کیفیتی ارائه شده فقط پنل هنوز جا داره تا بشه برای کاربر زیاد ازش استفاده کرد.
سپاس از شما

**Comment by alireza0** [comment]
درود بر شما
قبل از این پنل، پروژه های زیادی به صورت شخصی با هدف بهره برداری تجاری انجام شدند.
تجاری سازی هدف این پنل و پنل های رایگان دیگه نیست.
