### ISSUE TITLE
فعال سازی ipv6 در کانفیگها

### ISSUE THREAD

**Issue by skydarklord** [alireza0/s-ui#254]
سلام علیرضا جان خسته نباشید
چطور میشه از ipv6 در کانفیگها استفاده کنیم ؟ چون دیرتر فیلتر میشن بهتر از ipv4 هستند . من چند بار تو ساخت کانفیگ امتحان کردم اما موفق نشدم .

ممنون میشم راهنمایی کنید .

با تشکر

**Comment by alireza0** [comment]
درود بر شما
بهتره برای اینباند ها توی بخش تنظیمات سمت کلاینت، از مولتی دامین استفاده کنید
