### ISSUE TITLE
Problem In Streisand & My Configs

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#255]
درود علیرضا جان خوبی ؟ ببخشید یه سوال داشتم 
من جدیدا با کانفیگ های هیستریا و توییک که قبلا هم از همونا استفاده میکردم به یک
 مشکل عجیب خوردم ممنون میشم راهنماییم کنی 

### مشکل اول

کانفیگ هام‌ روی سینگ باکس راحت جواب میدن ولی روی Streisand که قبلا هم جواب میداد دیگه جواب نمیدن جدیدا 
چطوری باید بفهمم مشکل از کجاست ؟ البته یه سرور SWD خریدم با اون اکی هست ولی اون یکی سرورم متاسفانه له این مشکل خرده و نمیدونم از چیه 

خیلی هم دوست دارم یک کانفیگ بدم خدمتت ، شما هم تست کنی ولی حقیقت هیچ راه ارتباطی باهات ندارم ، اینجا هم نمیشه فرستاد 

### مشکل دوم

 جدیدا توی تلگرام ، ایردراپ همستر رو که میخواهم برم لود نمیشه و مدام باید تایید هویت کنم هر باز هم تیک رو میزنم که من انسان هستم ولی تاثیری نداره باز دوباره میگه تیک بزن  ! این رو هم ممنون میشم بگی مشکل از چیه و چطور باید حلش کنم ؟ ( این مشکل فقط روی گوشی من نیستا برای بقیه هم هست ) ( البته با کانفیگ های رایگان یا وی پی ان های رایگان این مشکل رو ندارم !
 

![image](https://github.com/user-attachments/assets/e14d17b1-4a44-4373-8e70-24108ee5fef8)

اگر هم امکانش هست واسه اینکه بتونم کانفیگم رو بفرستم که شما تستش کنی این جیمیل من هست لطفا یه Mail به من بزن بتونم ارسال کنم کانفیگ رو 🙏 سپاسگذارم از زحماتت 

My Gmail : parsv2@gmail.com

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
من داده های زیادی در این موارد ندارم و باید از دوستانی که کانفیگ های مناسب رو ارائه میدن کمک بگیرید.
