### ISSUE TITLE
there is no reality short id in sing-box json

### ISSUE THREAD

**Issue by x6ufeng** [alireza0/s-ui#256]
**Describe the bug**

there is no reality short id in sing-box json

**To Reproduce**

**Expected behavior**

Include short id in json

**Screenshots**

<img width="405" alt="Screenshot 2024-08-02 at 20 59 33" src="https://github.com/user-attachments/assets/d99525b5-053a-495f-8801-3f77f6417d40">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
Duplicate #224
