### ISSUE TITLE
Detailed settings of Multiplex in subscription link(json)

### ISSUE THREAD

**Issue by lonelylose** [alireza0/s-ui#257]
Thank you for your project. I can finally use sing-box more comfortably. Now only some details of the multiplex part can be set in inbound page(client side). Although the multiplex part is relatively simple, I hope this detailed option can be added. Thank you.

**Comment by alireza0** [comment]
Which part of mux do you want to be added ?
All possible configuration are exist now.

**Comment by lonelylose** [comment]
Outbound‘s part:
{
  "enabled": true,
  "protocol": "smux",
  "max_connections": 4,
  "min_streams": 4,
  "max_streams": 0,
  "padding": false,
  "brutal": {}
}

Now the outbound multiplex only has:

"multiplex": {
         "enabled": true
       },

**Comment by alireza0** [comment]
Are you sure?
![image](https://github.com/user-attachments/assets/f33c7b09-c45a-4ad1-aa2f-f3e081bf1316)

**Comment by lonelylose** [comment]
Apologies for not being clear initially. Let me clarify my request. The program generates a JSON subscription file with the "http://1.1.1.1:2096/sub/xxxxxxx?format=json" link. However, the generated JSON only includes "multiplex": { "enabled": true }. The issue seems to be related to the "client side" settings in the inbound section of the program. Specifically, the missing details related to multiplex, such as "protocol": "h2mux", "max_connections": 4".

Checking the frontend/src/layouts/modals/Inbound.vue file to add the necessary configuration may help this, I am not familiar with this, sorry. This way, the client should correctly use the generated JSON subscription link.

**Comment by alireza0** [comment]
Okay, I will take a look.

**Comment by alireza0** [comment]
I have removed automatic multiplex config for inbounds and add separated client side multiplex configuration in client side configuration.

Please build the codes or wait for new release.
