### ISSUE TITLE
امکان تفکیک ترافیک آپلود و دانلود

### ISSUE THREAD

**Issue by oneoneishere** [alireza0/s-ui#258]
سلام، وقت بخیر
داداش قبل از هرچیزی بگم به تکرار تشکر میکنم ازت، بابت همه زحمتهایی که میکشی و اینقدر کارهای مفیدی که کردی تابحال
یک پیشنهاد دارم، نمیدونم عملی هست یا نه
در بعضی از پروتکل ها مثل هیستریا2 وقتی مستقیم میزنیم سرعت دانلود عالیه سرعت آپلود خوب، ولی خب زود فیلتر میشه مخصوصا وقتی با هسته سینگ باکس پیاده میشه، میایم تانل میزنیم سرعت آپلود بهتر از قبل میشه ولی سرعت دانلود میاد پایین، میگم میشه یه کاری کنی سمت پنل که بشه تفکیک کرد ترافیک آپلود از سرور ایران رد بشه ترافیک دانلود مستقیم بیاد؟

این پیشنهاد رو به دوست تانل سازمون هم ارائه کردم ولی وقتی فکر میکنم به نظر میرسه سمت خود پنل شانس عملی شدنش خیلی بیشتره تا سمت تانل
اینم نمیدونم عملی باشه یا نه، به ذهنم میرسید که ترافیک مستقیم دانلود جوری دستکاری بشه که به نظر برسه فرد با IDM یا ابزارهای مشابه درحال دانلود هست، یا ترفندهای مشابه برای گول زدن سیستم
مطمئن نیستم ولی به نظرم اگر از همون ابتدا اینجوری باشه احتمال فیلترشدنش هم کمتر میشه
اگر به نظرت عملی باشه و صلاح بدونی میتونی با همکاری دوست عزیزمون رادکسوت عزیز شانس موفقیت این قضیه رو بیشتر کنی

**Comment by shengzehan** [comment]
I think port hopping can solve this problem.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و پیشنهادتون

بیشتر مشکلات اینچنینی به نحوه تنظیم و محل سرور و نوع استفاده برمیگرده.
باید از دوستانی که مدلهای درست کانفیگ رو ارائه میدن کمک بگیرید و همیشه بروز باشید.

ویژگی درخواستی شما توی هسته وجود نداره و نمیشه توسط پنل ارائه بشه
