### ISSUE TITLE
اقا دمت گرم خیلی خفن تر از ایکس یوای هستش از هر نظر

### ISSUE THREAD

**Issue by Kinggmahdi** [alireza0/s-ui#26]
دوستان توجه کنید بعد هر تغییری که میدید اون بالا سمت راست سیو رو باید بزنید وگرنه کار نمیکنه!!!!
اقا علیرضا دمتگرم خداقوت میگم بهت لطفا تو اپدیت بعد ui کار رو یه دستی بکش و رمز پنل هم بتونیم عوض کنیم عالی میشه ((((: 
در کل خیلی خفنه بنظرم از xray بهتره

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی شما
من سعی میکنم به مرور زمان به همه این بخش ها برسم.
هنوز همه این پروتکل ها به راحتی قابل استفاده نیستند و نرم افزار های سمت کاربر باید بروزرسانی های بیشتری انجام بدن.

**Comment by Rtping80** [comment]
> درود بر شما سپاسگزارم از همراهی شما من سعی میکنم به مرور زمان به همه این بخش ها برسم. هنوز همه این پروتکل ها به راحتی قابل استفاده نیستند و نرم افزار های سمت کاربر باید بروزرسانی های بیشتری انجام بدن.

داداش بک اپ چه جوری بگیرم؟
