### ISSUE TITLE
Duplication of the same thing.

### ISSUE THREAD

**Issue by Maneeha1234SL** [alireza0/s-ui#260]
<img width="769" alt="image" src="https://github.com/user-attachments/assets/c9462842-1318-4f68-b8b8-6485852c7949">

This needs to be explained properly to improve identification.

S-UI Start Automatically :

Sing-Box Start Automatically :

**Comment by alireza0** [comment]
Thank you your report.
Please be informed that it is not a bug.
It is already clear. But we can make it better as you suggested
