### ISSUE TITLE
Add s-ui restart button to panel.

### ISSUE THREAD

**Issue by Maneeha1234SL** [alireza0/s-ui#261]
![image](https://github.com/user-attachments/assets/929ce44b-910e-457d-bd7a-c4fdf8cbff83)

![Screenshot 2024-08-06 101644](https://github.com/user-attachments/assets/3dc806d6-afab-4fd0-8310-671a3eaa74d5)

Feature Request: Sing-box Core Alpha Support and Panel Update Capability

It would be beneficial to have the following features:

Option to Switch to Sing-box Core Alpha:

Provide a feature to switch to the sing-box core alpha version. This would allow users to test and utilize the latest alpha releases.
Update Core from the Panel:

Implement a functionality similar to x-ui that enables users to update the core from the panel. This feature should include an easy-to-use option for checking, downloading, and applying core updates directly from the panel interface.
These enhancements would improve the flexibility and usability of the sing-box system. Thank you for considering these additions.

**Comment by alireza0** [comment]
Thank you for sharing your idea.
But sing-box is not as same as xray. In sing-box core's builded packages, some features are disabled by default. We need to build a custom version
