### ISSUE TITLE
 Improved TLS Configuration Management

### ISSUE THREAD

**Issue by Maneeha1234SL** [alireza0/s-ui#262]
To enhance the user experience and reduce issues when configuring TLS settings, please consider the following improvements:

Move TLS Option Section:

Relocate the TLS option section from the TLS settings to the Inbounds configuration. This change will streamline the process by placing TLS settings directly within the context of the inbound configurations.
Enable TLS Option for Each Protocol:

Implement an option to turn on TLS for each protocol individually. This would allow users to enable TLS based on specific protocol needs, providing greater control and flexibility in configuration.
These updates would simplify the TLS configuration process and reduce potential issues. Thank you for considering this enhancement.

![Screenshot 2024-08-06 121406](https://github.com/user-attachments/assets/8dbc6344-15b9-478f-b414-5d827a3e582b)

![vlcsnap-2024-08-06-12h06m09s884](https://github.com/user-attachments/assets/300363f9-feaa-4429-b11a-4a6a090909c7)

**Comment by alireza0** [comment]
Thank you for sharing your idea. But it is against the common needs of users
