### ISSUE TITLE
مشکل در آپدیت ساب 

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#263]
درود علیرضا جان خوبی ؟ آقا یه سوال ؟ 

چرا موقع آپدیت کانفیگ توی برنامه ی سینگ باکس ورژن آیفون همش این اررور رو دریافت میکنم ؟ ( روی ۳تا از آیفونی ها اینجوریه ! )
مشکل از چی میتونه باشه ؟
**پنل و sing-box هم آخرین ورژن هستن**

![image](https://github.com/user-attachments/assets/0332a3d9-7981-420f-b7a4-8e6df48aad26)

**Comment by alireza0** [comment]
درود بر شما
به نظر میاد مشکل ارتباط دارین.
آدرس/دامنه پنل فیلتر یا محدود نشده؟

**Comment by roozbehalamdari** [comment]
> آدرس/دامنه پنل فیلتر یا محدود نشده؟

اتفاقا با check-host.net و host-tracker تست کردم اونجا اکی هست گویا ، اگر راه دیگه ای هست برای تست ممنون میشم بهم بگین.

نتیجه تست ها : 
![image](https://github.com/user-attachments/assets/053a8ffc-dfff-4da1-a4e5-6d52539bab60)
![image](https://github.com/user-attachments/assets/96c44b95-3c59-4de2-907e-cbf0bde3a3ba)

راستی یه سوال من ساب دامین سابم رو پروکسی روشن گذاشتما درسته که؟

**Comment by alireza0** [comment]
باید با تغییر تنظیمات تست کنید تا پیدا کنید که مشکل از کدوم بخشه.
شاید از تنظیمات cdn شما باشه
