### ISSUE TITLE
گزینه ریست sing-box داخل پنل نیست

### ISSUE THREAD

**Issue by HZabihi78** [alireza0/s-ui#264]
سلام و وقت بخیر
من از آخرین نسخه پنل استفاده میکنم
چندتا مشکل داره درخواست دارم بررسی و در نسخه بعدی در صورت امکان اصلاح بفرمایید

1 : گزینه ریست sing-box و s-ui داخل پنل نیست و اگر اشتباهی در داخل ساخت کانفیگ وجود داشته باشد و سینگ باکس stop شود دیگر نمیتوان آن را run کرد و باید داخل سرور از طریق ssh وارد شد و مجدد با گزینه ریست singbox گزینه 20 مشکل را حل کرد

2 : لطفا گزینه های مربوط به نصب و آپدیت geo-site و را مانند x-ui در منو نصب قرار دهید تا بتوان لیست سایت و دامنه های ایرانی را در سرور اضافه کرد و از طریق پنل دسترسی به سایت های ایرانی را بست لطفا گزینه بستن سایت های ایرانی را داخل پنل اضافه کنید
چند بار به صورت دستی انجام دادم اما اعمال نمیشود یا به درستی کار نمیکند

3 : بخش ساب پنل مشکل دارد و به درستی کار نمیکند 

4 : امکان ثبت اینباند با شماره پورت تکراری وجود دارد این موضوع موجب stop سینگ باکس می‌شود لطفا از ساخت اینباند خودداری کند

5 : در هنگام ساخت اینباند و کلاینت در صورتی که چندبار سیو را فشار دهیم همان اینباند و کلاینت چندبار ساخته می‌شود 

از همین جا میخوام از زحمت شما و آقای سنایی تشکر کنم واقعا عالی کار میکنید
از کار کردن با پنل شما لذت میبرم 
انشالله همیشه سالم و پایدار باشید 
باتشکر از محبت و لطف شما

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و پیشنهادات شما

۱. این پنل به ازای هربار درخواست، پنل رو ریستارت میکنه و نیازی به ریستارت دستی نیست!
در صورت کرش کردن، حداکثر بعد از چند ثانیه ریستارت میشه.
گزینه ریستارت در منو خط کد، کل سرویس رو ریستارت میکنه.

۲. این پنل با پنل های دیگه با هسته متفاوتی اجرا میشه و فایلهای جغرافیایی رو خودتون میتونید اضافه کنید.
در درخواست های دیگه این مورد اعلام شده. لطفا قبل از ایجاد درخواست جستجو کنید.

۳. از اینکه داده های کاملی ارائه میکنید ممنونم

۴. لطفا دقت کنید که پورت تکراری نسازید

۵. این مشکل هم تکراری است و همونطوری که جاهای دیگه گفتم، مشکل از پکیج هاست.
به محض فشردن دکمه ذخیره، مودال به حالت لودینگ میره و نمیتونید دوبار دکمه رو فشار بدید.
اگر تکرار میشه به دلیل تداخل اینترنتی و عدم کنترل توسط پکیج های استفاده شده است. در هر نسخه این پکیج ها بروز میشن.

پی نوشت:‌ لطفا تگ مناسب با درخواستتون انتخاب کنید و حتما سوالات رو جواب بدید.
اگر ایشو شما بسته میشه به دلیل عدم رعایت پروتکل های اعلام شده است.
بدون اطلاعات کافی هیج کسی نمیتونه به شما کمک کنه
