### ISSUE TITLE
تانل معکوس پنل به پنل

### ISSUE THREAD

**Issue by mahsamcse** [alireza0/s-ui#265]
با درود
ضمن تشکر فراوان از شما برای این پنل بی نظیر
واقعا درود به شرفتون

میخواستم بدونم همانند x-ui میتونیم تانل معکوس پنل به پنل پیاده کنیم ؟
من استفاده شخصی و خانوادگی دارم و در حال حاضر x-ui رو استفاده میکنم اما به شدت مایل هستم مهاجرت کنم به s-ui برای همین چون هنوز داکیومنت زیاد موجود نیست مجبور شدم اینجا بپرسم منو ببخشید از این بابت
وارپ هم یه راهنمایی کوچیک بکنید که میشه پیاده کرد یا نه ممنون میشم

امیدوارم بتونم در کنار شما و بقیه توسعه دهندگان این پروژه سهمه کوچکی در پیشرفتش داشته باشم
دمتون گرم

**Comment by mahsamcse** [comment]
ممنون از پاسخ شما
فقط قسمت ترکیبش با xray رو نفهمیدم منظور شما چیه !
یه سره نخی بدین منون میشم

**Comment by alireza0** [comment]
مفهوم chain of proxies یا زنجیره پراکسی ها، استفاده از چند مدل سرویس مختلفه که در نهایت به دست مشتری برسه.
یه توضیحاتی در این مورد [اینجا](https://alireza0.github.io/fa/docs/security/chains/#%DB%B5-%D8%B2%D9%86%D8%AC%DB%8C%D8%B1%D9%87-xray) نوشتم.

ولی چیزی که پیشنهاد میدم اینه که یه هسته xray-core توی سرورتون تنظیم کنید که به صورت reverse با سرور خارج در تماس باشه. بعد یه ارتباط socks بین s-ui و این هسته برقرار کنید و ترافیک رو به سمت اون هدایت کنید.
