### ISSUE TITLE
خطا در سینگباکس Aug 09 22:35:46 ...... systemd[1]: sing-box.service: Deactivated .successfully

### ISSUE THREAD

**Issue by mrn40** [alireza0/s-ui#266]
سلام این مشکل برام پیش اومده سرور ایران هست لطفا راهنمایی کنید [**Describe]) the bug**

**Comment by mrn40** [comment]
<img width="263" alt="Screenshot 2024-08-10 021436" src="https://github.com/user-attachments/assets/2cd4f87b-719a-4b42-a9a1-38702e510815">

**Comment by SeyedHashtag** [comment]
![Screenshot 2024-08-10 171246](https://github.com/user-attachments/assets/16d9ca53-ac2d-4f9c-992a-e92ca5db577b)

**Comment by SeyedHashtag** [comment]
پورت هیستریا روی 53 گذاشته شد ولی هسته ایستاد و هیچجوره برنگشت. همچنین با تعویض masquerade هم هسته دچار حالت مشابهی شد.

**Comment by mrn40** [comment]
> پورت هیستریا روی 53 گذاشته شد ولی هسته ایستاد و هیچجوره برنگشت. همچنین با تعویض masquerade هم هسته دچار حالت مشابهی شد.

داداش بنظرم بهتره فعلا vless یا vmessرو امتحان کنیم

**Comment by alireza0** [comment]
درود بر شما
این مشکل در سرویس سینگ باکس وجود داره و در نسخه بعد حل خواهد شد.
لطفا یا سرویس رو بروزرسانی کنید و یا منتظر نسخه بعدی باشید.
برای راه حل موقت میتونید از داخل سرور، سرویس سینگ باکس رو ریستارت کنید.

**Comment by mrn40** [comment]
داداش دمت گرممم.... بی صبرانه منتظر نسخه جدید هستیم

**Comment by SeyedHashtag** [comment]
درود بر شما
