### ISSUE TITLE
[Bug]: ShadowTLS parameter issues

### ISSUE THREAD

**Issue by radiumatic** [alireza0/s-ui#267]
**Describe the bug**

1. The handshake server port doesn't get added to the configuration 
2. The port value in the "add handshake server" feature gets added to the configuration as str, not int.

**To Reproduce**
1. Create a ShadowTLS inbound and set the handshake server.
2. Add a shadowsocks server and add it as the detour to the ShadowTLS server.
3. Create a chain config in either NekoRay or NekoBox and put the ShadowTLS first, then the shadowsocks config. 
4. You can see in the server logs that it tries to connect to [handshake_server]:0 instead of whatever port you specified and the port isn't present in the sing-box config.

**Expected behavior**

Ports being added correctly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
Thank you for your report. I will take a look and fix it soon

**Comment by radiumatic** [comment]
I think this is fixed? @alireza0

**Comment by alireza0** [comment]
It is fixed now. Please build it or wait for next release.
