### ISSUE TITLE
مشکل در واتس اپ

### ISSUE THREAD

**Issue by HajHadi76** [alireza0/s-ui#268]
درود وقتتون بخیر ، من تانل پنل به پنل زدم همه جا اوکیه بجز واتس اپ ، فقط پیام ارسال میشه آپلود و دانلود وضعیت و ... نداره مشکل چیه

**Comment by alireza0** [comment]
درود بر شما
این مشکل مربوط به پنل نیست. لطفا در انجمن ها و گروه های کاربران مطرح کنید تا به جوابتون برسید
