### ISSUE TITLE
Move flow settings to inbound

### ISSUE THREAD

**Issue by radiumatic** [alireza0/s-ui#269]
**Is your feature request related to a problem? Please describe.**

You can't have a user using both normal vless configs and xtls ones with the correct design.

**Describe the solution you'd like**

Moving the flow option to inbound settings. I.e the flow settings being unique to each inbound.

**Describe alternatives you've considered**

**Additional context**

**Comment by alireza0** [comment]
Flow is a part of users config in inbound.
It is deployed and tested and fully convertable on each inbound setup.
If you know any problem please raise another issue with proper evidences.

**Comment by radiumatic** [comment]
@alireza0 Sorry, the issue wasn't clear enough.

Problem is, you can't have both tls (or non-tls) vless configs and xtls ones with the same users. The option to change the flow disappears once you add a non-xtls vless config.

**Comment by radiumatic** [comment]
> It is true, because flow have to be available only for tls enabled inbounds. Otherwise the core could not parse it and stops normal working.

Exactly. That's why I'm saying flow settings should be moved to and parsed based on the inbounds. How many times have you seen a situation that requires one user of an inbound to use xtls and the other to not?

**Comment by alireza0** [comment]
I can not count it. But it should be possible.
By default, users have flow value until you decide to change it for user.
When user is supposed to use flow, it will be added to all suitable inbounds.
It is true that there is no way if you want to remove it from specific inbounds only.
There is a fact in s-ui that inbounds are not stored in database and it is not possible to add a special change like this. Therefore, the best way is the current!
By this way you could define some users with/without flow. But on your suggested way it is not possible!
