### ISSUE TITLE
Hysteria2 is not working

### ISSUE THREAD

**Issue by natasun** [alireza0/s-ui#27]
Thanks for the script.
I installed it on Ubuntu 22, Hysteria2 is not working after a test. This is while with the same server, the same setting for Hysteria2, it's working when running with a different script.

**Comment by amirmbi** [comment]
Same problem, here!

**Comment by alireza0** [comment]
Could you please share your configuration ?

@amirmbi TUIC needs a proper client with specific configuration. Did you follow ? Please share your configuration.

P.S. Please check your sing-box status as well.

**Comment by amirmbi** [comment]
سلام علیرضا عزیز 

خسته نباشید بهت میگم برای پنل بی نظیری که توسعه دادی ، عالی هستی مثل همیشه 

استاتوس سینگ باکس  Active: active (running)  است. 

از توییک و هیستریا 2 استفاده میکنم بر روی نکو باکس ولی با پنل شما فقط تونستم vless و vmess استفاده کنم. نه هیستریا 2 و نه توییک رو نتونستم با پنل شما استفاده  کنم . در ادامه نمونه کافیگ ساخته شده رو براتون ارسال می کنم :

tuic://ce368701-02c5-4cfb-cb0d-b8e9a24652f5:UJSqvqyuh0@79.137.207.121:12345?congestion_control=cubic#in-50512

یه مورد هم است که برام عجیبه وقتی اینباند هیستریا 2 یا توییک ایجاد می کنم بدون اینکه  بخوام tls enable میشه عکسش رو براتون ارسال می کنم با اینکه تنظیمات tls خاموشه .... البته من با tls روشن و cetficate گرفته شده هم نتوانستم به توویک یا  هیستریا 2 استفاده کنم !!! (عکس را ضمیمه می کنم) 

نکته دیگر اینکه من در کانفیگ های قبلی که استفاده می کردم اصلا امکان tls گذاشتن بر روی پروتوکل هیستریا 2 و توییک وجود نداشت و همچینین گزینه ای که باید برای این کانفیگ ها اضافه کنید در پنل allow insecure می باشد. 

ممکن است توضیحات من ناقص باشد، باعث خوشحالی است اگر ابهامی در توضیحاتم بود بیشتر توضیح دهم. 

![TLS](https://github.com/alireza0/s-ui/assets/57032975/16169aa0-039c-44d3-9dd4-af0b94c77c3a)
![configuration](https://github.com/alireza0/s-ui/assets/57032975/e15ed716-7a07-4fb0-a61e-89df9be68811)

**Comment by natasun** [comment]
Same for me, I'm not limited to any configuration, therefore I tried many configurations. with or without SNI, with or without TLS, different ports, different setups. No result.

**Comment by natasun** [comment]
> Could you please share your configuration ?

@alireza0 Same for me, I'm not limited to any configuration, therefore I tried many configurations. with or without SNI, with or without TLS, different ports, different setups. No result.

**Comment by alidxdydz** [comment]
@alireza0 

سلام،
یادمه قبلا مخزن TinrLin/sing-box همه پروکسیا رو با هسته sing-box ایجاد میکیرد که الان حذف شده. البته تا حد زیادی از طریق Wayback Machine و مخزن فورک nmyo/sing-box قابل دسترسه. امیدوارم بتونه کمکی کنه.

**Comment by alidxdydz** [comment]
@alireza0

سلام،
یادمه قبلا مخزن [TinrLin/sing-box](https://github.com/TinrLin/sing-box) همه پروکسیا رو با هسته [sing-box](https://github.com/SagerNet/sing-box) ایجاد میکیرد که الان حذف شده. البته تا حد زیادی از طریق [Wayback Machine](https://web.archive.org/web/20231224131130/https://github.com/TinrLin/sing-box) و مخزن فورک [nmyo/sing-box](https://github.com/nmyo/sing-box) قابل دسترسه. امیدوارم بتونه کمکی کنه.

**Comment by alireza0** [comment]
Based on SingBox documentation, tls is mandetory for [hysteria](https://sing-box.sagernet.org/configuration/inbound/hysteria/#tls), [hysteria2](https://sing-box.sagernet.org/configuration/inbound/hysteria2/#tls) and [tuic](https://sing-box.sagernet.org/configuration/inbound/tuic/#tls)! Even if it is not mandetory in their base.

In my tests, Sing-Box will fail if there was no tls configuration. But you can try invalid certificate with manually check the `allow insecure` in client.

It works fine with me in nekoray by simple and complex configuration:
![image](https://github.com/alireza0/s-ui/assets/12573084/c034798b-3c41-4a52-b224-269074492d37)

I have tested it with nekobox in android with same successful result!
Please check your sing-box service status always after your configuration.
You can also check the sing-box service's status and log with:

```bash
systemctl status sing-box
journalctl -u sing-box
```

**Comment by amirmbi** [comment]
Dear @alireza0 

I would be truly grateful for your help and explanations. I will resolve my problem concerning your above description. 

You make my day. May you always have a feeling of sheer delight.

Best regards

From one of your fan ❤

**Comment by natasun** [comment]
Thank you very much @alireza0,
The difference with other scripts which are building hysteria2/TUIC configs with one click is that they are also generating a self-assigned SSL certificate automatically and add it to the config without user to notice, or some other scripts I noticed they ask the user to choose a self-assigned SSL or a domain SSL certificate. Therefore I think for the next updates it would be much nicer to make a self-assigned SSL generator if that's possible. Thanks.

**Comment by alireza0** [comment]
TLS and Domains control are defined in my road-map.
It takes time to make it mature and deploy it in the best way.

**Comment by nima1300** [comment]
> Based on SingBox documentation, tls is mandetory for [hysteria](https://sing-box.sagernet.org/configuration/inbound/hysteria/#tls), [hysteria2](https://sing-box.sagernet.org/configuration/inbound/hysteria2/#tls) and [tuic](https://sing-box.sagernet.org/configuration/inbound/tuic/#tls)! Even if it is not mandetory in their base.
> 
> In my tests, Sing-Box will fail if there was no tls configuration. But you can try invalid certificate with manually check the `allow insecure` in client.
> 
> It works fine with me in nekoray by simple and complex configuration: ![image](https://private-user-images.githubusercontent.com/12573084/305544993-c034798b-3c41-4a52-b224-269074492d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTMzMDQsIm5iZiI6MTcwOTc5MzAwNCwicGF0aCI6Ii8xMjU3MzA4NC8zMDU1NDQ5OTMtYzAzNDc5OGItM2M0MS00YTUyLWIyMjQtMjY5MDc0NDkyZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2MzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwN2VmZDAxYzAwMDAwMGEwNDAwYWU2ODg1MDEzMjE4NjU4NWQ3MTg2MTQ2Njg3ZDMzOGMzZGZmYzI5YWUwNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j6FBHfKsnppumiViZnD_C_P4VCWw6tgrpP6PL2mzLwM)
> 
> I have tested it with nekobox in android with same successful result! Please check your sing-box service status always after your configuration. You can also check the sing-box service's status and log with:
> 
> ```shell
> systemctl status sing-box
> journalctl -u sing-box
> ```

با سلام ، میتونید بگید چطور مسیر سرتیفیکت رو در سرور خودم پیدا کنم؟ ممنون

**Comment by alireza0** [comment]
@nima1300 
هر نرم افزاری مسیر خودش رو داره. بهتره از راهنماها و ویدیوهایی که وجود داره کمک بگیرید
