### ISSUE TITLE
User usage bug

### ISSUE THREAD

**Issue by setarehirani** [alireza0/s-ui#270]
Hello, thanks for the script.
There are times that I create a user with unmetered usage, and share the config with him, he uses, and when I decide to put a limitation like 80 GB, his usage will no longer work, so I can't get the user usage anyway, so the usage limitation should be set when creating the user.
Or sometimes when I set the usage limitation when creating the user, it works but the usage get stuck somewhere. For example I made a user and set his usage for 80 GB, he used it, and I see his usage is 2.60 GB now, but this no longer changes, even if user is online and using the service.

Another bug: subscription link is not working for IOS apps, for example Streisand.

Recommendation:
1. It could be so nice to change the view of the clients page, make them as compact as possible, like how you did it on your x-ui. So then if the users are more than the first view, it could be easier to handle without scrolling (probably having them into rows would work better)

Thank you.

**Comment by alireza0** [comment]
Hello @setarehirani ,

There is no difference between limitation in create time or edit. Database will update accordingly and should works fine. If you found any problem, please provide proper investigation result.

Usage will be counted only when traffic calculation is enabled for the user. If not, or changed, counting traffic will stop.

Subscription link is provided based on sing-box standard configuration. If some other apps does not support, just ask them to fix it. It is not a bug!

Thank you for your recommendation. this feature is already deployed 6 days ago by [this](https://github.com/alireza0/s-ui/commit/6f0df2d55554423e5e5b979f9796125068c67b9a) commit. Please wait for next release.

**Comment by setarehirani** [comment]
Sorry for insufficient information.
I searched more to find out what I have done. In fact this happens after I copied the two files `s-ui.db` and `config.json`, and replaced this files with a new created website. The purpose was to backup my s-ui configs and data, reinstall my server and restore the backup. And I found out that is not only about one user, nor about when I put limitations. It's already same for everyone.
I don't know what to do, how to fix this issue without losing my data.
And also the following screenshot is of: when I click on Traffic Chart of any user.
 
![image](https://github.com/user-attachments/assets/21a41408-6300-417d-b3da-6e0bab2b9b05)

Thank you about the subscription link, I noticed it's not a bug. However I found out that some apps are not supporting user info (usage) in sub link. That's why they can't import it.

And I'm happy that you're releasing a new update soon.

A question: do you plan to add a clash meta subscription link? And also based on your knowledge and experience, which inbound type is now working the best for Iranian users? do you recommend a Iranian server tunnel? or is any of them working at its best without?

Thanks.

**Comment by alireza0** [comment]
If your move the database during a huge amount of changes, it is normal that you may have some problem in fetching correct data. In storing traffic, panell will use transactions. Therefore you should stop s-ui first and then move the files. And also make sure that transaction file is not exist or already moved to the new server.

Backup instruction in the future will control all these reqirements.

Clash meta subscription link is in my plans, but with lower priority. I need free time to work on all requested features.

I have no idea about which tunnels and configurations could works fine. You should find these kind of information in other forums or groups from people who are actively working and testing possible scenarios.
