### ISSUE TITLE
How to Force Renew Cloudflare SSL

### ISSUE THREAD

**Issue by shofotolavski** [alireza0/s-ui#271]
26. SSL Certificate Management
 27. Cloudflare SSL Certificate

How to Force Renew Cloudflare SSL Certificate

 27. Cloudflare SSL Certificate
 
There is no forced update option in 27. If I make 27 first and then 26, is it impossible to make 27 again?

**Comment by alireza0** [comment]
There is no reason to use force renew and also no difference.
If you want you can use advanced commands with your own risk and knowledge, you can find the command here:
```bash
~/.acme.sh/acme.sh
```

In case of using CF as your main certificate manager, it is not possible to use 2nd one automatic.
It is better to manage it by your own command sets.
