### ISSUE TITLE
Intermittent WARP Connectivity

### ISSUE THREAD

**Issue by chav0sh** [alireza0/s-ui#272]
**Describe the bug**
Running V2ray panel (3x-ui: Sanaei) on a Hetzner server (Germany). After enabling WARP and using it for some sites, those sites become inaccessible after a while. Other outbounds and directions work fine, but the ones with WARP stop working. To temporarily fix the issue, I have to run the command x-ui restart or restart the x-ray on the panel. This needs to be done 4 to 5 times a day.

I have tried using DigitalOcean servers, changing WARP to WARP+, and uninstalling and reinstalling WARP, but none of these approaches worked.

Details about my WARP outbound:

- Protocol: WireGuard
- Domain Strategy: ForceIP
- MTU: 1420
- Public Key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=

versions:
3x-ui: 2.3.12
xray: 1.8.23

**Comment by alireza0** [comment]
Wrong repo!
