### ISSUE TITLE
TLS settings not effected on Client Side

### ISSUE THREAD

**Issue by DeadSecure** [alireza0/s-ui#273]
درود علیرضا عزیز
در ساخت کانفیگ VLESS درصورتیکه در قسمت Client Side گزینه Enable TLS رو برای یک دامین فعال کنیم، بهش مقدار SNI هم بدیم، سمت کاربر اعمال نمیشه و داخل ساب جیسون عملا تاثیری نداره
بصورت کلی برای این اینباند TLS غیرفعال هست و صرفا برای یک دامین میخوام فعال باشه، جهت عبور از CDN با پورت 443

![image](https://github.com/user-attachments/assets/31bede66-47ea-4bd8-ac10-86a943489531)

![image](https://github.com/user-attachments/assets/8b9f4b19-14f4-49a9-af43-762de23a1a16)

![image](https://github.com/user-attachments/assets/d68bf072-566b-4734-ada9-d94d25ad8f6a)

**Comment by alireza0** [comment]
Thank you for your report.
It is now fixed and will be available in next release
