### ISSUE TITLE
مشکل در ساخت tuic 

### ISSUE THREAD

**Issue by artankohan** [alireza0/s-ui#275]
سلام وقت بخیر. من کانفیگ tuic که میسازم پینگ نمیده. 
البته هر کانفیگی که میسازم پینگ نمیده. 
سرتیفیکیت هم گرفتم ممنون میشم کمک کنید
edit :
وقتی که توی کلاینت ویندزو به جای ادرس ای پی سرور رو زدم وصل شد. مشکل از کجا میتونه باشه؟
![image](https://github.com/user-attachments/assets/c16ef731-440d-4a13-9442-1dc383007f3b)

**Comment by artankohan** [comment]
ممنون بابت کمکت. پورت ها بازه و ALPN هم روی H3 ست کردم جواب نداد. وقتی توی کلاینت به جای ادرس، ای پی سرور رو وارد میکنم حل میشه.

**Comment by DeadSecure** [comment]
@artankohan 
از تب Client Side اون تغییراتی که لازم هست رو اعمال کنید اوکی میشه

**Comment by alireza0** [comment]
درود بر شما
وقتی به جای آدرس، IP رو زدید و حل شد مشکل از تنظیمات دامنه شماست.
