### ISSUE TITLE
TLS Hello download interruption 

### ISSUE THREAD

**Issue by mehradraissi** [alireza0/s-ui#279]
علیرضا جان ممنون از پنل بی نظیرت. 

https://youtube.com/shorts/qoYhNxokQKk?feature=share

از پرتکل VLESS WEBSOCKET TLS استفاده می کنم روی  فیبر نوری مخابرات  یه سوال داشتم 
 تو این ویدیو همونطوری که مشخصه تو حدود سرعت ۱۵۰-۱۸۰ فکر می کنم TLS چک میکنه هی و بعد هم این پروسه ادامه داره یه سکته هایی تو کانکشن میندازه این قابل حل هست ؟  بعد فقط رو دانلود این بازی رو در میاره تو آپلود تو ویدیو هم معموله اصلا کاری نداره اپراتور انگار. روی Reality GRPC  این  مشکل کمتره ولی اون سرعت خوبی نداره.  چه پرتکل دیگه ای پیشنهاد می کنید ؟
ممنون میشم راهنماییم کنید.

**Comment by mehradraissi** [comment]
سلام محدد نه مشکل از پرتکل و کانفیگ نبود مشکل از  نرم افزار Shadowrocket تو iOS هست یا اینکه من iOS 18 beta نصب کردم این مشکل با لن نیست فقط توی وای فای این جوری میشه روی LAN همه چی اوکی هست.

**Comment by alireza0** [comment]
درود بر شما
اگر منظورتون وقفه داخل تست هست، دلیلش روش سرویس تست سرعته و ربطی به چیز دیگه ای نداره.
من مشکلی توی این ویدئو ندیدم
