### ISSUE TITLE
تغییر پورت

### ISSUE THREAD

**Issue by holms2012** [alireza0/s-ui#28]
با سلام و تشکر.
هنگام نصب چطور پورت رو عوض کنیم؟
برای سرورهای NAT

**Comment by MasoudRahmani** [comment]
در حال حاضر قابلیت تغییر تنظیمات از طریق cli وجود نداره چه در نصب چه بعد، فعلا تنها از طریق پنل وب یا تغییر مستقیم دیتابیس ممکن هست.
