### ISSUE TITLE
Single IP address (and geoip) in routing

### ISSUE THREAD

**Issue by radiumatic** [alireza0/s-ui#281]
**Is your feature request related to a problem? Please describe.**

A field to allow specifying single IP addresses (without CIDR) and geoip headers in routing.

**Describe the solution you'd like**

Another field in the "Domain/IP" cateogory.

**Describe alternatives you've considered**

Using rule-sets. Unfortunately enough there's no source for ruleset files. ~~I wouldn't be surprised if the sing-box dev backtracks to geo* and `.dat` and abandons rulesets.~~ Maybe not, but it doesn't hurt to have geo* files. 

**Additional context**

**Comment by alireza0** [comment]
Everything you need to configure it is available. You can set single IP in CIDR without problem (or using IPv4:/32 or IPv6/128).
