### ISSUE TITLE
https 

### ISSUE THREAD

**Issue by elbokarin** [alireza0/s-ui#282]
سلام و وقت بخیر
 پیشاپیش اگه سوالات مبتدیانه هستش عذر میخوام بنده تازه وارد هستم تو این حوزه :)
سوال اول اینکه کانفیگهایی که میسازم روی ویندوز و V2rayN به خوبی کار میکنن اما همون کانفیگها روی گوشی و اپ نکوباکس که استفاده میشه یوتوب رو باز نمیکنه و وب پیج های مختلف رو که باز میکنی خطای DNS ی میده 
سوال دوم : دامنه و سرتیفیکیت برای اینکه بتونم پنل رو روی https بیارم بالا تنظیم کردم و اوکی هم بود ینی https بالا اومد 
ولی بعدش هر چی کانفیگ میسازم کار نمیکنه!
 اگه داخل s-ui یا cloudflare کانفیگ خاصی باید انجام بدم ممنون میشم راهنمایی کنید

**Comment by Kiarash-esl** [comment]
> سلام و وقت بخیر پیشاپیش اگه سوالات مبتدیانه هستش عذر میخوام بنده تازه وارد هستم تو این حوزه :) سوال اول اینکه کانفیگهایی که میسازم روی ویندوز و V2rayN به خوبی کار میکنن اما همون کانفیگها روی گوشی و اپ نکوباکس که استفاده میشه یوتوب رو باز نمیکنه و وب پیج های مختلف رو که باز میکنی خطای DNS ی میده سوال دوم : دامنه و سرتیفیکیت برای اینکه بتونم پنل رو روی https بیارم بالا تنظیم کردم و اوکی هم بود ینی https بالا اومد ولی بعدش هر چی کانفیگ میسازم کار نمیکنه! اگه داخل s-ui یا cloudflare کانفیگ خاصی باید انجام بدم ممنون میشم راهنمایی کنید

از داخل s-ui  بخش settinigs=>json subscriptin   دی  ان اس ست کنید ترجیحا dns  گوگل یا کلودفلر احتمالا مشکل اول تون حل میشه

**Comment by alireza0** [comment]
درود بر شما
در مورد سوال اول باید از کامیونیتی های مربوط به تنظیمات و کلاینت ها کمک بگیرید.
درمورد سوال دوم باید لاگ ها رو چک کنید. این دو موضوع به همدیگه مربوط نیستند.
