### ISSUE TITLE
Batch Add

### ISSUE THREAD

**Issue by mysoft999** [alireza0/s-ui#285]
Hello, is there a plan to generate multiple Vmesses at once? Also, if the socks information is the same except for the IP, can I add an IP segment all at once in outbound? thank you

**Comment by alireza0** [comment]
Hello,
There is no plan for batch creating Inbound/Outbound.
But current plan for batch client add is in progress.

**Comment by alireza0** [comment]
Batch client is now added. Please wait for next release
