### ISSUE TITLE
مشکل اضافه کردن ?ed=2048 در path

### ISSUE THREAD

**Issue by MoSi8160** [alireza0/s-ui#286]
سلام . خسته نباشید و ممنونم از زحماتتون که این پنل خوب رو ساختید
این کانفیگ من هست:
![image](https://github.com/user-attachments/assets/64f611ac-a33c-43ac-991f-a994e41826b1)

اما وقتی من در انتهای path ؟ed=2048 قرار میدم و تست میکنم کانفیگ ها دیگه پینگ نمیدن 
البته وقتی به صورت دستی کانفیگ رو در v2rayng ویرایش میکنم و ?ed=2048 رو در آخر قرار میدم مشکلی نداره و کار میکنه

**Comment by alireza0** [comment]
درود بر شما
تنظیمی که میخواید انجام بدید مخصوص هسته xray هست و روش تنظیمش توی سینگ باکس متفاوته.

**Comment by MoSi8160** [comment]
@alireza0 
در واقع وقتی از ?ed=80 آخر path استفاده بشه اینستاگرام خیلی روون تر اجرا میکنه روی ایرانسل و خودم شخصا این رو تست کردم.

روی همین پنل هم با این روش من استفاده کردم و اگر شما بتونید کاری کنید که مسیر کوتاه تر بشه ممنونتون میشم:
1. مقدار رو آخر path اضافه کنید و save بزنید 
![image](https://github.com/user-attachments/assets/b18db15e-276c-49cb-9f5b-78952969d919)

2. از طریق هر ادیتوری که راحت هستید این فایل رو ادیت کنید و اون مقداری که اضافه کردید رو در اینباند پاک کنید:
/usr/local/s-ui/bin/config.json
![image](https://github.com/user-attachments/assets/54d657b2-761b-48e8-a2a6-4fce0c4d22a0)

3. حالا داخل سرور "s-ui" رو بنویسید و هسته سینگ باکس رو ریست کنید
4. حالا هر کس آپدیت سابسکریپشن بزنه کانفیگ رو با ed=80 دریافت میکنه

**Comment by alireza0** [comment]
درسته ولی این تنظیم توی هسته سینگ باکس توی بخش max early data انجام میشه.
کلاینت ها اگر هسته xray داشته باشند متوجه میشن، و اگر سینگباکس باشه باید به شکل خودش انجام بشه
