### ISSUE TITLE
Crash after heavy use

### ISSUE THREAD

**Issue by ali6043** [alireza0/s-ui#289]
سلام وقت بخیر.کانفیگ هایی که روی‌پنل میسازم بعد چند ساعت استفاده سنگین ارور eof میدن و تا s-ui restart انجام ندم اوکی نمیشن.کانفیک vless grpc reality

**Comment by alireza0** [comment]
درود بر شما
مشکل ریستارت در نسخه بعدی حل میشه.

**Comment by ali6043** [comment]
![Screenshot_20240904_221017_Termius](https://github.com/user-attachments/assets/ea4e6e3f-be01-4033-84d5-a45b004932ee)
این ارور تو لاگ برنامه میاد.

**Comment by ali6043** [comment]
روی ابونتو ۲۴ این مشکل پیش میاد ولی رو ۲۲ اوکیه
