### ISSUE TITLE
Sing-Box Info Running no

### ISSUE THREAD

**Issue by oneoneishere** [alireza0/s-ui#29]
سلام وقت شما بخیر
اول از همه ممنون بابت این اقدام بسیار زیبا و ارزشمندتون، به شدت جای خالی همچین چیزی احساس میشد
ایده و طرح اولیه هم بسیار زیباست مشخصه در ادامه امکانات و طرح های بسیار خوبی در انتظارمون هست

من یه چند روزی هست با این پنل ور میرم هنوز نتونستم به کانفیگهاش وصل بشم، الان چک کردم تو بخش تایلز میگه سینگ باکس در حال اجرا نیست
این به دلیل اینه که کسی بهش وصل نیست یا مشکلی در اجرای خود هسته وجود داره؟
Sing-Box Info
Running
no
اینجوی نوشته با رنگ قرمز

**Comment by MasoudRahmani** [comment]
درود
وقتی دستور بررسی وضعیت سرویس سینگ باکس رو در سرور میزنی چی میده؟

`systemctl status sing-box.service`

اگر اجرا نیست ببین دستی اجرا میشه، یا یکبار ریستارت کن ببین مشکلش حل میشه
```
systemctl start sing-box.service

systemctl restart sing-box.service
```

حالت عادی اینه
![image](https://github.com/alireza0/s-ui/assets/5321268/d3e2894e-a74f-41cf-a922-a6a925f5cc3c)

**Comment by oneoneishere** [comment]
![Screenshot 2024-02-15 153355](https://github.com/alireza0/s-ui/assets/145899845/3bb2f688-6a37-43f5-a8f3-0c0dace22425)
نه من منظورم این قسمته
میخوام ببینم وضعیت نرمالش اینه یا مشکلی روی سرور من وجود داره

**Comment by MasoudRahmani** [comment]
متوجه هستم، نه وضعیت درست اون این شکلیه
![image](https://github.com/alireza0/s-ui/assets/5321268/eebabfac-60cd-4f40-a756-ace68e353b5b)

برای همین میگم نرم افزار اصلیش رو چک کنی ببینی اصلا اجرا شده

**Comment by 0x05E1** [comment]
این مشکل به خاطر وجود نداشتن singbox در نسخه داکر پیش میاد
#34 باید این مشکل رو حل کنه

**Comment by alireza0** [comment]
@0x05E1 
شما میتونید موقت از تنظیم داکر استفاده کنید.
استفاده از دو نرم افزار در یک داکر اصلا توصیه نمیشه.
برنامه من برای داکر، جدا کردن دو کانتینر و ارتباط با شبکه داکر هست.
قبلا توی [پروژه رها](https://github.com/Raha-Project/Raha/blob/main/dockerMysql/docker-compose.yaml) استفاده کردم.

در حال حاضر یه سری مشکلات هسته اجازه این کار رو به من نمیده. کم کم بهش میرسم

**Comment by bloodh73** [comment]
> ![Screenshot 2024-02-15 153355](https://private-user-images.githubusercontent.com/145899845/305065756-3bb2f688-6a37-43f5-a8f3-0c0dace22425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTA0OTEsIm5iZiI6MTcwODYxMDE5MSwicGF0aCI6Ii8xNDU4OTk4NDUvMzA1MDY1NzU2LTNiYjJmNjg4LTZhMzctNDNmNS1hOGYzLTBjMGRhY2UyMjQyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMzU2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzVhYjE1ODc3YjMwZmVmNjE1Y2ZkYzIxMmU0Mzk4NThiMjVhOTQyZTMyNzk1Y2UzNzg3MmZhMzM4NjIwZWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nmkw8ebs8aOwWuh3CUAx-iacrC2K8_McbMBRLsDdJCQ) نه من منظورم این قسمته میخوام ببینم وضعیت نرمالش اینه یا مشکلی روی سرور من وجود داره

سلام داداش منم این مشکل رو دارم 
هسته توی سرور روشن میزنه ولی توی سرور خاموشه

**Comment by oneoneishere** [comment]
> این مشکل به خاطر وجود نداشتن singbox در نسخه داکر پیش میاد
> #34 باید این مشکل رو حل کنه

نه مشکل از جای دیگه بود پیدا کردم، یه سری مورد توی پنل هست که به خاطر اونا بود با چند تست مختلف تونستم پیدا کنم ایراد از کجا ناشی میشه

**Comment by mrn40** [comment]
داداش این مشکل رو چجوری حل کردی ؟؟

**Comment by oneoneishere** [comment]
> داداش این مشکل رو چجوری حل کردی ؟؟

بعضی آپشنها رو فعال میکنی هسته کلا از کار میفته، از جمله UDP option ، من اوایل برای تست اینو فعال میکردم بعد متوجه شدم خاموشش کردم درست شد
ولی فقط این نیست، با موارد دیگری هم میتونه اتفاق بیفته، مثلا یه اشتباهی توی کانفیگ داشته باشی ممکنه بازم هسته از کار بیفته، لاگهاشو بررسی کنی مشخص میشه.
