### ISSUE TITLE
بستن یک سایت خاص روی پنل

### ISSUE THREAD

**Issue by mrmasiha0** [alireza0/s-ui#290]
سلام وعرض خسته نباشید
اگر بخوام یک سایت خاص رو روی پنل برای تمام کاربران بلاک کنم چه کاری باید انجام بدم؟ ممنون میشم راهنمایی کنید.

**Comment by alireza0** [comment]
![image](https://github.com/user-attachments/assets/13928d3a-7145-4fa6-be4d-52c0e86a8280)
