### ISSUE TITLE
 entrypoint.sh is not recognized

### ISSUE THREAD

**Issue by jmyh88** [alireza0/s-ui#292]
entrypoint.sh is not recognized, download yml, run docker-composeup-d and prompt Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec : "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown, manual download and upload to the s-ui directory, the same prompt

**Comment by admiralhr99** [comment]
Fix is here
https://github.com/alireza0/s-ui/pull/295

**Comment by jmyh88** [comment]
Thank you very much, I will test it when I have time.

**Comment by PR2403** [comment]
> Fix is here #295

@admiralhr99 
Hi,I used your file but still the same problem

**Comment by admiralhr99** [comment]
1. `git clone https://github.com/alireza0/s-ui.git`
2. `cd s-ui`
3. Make changes on docker-compose.yml
4. `docker build -t alireza7/s-ui .`
5. `docker compose up -d`


If you got this error `Error response from daemon: invalid mount config for type "volume": invalid mount path: 's-ui' mount path must be absolute`

Do this:

1. `docker compose down -v`
2. `docker compose up -d`

This should solve your problem.

**Comment by PR2403** [comment]
all worked, thanks
so, alireza0 didn't update docker img right?
