### ISSUE TITLE
Question about API integration 

### ISSUE THREAD

**Issue by setarehirani** [alireza0/s-ui#294]
Hello Alireza,
Thanks for the panel. I'd like to know when the next update is going to be released? Also I have a question.
I know the API is a feature to be added in future. However I couldn't wait and I already made an API endpoint,
connected my app to the API, so I can view/update/delete the s-ui.db already. But as the s-ui updates the database each time, and by clicking on "Save", it do the changes to the sing-box config, and my cahnges to the API wouldn't work without having a save button on my app. I'd like to know what you'd suggest to solve this issue, is there a way to make the "save" automatically each time a request is sent to database?
I'd only create "clients" from my app, I'd update expiry and volume, I'll enable/disable as well. I also want to see online users.

Thank you in advance.

**Comment by roozbehalamdari** [comment]
درود علیرضا جان ، ما هم همچنان منتظر ورژن جدیدیم حدودا چند روز دیگه بیرون میاد ؟ 🥺
و اینکه تغییرات گرافیکی پنل رو امکانش هست مثل X-Ui بشه ؟ مخصوصا قسمت اینباندها و یوزر ها ؟ ( اونجا خیلی عالی هست اگر این پنل هم مثل اون بشه خیلی عالی میشه )

**Comment by alireza0** [comment]
Hello @setarehirani ,

API in s-ui is not based on DB change. It is using change management calls. Each change in users will affect the DB and config files in same time. By changing database you will only add a miss configuration to the panel.

If you find how to send changes and manage all parts which are supposed to be changed, then you can call current API simply.
Update clinets volume and expiry is possible, because it is only a change in database.
For online users/inbounds/outbounds you can call `load` api. Please check panel calls.

@roozbehalamdari
درود بر شما
من فقط میتونم وقت آزادم رو بذارم و نمیتونم زمان مشخصی اعلام کنم.
برای تغییرات گرافیکی اول به تغییرات پایه ای احتیاج داریم و بعد از اون میشه روی گرافیکش کار کرد.
البته برای اینکار باید حتما دوستان دیگه ای هم کمک بکنند که در حال حاضر کسی نیست و دست تنهام

**Comment by wepeenet** [comment]
> Hello @setarehirani ,
> 
> API in s-ui is not based on DB change. It is using change management calls. Each change in users will affect the DB and config files in same time. By changing database you will only add a miss configuration to the panel.
> 
> If you find how to send changes and manage all parts which are supposed to be changed, then you can call current API simply. Update clinets volume and expiry is possible, because it is only a change in database. For online users/inbounds/outbounds you can call `load` api. Please check panel calls.
> 
> @roozbehalamdari درود بر شما من فقط میتونم وقت آزادم رو بذارم و نمیتونم زمان مشخصی اعلام کنم. برای تغییرات گرافیکی اول به تغییرات پایه ای احتیاج داریم و بعد از اون میشه روی گرافیکش کار کرد. البته برای اینکار باید حتما دوستان دیگه ای هم کمک بکنند که در حال حاضر کسی نیست و دست تنهام

Thanks a lot for replying.
That's a good news that I can update clients volume and expiry, what about up and down and desc?
Each change in users will affect the DB and config files in same time, is there a way for making such connection with Express API? As you're working alone on this, maybe I can be a help for database?

**Comment by setarehirani** [comment]
> Hello @setarehirani ,
> 
> API in s-ui is not based on DB change. It is using change management calls. Each change in users will affect the DB and config files in same time. By changing database you will only add a miss configuration to the panel.
> 
> If you find how to send changes and manage all parts which are supposed to be changed, then you can call current API simply. Update clinets volume and expiry is possible, because it is only a change in database. For online users/inbounds/outbounds you can call `load` api. Please check panel calls.
> 
> @roozbehalamdari درود بر شما من فقط میتونم وقت آزادم رو بذارم و نمیتونم زمان مشخصی اعلام کنم. برای تغییرات گرافیکی اول به تغییرات پایه ای احتیاج داریم و بعد از اون میشه روی گرافیکش کار کرد. البته برای اینکار باید حتما دوستان دیگه ای هم کمک بکنند که در حال حاضر کسی نیست و دست تنهام

Thanks a lot for replying.
That's a good news that I can update clients volume and expiry, what about up and down and desc?
Each change in users will affect the DB and config files in same time, is there a way for making such connection with Express API? As you're working alone on this, maybe I can be a help for database?

**Comment by alireza0** [comment]
For sure, contributions are welcome and would be appreciated.
In my plan, API will be easy solution and completely diffrent from the way that panel uses.

**Comment by setarehirani** [comment]
Thank you !
I just need to know how to send the /load request. I see that I can send post request with a data like this: mypaneladdress.com:443/app/load
but how the data structure should be ? if I'm going to post it through postman for example.

**Comment by alireza0** [comment]
It is GET method and you may send `lu` parameter using query string.
```url
curl -X GET http[s]://domain:port/app/load?lu=<unix time like 1729527651>
```
The `lu` is about last update in unix time. It is optional and will change the respose:
1. If lu> last change in database => Only return the online users
```json
{
  "success": true,
  "msg": "",
  "obj": {
    "onlines": {...}
  }
}
```
3. if lu<= laste change in database (or empty) => Will return all the configuration needed in UI
```json
{
  "success": true,
  "msg": "",
  "obj": {
    "clients": [...],  // All clients data
    "config": {
      "log": {
        "level": "warn",
        "disabled": true
      },
      "dns": {
        "servers": []
      },
      "ntp": null,
      "inbounds": [...],  // All inbounds data
      "outbounds": [...],  // All outbounds data
      "route": {
        "rules": [...],   // All ruting rules
        "rule_set": [...] // All routing rule_sets
      },
      "experimental": {
        "v2ray_api": {
          "listen": "127.0.0.1:1080",
          "stats": {
            "enabled": true,
            "inbounds": [...],  // All inbound tags which are supposed to check for stats
            "outbounds": [...],  // All outbound tags which are supposed to check for stats
            "users": [...]  // All clieny names which are supposed to check for stats
          }
        }
      }
    },
    "inData": [...],  // All extra inbound's data
    "onlines": {...}, // Online users
    "subURI": "",  // subscription URL
    "tls": [...] // All TLS data
  }
}
```

**Comment by setarehirani** [comment]
Thanks! that's amazing,
and how to send request and update? for example adding a client?

**Comment by alireza0** [comment]
Requests between frontend and backend in panel is complex enough to avoid a developer for preparing a code for change.
My plan for api is simplify all these actions and handle some frontend processes in backend.
For example, you need to check if client is depleted or not. If it is depleted, then add it to related inbounds as well. If not, only client table will be updated.

Current backend works as change manager. That means all changes will be detected in frontend and infom backend what change is needed.

Changes will be called by `POST` to `/app/save` with following information:
```json
{
  "config": [...],  // changes in config.json including inbound, outbound, dns, ...
  "clients": [...],  // changes in client table
  "tls": [...],  // changes in tls table
  "inData": [...]  // changes in inbound data table
}
```
Each change has standard format.
For example for editing client ( in clients array ):
```json
    {
      "key": "clients",  // which object is trying to
      "action": "edit",  // Action
      "obj": {}  // Final edited client data
    }
```
For adding new inbound in config array:
```json
  {
    "key": "inbounds", // each part of config.json
    "action": "new",  // Action
    "index": 5,  // index of object
    "obj": {  // object details
      "type": "direct",
      "tag": "direct-37015",
      "listen": "::",
      "listen_port": 37015
    }
  }
```

P.S. You can find the real data in your inspect mode of your browser during working with panel. 
P.S. This usage will transfer a huge amount of data right now and may change in the future to make it more clean.

**Comment by setarehirani** [comment]
Hello @alireza0 , thanks for your great explanation.
However trying to do a send request to http://*****/app/api/save 
with following body, in RAW and Json format:

```{
  "config": [
    {
      "key": "inbounds",
      "action": "edit",
      "index": 0,
      "obj": {
        "type": "vless",
        "users": [
          {
            "name": "Everyone",
            "uuid": "9af7536f-e899-44eb-0909-faf6d84e07ac"
          },
          {
            "name": "gvMTa2eF",
            "uuid": "866d9ee1-039c-49a0-09090-9111fb5bdf09"
          }
        ],
        "tls": {},
        "multiplex": {},
        "transport": {},
        "tag": "vless-38924",
        "listen": "::",
        "listen_port": 5146
      }
    },
    {
      "key": "experimental",
      "action": "set",
      "obj": {
        "v2ray_api": {
          "listen": "127.0.0.1:1080",
          "stats": {
            "enabled": true,
            "inbounds": [
              "hysteria2-40489",
              "vless-38924",
              "hysteria-5146",
              "trojan-16755",
              "shadowsocks-44807"
            ],
            "outbounds": ["direct"],
            "users": ["Everyone", "gvMTa2eF"]
          }
        }
      }
    }
  ],
  "clients": [
    {
      "key": "clients",
      "action": "new",
      "obj": {
        "enable": true,
        "name": "gvMTa2eF",
        "config": {
          "mixed": {
            "username": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          },
          "socks": {
            "username": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          },
          "http": {
            "username": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          },
          "shadowsocks": {
            "name": "gvMTa2eF",
            "password": "v6vIB1+AVxlg9r8nnI8vSTCgV0avk9Emg1VwpiUMmdk="
          },
          "shadowtls": {
            "name": "gvMTa2eF",
            "password": "v6vIB1+AVxlg9r8nnI8vSTCgV0avk9Emg1VwpiUMmdk="
          },
          "vmess": {
            "name": "gvMTa2eF",
            "uuid": "866d9ee1-039c-49a0-0909-9111fb5bdf09",
            "alterId": 0
          },
          "vless": {
            "name": "gvMTa2eF",
            "uuid": "866d9ee1-039c-49a0-090909-9111fb5bdf09"
          },
          "trojan": {
            "name": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          },
          "naive": {
            "username": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          },
          "hysteria": {
            "name": "gvMTa2eF",
            "auth_str": "FbUP7PKnKE"
          },
          "tuic": {
            "name": "gvMTa2eF",
            "uuid": "866d9ee1-039c-49a0-090909-9111fb5bdf09",
            "password": "FbUP7PKnKE"
          },
          "hysteria2": {
            "name": "gvMTa2eF",
            "password": "FbUP7PKnKE"
          }
        },
        "inbounds": ["vless-******"],
        "links": [
          {
            "type": "local",
            "remark": "vless-******",
            "uri": "vless://******"
          }
        ],
        "volume": 53687091200,
        "expiry": 1730898600,
        "up": 0,
        "down": 0,
        "desc": "uhuhuh"
      }
    }
  ],
  "tls": [],
  "inData": []
}```


I receive this error:

```{
    "success": false,
    "msg": "savejson: cannot unmarshal array into Go value of type string",
    "obj": null
}```

what's wrong with my json?

**Comment by alireza0** [comment]
You should send the data with `application/x-www-form-urlencoded; charset=UTF-8` format.

**Comment by setarehirani** [comment]
I'm sorry but I need to say that didn't work...

**Comment by alireza0** [comment]
I can not check what is your problem. I am not behind your PC.
For now, just simply check the UI behaviour for each api call and try to find it.

As I already mentioned, I am going to add a simple API service. It is better to wait for that.
My plan is to change current UI interactions in the future to standard API.
Therefore your deployments won't work in next versions.

**Comment by setarehirani** [comment]
Thank you, yet that's amazing to know it would be in the next updates, I thought I could be a help and speed up the procedure; However it makes me feel good to wait for something amazing created by you as a great developer. May I ask when it would be ready approximately ~ ?
