### ISSUE TITLE
Is there the dns rule feature in s-ui?

### ISSUE THREAD

**Issue by PR2403** [alireza0/s-ui#296]
Hi
I can't find where to config it, but I find json sub have dns rule
If this feature is unavailable, I will manually configure it.
and by the way, Could you please add a switch to the inbound/outbund/dns server nodes so that they can be temporarily closed?

**Comment by alireza0** [comment]
Hello,
DNS rules are not complete for the server. But you can define dns servers in Basic page.

These configurations are not going to be stored in database. They use sing-box configuration directly.
Therefore disabling these parts has no meaning yet. You can remove inbound from client config. Not using outbound in rules. And use Final dns for using only one dns server.

**Comment by lonelylose** [comment]
> Hello, DNS rules are not complete for the server. But you can define dns servers in Basic page.
> 
> These configurations are not going to be stored in database. They use sing-box configuration directly. Therefore disabling these parts has no meaning yet. You can remove inbound from client config. Not using outbound in rules. And use Final dns for using only one dns server.

Hello, I tried and found that DNS rules work normally on the server side.
"rules": [
      {
        "server": "local",
        "rule_set": [
          "geosite-cn"
        ]
      },
      {
        "server": "block",
        "rule_set": [
          "geosite-category-ads-all"
        ]
      }
    ],
    "final": "proxy",
    "strategy": "prefer_ipv4"
  },

INFO[0338] [3081326404 0ms] inbound/shadowsocks[shadowsocks-fl]: [3IejJ5zC] inbound connection to www.ipip.net:443
DEBUG[0338] [3081326404 0ms] router: sniffed protocol: tls, domain: www.ipip.net
DEBUG[0338] [3081326404 1ms] dns: lookup domain www.ipip.net
DEBUG[0338] [3081326404 1ms] dns: match[0] rule_set=geosite-cn.srs => local

INFO[0338] [3081326404 80ms] dns: lookup succeed for www.ipip.net: 123.129.226.36 123.129.226.26
DEBUG[0338] [3081326404 80ms] dns: resolved [123.129.226.36 123.129.226.26]
