### ISSUE TITLE
نمایش اطلاعات کاربری در برنامه سینگ باکس

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#298]
درود علیرضا جان خوبی ؟ 
ببخشید یه سوال داشتم چطوری میشه توی برنامه Sing-Box اطلاعات کاربری ( حجم ، زمان و ... ) رو اضافه کرد ؟  ( اصلا امکانش هست ؟ )
 چون واقعا توی برنامه ی به این خوبی جای این مورد خالیه
 بازم سپاس از زحماتی که میکشی

**Comment by alireza0** [comment]
درود بر شما
کاربر رو ویرایش کنید و حجم و زمانش رو تغییر بدید.

**Comment by roozbehalamdari** [comment]
> درود بر شما کاربر رو ویرایش کنید و حجم و زمانش رو تغییر بدید.

علیرضا جان منظور من رو اشتباه متوجه شدید ، منظورم اینه توی اپ مثلا اندروید یا IOS راهی هست که مشخصات حجم یا زمان باقیمانده ی اکانت هر یوزر رو نشون بده ؟ یا اگر باید به تیم برنامه نویس خود اپ بگم چی بگم که روش کار کنن ؟

**Comment by alireza0** [comment]
من پروتکل و یا هدری ندیدم که پشتیبانی بشه. اگر کلاینت پشتیانی بکنه میتونم اضافه کنم.
