### ISSUE TITLE
مشکلات پنل 

### ISSUE THREAD

**Issue by Real-kia** [alireza0/s-ui#3]
با تشکر از زحماتتون
چند مورد که تا اینجا دیدم و به نظرم مشکل حساب میشه

اول موقع نصب 
s-ui usages: 
s-ui              - Enter     Run S-UI

این پیام میاد که با وارد کردن کامند s-ui کامند/سرویس پیدا نمیشه.
و نمیدونم پنل چطور میشه حذف کرد یا اگه مشکلی پیش بیاد که خود پنل بالا نیاد چطور میشه حلش کرد بدون کامند لاین

موردی بعد چند تا اینباند و کلاینت ساختم
که رفرش کردم و برگشتم کلا پاک شده بودن 

و مورد اخر تا اینجا

از توی پنل نمیشه اطلاعات ورود رو عوض کرد !
امکان تغییر پورت هست ولی رمز و پسورد دیفالت رو نمیشه تغییر داد

**Comment by hossein1200github** [comment]
اینباند می سازی باید دکمه save اون گوشه بالا سمت راست بزنی . تا ذخیره شود .

**Comment by Real-kia** [comment]
اوه
درست
برا کلاینت و اینباند ها باید سیو انجام بشه
موردن ندارن

**Comment by alireza0** [comment]
درود بر شما
بله، این نسخه بیشتر حالت تستی داره و یه سری کانسپت ها باید توضیح داده بشه.
نگاه به سیستم کمی متفاوت تر از بقیه پنل هاست.
بخشهایی که باید اضافه بشه کاملا مشخصه و الان فقط حداقل ها رو برای راه اندازی و تست سرویس ها داره.

**Comment by aminamdaba** [comment]
سلام
من سروری که دارم فیلتر نیست ولی برای بالا اومدن پنلم vpn میخواد از 2 3 ساعت پیش و کلا وصل نمیشه؟
چیکار باید بکنم؟

**Comment by Zarei72** [comment]
سلام چطور میشه از پنل sui بکاپ گرفت نام پوشه‌ رو میگین

**Comment by jgargit** [comment]
با سلام و عرض خسته نباشید
من این پنل رو چندین روزه زدم و استفاده میکنم خیلی عالی هست
چون قابلیت های زیادی میتونیم ایجاد کنیم و این خیلی عالی هست
مشکلات اصلی که من دیدم اینه که گزینه های بک اپ و ریستور نداره
این گزینه رو زودتر اپدیت بیارین ممنون میشم
همیشه عالی و نامبر وان هستین
خیلی دوستون دارم
🙏❤️

**Comment by NimaTarlani** [comment]
> سلام چطور میشه از پنل sui بکاپ گرفت نام پوشه‌ رو میگین

https://github.com/NimaTarlani/s-ui-backup

**Comment by raminsh2001** [comment]
درود بر شما اقای علیرضا هر کاری میکنم کانفیگ tuic کار نمیکنه

**Comment by hazeghsa89** [comment]
سلام تو این پنل برای hysteria2 میشه محدودیت تعداد دستگاه گذاشت؟
