### ISSUE TITLE
Command 's-ui' not found after installation

### ISSUE THREAD

**Issue by trongtinh7727** [alireza0/s-ui#30]
After installing s-ui, the command is not recognized in the terminal. When attempting to run s-ui, I receive an error suggesting that the command is not found and a recommendation to install s-tui instead.

Environment
OS: Ubuntu
Version: 20.04 LTS

![image](https://github.com/alireza0/s-ui/assets/72309458/37fcdd0c-ede3-47d0-a1d8-f523235fff07)

**Comment by MasoudRahmani** [comment]
There is no command line feature for sui as of right now.

the only option for calling sui is to run it again and the location of program is in
`/usr/local/s-ui`
