### ISSUE TITLE
راهنمایی برای اجرای پروکسی تلگرام

### ISSUE THREAD

**Issue by 33008252aM2** [alireza0/s-ui#300]
سلام. ظاهرا پنل شما از mtproto پشتیبانی میکنه. میخواسم بپرسم امکانش هس برای راه اندازی باید چیکار کنیم؟ سپاس

**Comment by alireza0** [comment]
درود بر شما
این پروتکل توی ایران سریع شناسایی میشه و باعث فیلتر شدن IP میشه.
توصیه میکنم از راه های دیگه اسنفاده کنید.

**Comment by rezadadashi72rd-glitch** [comment]
سلام چجوری از پروکسی استفاده کنیم
