### ISSUE TITLE
Manual tweak for proxy link parameters

### ISSUE THREAD

**Issue by radiumatic** [alireza0/s-ui#301]
**Is your feature request related to a problem? Please describe.**

Usually proxy configs aren't directly applicable to clients, maybe you want to use the resolved IP of a domain as the server IP, maybe it's all behind a web server, maybe you want to set uTLS etc. 

**Describe the solution you'd like**

A menu that allows changing the parameters used for constructing the link. Either in user or inbound settings, though it would be best if it can be easily duplicated, so inbound settings?

**Describe alternatives you've considered**

Running a simple webserver as the sub server, but it's bothersome.

**Additional context**

**Comment by alireza0** [comment]
In inbound configuration, you can find client side tweak for proxy link.
