### ISSUE TITLE
Client for Mac/iOS?

### ISSUE THREAD

**Issue by JWick90** [alireza0/s-ui#302]
سلام.خسته نباشید
کانفیگای هیستریا۲ داخل اپ streisand کار نمیکنن!
داخل هیدیفای کار میکنه ک اونم دردسر داره tun mode ...
اپ سینگ باکس هم حذف شده از اپ استور
از داخل پنل راهی برای درست کردنش هست یا کلاینت به خصوصی هست ؟
ممنونم

**Comment by misagh72** [comment]
شادوراکت

**Comment by amirtrj75** [comment]
Karing 
هم اپ خوبیه من جدیدا تست گرفتم پایدار هم هست و فری
