### ISSUE TITLE
syslog exited with code 1

### ISSUE THREAD

**Issue by shahrooz1397** [alireza0/s-ui#303]
:~/s-ui# docker compose up
[+] Running 23/23
 ✔ s-ui 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                            6.8s 
   ✔ ec99f8b99825 Pull complete                                                                                                                           3.2s 
   ✔ 984ada7befce Pull complete                                                                                                                           3.4s 
   ✔ bd7c0d15a452 Pull complete                                                                                                                           3.7s 
   ✔ 59b8be92e01f Pull complete                                                                                                                           4.3s 
 ✔ sing-box 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                       6.0s 
   ✔ c6a83fedfae6 Pull complete                                                                                                                           2.2s 
   ✔ bfe26c507390 Pull complete                                                                                                                           2.2s 
   ✔ 682cb5db5fb0 Pull complete                                                                                                                           2.8s 
   ✔ 39342cc599c4 Pull complete                                                                                                                           3.6s 
   ✔ 23a4e8aaea4a Pull complete                                                                                                                           3.6s 
 ✔ syslog 11 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                  4.1s 
   ✔ 2fdfe1cd78c2 Pull complete                                                                                                                           0.8s 
   ✔ 51631cad5a67 Pull complete                                                                                                                           0.8s 
   ✔ bc03ff7bc61a Pull complete                                                                                                                           1.2s 
   ✔ c7ad936bdd12 Pull complete                                                                                                                           1.2s 
   ✔ 0f9163febd6d Pull complete                                                                                                                           1.2s 
   ✔ 76f98260bbb2 Pull complete                                                                                                                           1.3s 
   ✔ 0164f652db31 Pull complete                                                                                                                           1.5s 
   ✔ 9b830923a0f2 Pull complete                                                                                                                           1.6s 
   ✔ d9bc51ea5e92 Pull complete                                                                                                                           1.8s 
   ✔ dc9573124a00 Pull complete                                                                                                                           1.9s 
   ✔ 933f52ce59f4 Pull complete                                                                                                                           2.1s 
[+] Building 0.0s (0/0)                                                                                                                                        
[+] Running 4/4
 ✔ Volume "s-ui_logs"  Created                                                                                                                            0.0s 
 ✔ Container syslog    Created                                                                                                                            0.1s 
 ✔ Container s-ui      Created                                                                                                                            0.1s 
 ✔ Container sing-box  Created                                                                                                                            0.1s 
Attaching to s-ui, sing-box, syslog
syslog    | rsyslog appliance version 2018-06-26 (1530020232) - http://www.syslogappliance.de
syslog    | Copyright (C) 2018 by Rainer Gerhards and Adiscon GmbH - released under ASL 2.0
syslog    | 
syslog    | WARNING: this is an experimental container - do not use in production
syslog    | 
syslog    | Using rsyslog configuration file: /etc/rsyslog.conf
syslog    | ERROR: command not known: sh -c touch /config/container_config
syslog    | 
syslog    | docker run --read-only <container-name> command
syslog    | where command is one of:
syslog    | rsyslog     - run rsyslog (default)
syslog    | help        - display this help message
syslog    | show-work   - list the /work area
syslog    | show-config - display the current container config
syslog    | edit-config - edit container config (with vi editor, press <ESC>ZZ to quit)
syslog    | bash        - start an interactive shell (<CTL>-d terminates)
syslog    | 
syslog    | volumes:
syslog    | /log        - log file store (if used)
syslog    | /work       - rsyslog work files; do not share with multiple instances
syslog    | /config     - configuration files, can be mounted read-only once finalized
syslog    | 
syslog    | listening ports:
syslog    | 514/udp     - syslog (udp)
syslog    | 514/tcp     - syslog (plain tcp)
syslog    | 1601/tcp    - RELP
syslog    | 
syslog exited with code 0
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1
syslog exited with code 1

من رو اوبونتو ۱۸ میخوام با داکر ران کنم خطای بالارو میگیرم و وب سرور بالا نمیاد که وارد پنل شم 
قبلا سنایی هم ران کردم با داکر مشکلی نبود

**Comment by alireza0** [comment]
سلوشن کامل داکر با لاگ هنوز نسخه نشده، لطفا منتر نسخه جدید باشید و یا از نسخه قبلی فایل docker-compose.yml استفاده کنید.
