### ISSUE TITLE
record not found

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#308]
**درود علیرضا جان یه سوال داشتم 
توی لاگ S-UI پنلم مدام این اررور رو دارم ! مشکل از چیه ؟** 

![image](https://github.com/user-attachments/assets/f9fab20a-a1ed-4ccb-9d32-615a38124918)

**Comment by alireza0** [comment]
درود بر شما
اتک دارید و یا کاربرهای قدیمی که پاک کردین به ساب شما درخواست میدن.
