### ISSUE TITLE
all dns request match to proxy-dns

### ISSUE THREAD

**Issue by shminer** [alireza0/s-ui#309]
https://github.com/alireza0/s-ui/blob/54e48c8c760717eb12269f601f39525a857e50d8/frontend/src/components/SubJsonExt.vue#L145

 In fact, we don't have to match the source address for DNS resolution, because we only have one inbound, and letting the rule set and target address resolve is the right choice

**Comment by alireza0** [comment]
It is true. But if you want to use local resolver for all packets, you can disable DNS.
And if you want to use direct DNS based on country rules, just set direct DNS.
