### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by ali622** [alireza0/s-ui#313]
من این مشکل رو دارم هر از چند وقتی اینجوری میشه

**Comment by alireza0** [comment]
من پشت سیستم شما نیستم. لطفا با یک ادمین سیستم مشورت کنید

**Comment by ali622** [comment]
من هر چند ساعت یا هر یکی دو روز این database disk image is malformed اررور رو میگیرم یا میگه نمیتونم save کنم و پشت سرش هم همین ارور میاد که نوشتم ابونتو من 20 هست بنظرتون چرا اینجوری میشه رفتم و id ها رو نگاه کردم دیدم که نامنظم هست id هارو منظم کردم اما فایده ایی نداشت ممنون میشم کمک کنید مرسی
