### ISSUE TITLE
عدم اتصال در آی پی دوم سرور

### ISSUE THREAD

**Issue by delshad1522** [alireza0/s-ui#316]
سلام علیرضا جان خسته نباشی
من برای سرورم آی پی دوم گرفتم
با همین آی پی جدید دوباره 3 حالت TLS -TLS-ECH-TLS-ECH-PQS رو در hysteria2 ایجاد کردم و Inbounds جدید و کاربر جدید برای این آی پی ایجاد کردم .
ولی متاسفانه وصل نمیشه و خطا میده 
برای همچین حالتی که دو آی پی در یک سرور هست باید چکار کرد ؟ آیا جایی رو باید تغییر بدم
ممنون میشم راهنماییم کنید

**Comment by alireza0** [comment]
درود بر شما
برای استفاده از TLS حتما باید دامنه رو توی SNI تعریف کنید، حتی فیک!
