### ISSUE TITLE
مشکل رد نشدن مستقیم ترافیک آی پی های ایران

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#318]
درود علیرضا جان خوبی ؟ 
ببخشید  برای اینکه آی پی ها و اپ های ایرانی ترافیکشون مستقیم رد بشه باید دقیقا چکار کنم ؟ 
چون توی قسمت ساب جیسون هر چی تغییر دادم بازم فرقی نداشت ! 
ممنون میشم بهم بگی کجا ها رو باید تغییر بدم ( توی اکانت توییتر کِوین هم انگار دوستان همین مشکل رو داشتن )

> پروتکول هایی هم که استفاده میکنم هیستریا 2 و توییک هستن ، سرور هم یدونه خارج دارم فقط 

اینم تنظیمات قسمت ساب جیسون در پنل 

![image](https://github.com/user-attachments/assets/92dce4bc-e0de-462b-a72c-c1a09caeff7d)

من حتی برای بلاک کردن تبلیغات هم این تنظیمات رو اعمال کردم ولی تاثیری نداره انگار ! 
اگر جایی اشکالی وجود داره یا نکته ای هست لطفا بهم بگو انجام بدم 
اگر برای تبلیغات یوتیوب هم راهی پیدا کردی لطفا اون رو هم بهم بگی ممنون میشم ، با سپاس فراوان

**Comment by TheyCallMeSecond** [comment]
tick "iran" in "route to direct dns" section

**Comment by roozbehalamdari** [comment]
> tick "iran" in "route to direct dns" section

Hello and thank you for your guidance, dear friend. 🙏
I have another question: 
What should I use for global DNS and Direct DNS?

**Comment by TheyCallMeSecond** [comment]
there is no need to set ruleset for bypassing ir geosite and geoip...for apps just exclude them in client setting

**Comment by roozbehalamdari** [comment]
> there is no need to set ruleset for bypassing ir geosite and geoip...for apps just exclude them in client setting 

@TheyCallMeSecond ممنونم از توضیحات و کمکت رفیق ، یه سوال دیگه هم پرسیدم فکر کنم حواست نبود    🙂 راهنماییم کنی

_به نظرت برای Global DNS و Direct DNS توی ساب جیسون چی استفاده کنم بهتره ؟ و اینکه چیزی که الان ست کردم خوبه ؟ _

**Comment by armanpier** [comment]
من میخوام از سمت سرور ترافیک به ایپی ایران block بشه شبیه چیزی که توی x-ui میتونیم داشته باشیم , چون بعضیا با json وصل نیستن و لینک hy2 استفاده میکنن و چون وارد سایتای ایرانی میشنباعث میشه فیلتر بشم,  من سعی یه outbont برای block  ساختم ولی نمیدونم از rules چطور استفاده کنم تا geoip برای ایران رو block کنم از سمت پنل ممنون میشم کسی راهنمایی کنه

**Comment by roozbehalamdari** [comment]
> من میخوام از سمت سرور ترافیک به ایپی ایران block بشه شبیه چیزی که توی x-ui میتونیم داشته باشیم , چون بعضیا با json وصل نیستن و لینک hy2 استفاده میکنن و چون وارد سایتای ایرانی میشنباعث میشه فیلتر بشم,  من سعی یه outbont برای block  ساختم ولی نمیدونم از rules چطور استفاده کنم تا geoip برای ایران رو block کنم از سمت پنل ممنون میشم کسی راهنمایی کنه

دقیقا منم همین سوال رو دارم 
@alireza0 @TheyCallMeSecond

**Comment by alireza0** [comment]
اگر روشش رو توی سینگ باکس نمیدونید، لطفا عجله نکنید. کم کم این موارد اضافه میشه.
من یه توضیح مختصر میتونم اینجا برای شما بذارم:
۱. مجموعه آدرس های ایران رو اضافه کنید
Iran-Domains:
```
https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ir.srs
```
![image](https://github.com/user-attachments/assets/8e68b131-7fa0-4d60-b41d-0f7083f5ae52)

Iran-IPs:
```
https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/ir.srs
```
![image](https://github.com/user-attachments/assets/8fcca017-8c29-451c-9e4d-d6fe1a8125ae)

۲. قانون جدیدی برای بلاک کردن این آدرس ها اضافه کنید:
قانون جدید رو ایجاد و از دکمه Rule Options گزینه Rulesets رو انتخاب کنید و خروجی رو به تگ block که قبلا در خروجی ها اضافه کردید، تنظیم کنید:
![image](https://github.com/user-attachments/assets/d4cbcc27-9354-4500-8ffc-28c09b94542a)

**Comment by MoSi8160** [comment]
من هم دقیقا همین مشکلی که دوستمون در ابتدای کار داشتن رو دارم
![image](https://github.com/user-attachments/assets/c14d4f8b-61d7-4936-a8d0-32e1dade8223)
متاسفانه آی پی های ایران و سایت های ایران دایرکت نمیشن!

**Comment by roozbehalamdari** [comment]
> اگر روشش رو توی سینگ باکس نمیدونید، لطفا عجله نکنید. کم کم این موارد اضافه میشه. من یه توضیح مختصر میتونم اینجا برای شما بذارم: ۱. مجموعه آدرس های ایران رو اضافه کنید Iran-Domains:
> 
> ```
> https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ir.srs
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/12573084/378203700-8e68b131-7fa0-4d60-b41d-0f7083f5ae52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzIyNjgsIm5iZiI6MTcyOTk3MTk2OCwicGF0aCI6Ii8xMjU3MzA4NC8zNzgyMDM3MDAtOGU2OGIxMzEtN2ZhMC00ZDYwLWI0MWQtMGY3MDgzZjVhZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE5NDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOWEyZDg3MGFhM2JjODFmYjI2YWQyN2MwYjBjMThiMmQwZjNlY2U0MzI4OTMwYmU3MmEzM2Q3NTdhNmIyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UERvNmdivJU1OPOphzWWk-zoIewYP9MA_QOzOAkYQM4)
> 
> Iran-IPs:
> 
> ```
> https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/ir.srs
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/12573084/378203739-8fcca017-8c29-451c-9e4d-d6fe1a8125ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzIyNjgsIm5iZiI6MTcyOTk3MTk2OCwicGF0aCI6Ii8xMjU3MzA4NC8zNzgyMDM3MzktOGZjY2EwMTctOGMyOS00NTFjLTllNGQtZDZmZTFhODEyNWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE5NDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjhlZjQ5NzkyMTEyYzNkYzQzYjcxNjdiZTU5YTFlMjQ3MWY3YzcxMzAyMDdjN2Y0ZTlhM2Q1YzE2N2NiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jht0BalrlFRP0lskbT-Umo8B1Hizno2zIo3pJNN4jT4)
> 
> ۲. قانون جدیدی برای بلاک کردن این آدرس ها اضافه کنید: قانون جدید رو ایجاد و از دکمه Rule Options گزینه Rulesets رو انتخاب کنید و خروجی رو به تگ block که قبلا در خروجی ها اضافه کردید، تنظیم کنید: ![image](https://private-user-images.githubusercontent.com/12573084/378203992-d4cbcc27-9354-4500-8ffc-28c09b94542a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NzIyNjgsIm5iZiI6MTcyOTk3MTk2OCwicGF0aCI6Ii8xMjU3MzA4NC8zNzgyMDM5OTItZDRjYmNjMjctOTM1NC00NTAwLThmZmMtMjhjMDliOTQ1NDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE5NDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ODUxZjRmYTAzMjVhMTg3NDBmZGRiNmJkOGIxYzFhNjA3YzU0NTU4MmNjOGM1ZWI4NGU1NjMzYzRkMWM4NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wFWca8_as4cLYhGCqKuy3utZdAI7Wh-TYreLYnEwZn0)

سپاس از توضیحات بسیار خوبت علیرضا جان ، من انجام دادم ولی این روش برای بلاک کردن سایت ها و آی پی های ایران هست ، من دنبال راهی واسه دایرکت کردن هستم ممنون میشم اگر اونم بهمون بگی دمت گرم

**Comment by TheyCallMeSecond** [comment]
![image](https://github.com/user-attachments/assets/1d752000-e9be-4fcf-9569-4c7e3ae28c54)
با همین تنظیمات آیپی و دامنه های ایران دایرکت میشن اگه از JSON Subscription استفاده کنین

**Comment by roozbehalamdari** [comment]
> ![image](https://private-user-images.githubusercontent.com/73380906/380484144-1d752000-e9be-4fcf-9569-4c7e3ae28c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjQzNzQsIm5iZiI6MTczMDA2NDA3NCwicGF0aCI6Ii83MzM4MDkwNi8zODA0ODQxNDQtMWQ3NTIwMDAtZTliZS00ZmNmLTk1NjktNGM3ZTNhZTI4YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDJlMDc2M2YzOTIyNGIwOWJhMmFiYjQwYTkzMWIzNDM0YTU2MjVkM2ZkNWQwNjQ0MjViNjE3ZjU1MjcwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RSMYRXlRz3RIhaCHx7n3b_23EZmeEk-_n9srixp5Ui0) با همین تنظیمات آیپی و دامنه های ایران دایرکت میشن اگه از JSON Subscription استفاده کنین

درود ، ممنونم داداش
الانم تنظیماتم همینه دقیقا ولی بعضی برنامه ها مثل ایرانسل ، همراه اول و .... تا واردشون میشم اعلام میکنه که شما با وی پی ان اومدین ، میخواهم این مشکل رو حل کنم  ، برای شما این مشکل وجود نداره ؟ 
برای مثال این برنامه همراه اول » 

![image](https://github.com/user-attachments/assets/935ea5c4-37fb-4f26-88ea-1dd009eb6bc6)

**Comment by TheyCallMeSecond** [comment]
> > ![image](https://private-user-images.githubusercontent.com/73380906/380484144-1d752000-e9be-4fcf-9569-4c7e3ae28c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjQzNzQsIm5iZiI6MTczMDA2NDA3NCwicGF0aCI6Ii83MzM4MDkwNi8zODA0ODQxNDQtMWQ3NTIwMDAtZTliZS00ZmNmLTk1NjktNGM3ZTNhZTI4YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDJlMDc2M2YzOTIyNGIwOWJhMmFiYjQwYTkzMWIzNDM0YTU2MjVkM2ZkNWQwNjQ0MjViNjE3ZjU1MjcwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RSMYRXlRz3RIhaCHx7n3b_23EZmeEk-_n9srixp5Ui0) با همین تنظیمات آیپی و دامنه های ایران دایرکت میشن اگه از JSON Subscription استفاده کنین
> 
> درود ، ممنونم داداش الانم تنظیماتم همینه دقیقا ولی بعضی برنامه ها مثل ایرانسل ، همراه اول و .... تا واردشون میشم اعلام میکنه که شما با وی پی ان اومدین ، میخواهم این مشکل رو حل کنم ، برای شما این مشکل وجود نداره ؟ برای مثال این برنامه همراه اول »
> 
> ![image](https://private-user-images.githubusercontent.com/131817501/380533680-935ea5c4-37fb-4f26-88ea-1dd009eb6bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjc0MDksIm5iZiI6MTczMDA2NzEwOSwicGF0aCI6Ii8xMzE4MTc1MDEvMzgwNTMzNjgwLTkzNWVhNWM0LTM3ZmItNGYyNi04OGVhLTFkZDAwOWViNmJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QyMjExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWUxNDQzOTc0ZjFkYTMyZjBjNjVmODM4Yzc4Y2NiYmEzNDRmZDFiNTZmYzg5MTJhODNhMjE3MTQ5NzgwNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dG-neqSYPbVguNqgPZp-Z9--zPFpiW-zsecI19BDhhs)

گفتم این رو هم بالاتر،اپ ‌ها رو میتونین از داخل کلاینت بایپس کنین، با رول نمیشه دایرکتشون کرد چون ریکوئست میزنن به کلاودفلر آیپی رو از اونجا میگیرن میفهمن وی‌پی‌ان روشنه

**Comment by roozbehalamdari** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/73380906/380484144-1d752000-e9be-4fcf-9569-4c7e3ae28c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjQzNzQsIm5iZiI6MTczMDA2NDA3NCwicGF0aCI6Ii83MzM4MDkwNi8zODA0ODQxNDQtMWQ3NTIwMDAtZTliZS00ZmNmLTk1NjktNGM3ZTNhZTI4YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDIxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNDJlMDc2M2YzOTIyNGIwOWJhMmFiYjQwYTkzMWIzNDM0YTU2MjVkM2ZkNWQwNjQ0MjViNjE3ZjU1MjcwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RSMYRXlRz3RIhaCHx7n3b_23EZmeEk-_n9srixp5Ui0) با همین تنظیمات آیپی و دامنه های ایران دایرکت میشن اگه از JSON Subscription استفاده کنین
> > 
> > 
> > درود ، ممنونم داداش الانم تنظیماتم همینه دقیقا ولی بعضی برنامه ها مثل ایرانسل ، همراه اول و .... تا واردشون میشم اعلام میکنه که شما با وی پی ان اومدین ، میخواهم این مشکل رو حل کنم ، برای شما این مشکل وجود نداره ؟ برای مثال این برنامه همراه اول »
> > ![image](https://private-user-images.githubusercontent.com/131817501/380533680-935ea5c4-37fb-4f26-88ea-1dd009eb6bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjc0MDksIm5iZiI6MTczMDA2NzEwOSwicGF0aCI6Ii8xMzE4MTc1MDEvMzgwNTMzNjgwLTkzNWVhNWM0LTM3ZmItNGYyNi04OGVhLTFkZDAwOWViNmJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QyMjExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWUxNDQzOTc0ZjFkYTMyZjBjNjVmODM4Yzc4Y2NiYmEzNDRmZDFiNTZmYzg5MTJhODNhMjE3MTQ5NzgwNjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dG-neqSYPbVguNqgPZp-Z9--zPFpiW-zsecI19BDhhs)
> 
> گفتم این رو هم بالاتر،اپ ‌ها رو میتونین از داخل کلاینت بایپس کنین، با رول نمیشه دایرکتشون کرد چون ریکوئست میزنن به کلاودفلر آیپی رو از اونجا میگیرن میفهمن وی‌پی‌ان روشنه

بله همین کار هم کردم ولی متاسفانه باز هم همین اررور رو میدن خودتون اگر تست کنید متوجه منظورم میشید

**Comment by alireza0** [comment]
داریرکت کردن از گوشی کلاینت فقط از طریق نرم افزارهایی که ساب جیسون رو پشتیبانی میکنن ممکنه.
و حتما باید قوانین مسیریابی رو هم پشتیبانی کنه. مثل خود نرم افزار سینگ باکس
بخش تنظیمات ساب جیسون به این صورت باید تنظیم بشه:
![image](https://github.com/user-attachments/assets/10406bd7-74ed-49df-a212-3d02f31eab7d)

**Comment by alireza0** [comment]
> برای مثال این برنامه همراه اول »

دوست عزیز، نرم افزار همراه من برای اینکار از متد شبکه استفاده میکنه و باید از روش دایرکت کردن برنامه استفاده کرد.
در حال آماده کردن یک بخش برای اضافه کردن آی‌دی برنامه ها به لیست دایرکت هستم. این بخش با اضافه کردن قانون package_name انجام میشه.

**Comment by alireza0** [comment]
این مورد به ساب جیسون اضافه شد.
نکته اینه که ممکنه برای اپ های سمت آیفون به مشکل بخورید.
پس لطفا منتظر نسخه بعد باشید و تست بگیرید.

**Comment by alireza0** [comment]
با سفارشی کردن بخش ورودی های ساب جیسون میشه برنامه های این مدلی رو از اینباند Tun مستثنی کرد.
منتظر نسخه بعدی باشید.
![image](https://github.com/user-attachments/assets/3f8d3cc1-8bd0-4fec-99da-9698a9b66d6c)

**Comment by roozbehalamdari** [comment]
> با سفارشی کردن بخش ورودی های ساب جیسون میشه برنامه های این مدلی رو از اینباند Tun مستثنی کرد. منتظر نسخه بعدی باشید.

دمت گرم بابت توضیحاتت و از همه مهم تر بابت آپدیت جدید ♥
علیرضا جان ممنون میشم اگر از بخش تون هم یه عکس بدی طبق همون یه اینباند بسازم ، مرسی از تمام زحماتت
من اینطوری با این مقادیر ساختم نمیدونم درست هست یا نه 
![image](https://github.com/user-attachments/assets/ebecd2d9-8762-4ec4-945f-cb9f8c830ea6)

**Comment by alireza0** [comment]
دوتا داستان هست:
۱. تنظیم dns مستقیم رو حذف کنید!
۲. بستن سایت های تبلیغاتی رو حذف کنید ( دردسر داره برای کاربرها )

بقیه درست هستن

**Comment by roozbehalamdari** [comment]
علیرضا جان با پوزش ، من تغییرات رو انجام دادم ولی متاسفانه باز هم همون اررور رو دریافت میکنم لطفا میشه ببینی کجا رو اشتباه رفتم ؟ سپاس 
این از اینباند TUN : 
![image](https://github.com/user-attachments/assets/5f586ad8-8846-4a80-ad31-ecc0b7f18920)

اینم تنظیمات ساب جیسون : 
![image](https://github.com/user-attachments/assets/31b1c533-0c62-4c62-a9aa-f537bf22b105)

و اینم ارروری که همچنان پا برجاست :
![image](https://github.com/user-attachments/assets/7dea9342-96eb-4e48-ba17-d13e9e48adc0)

**Comment by roozbehalamdari** [comment]
> نیازی به تنظیم اینباند TUN در سرور ندارید. تنظیم ساب جیسون کافیه! برای پیدا کردن مشکلتون باید بررسی بیشتری انجام بدید: ۱. آیا اسم پیکیج استثنا شده درست وارد شده ؟ ۲. آیا نرم افزار کلاینت به درستی پیکج رو استثنا میکنه ( مشکل کلاینت سینگ باکس ) ۳. آیا نرم افزار همراه من از متد دیگری برای پیدا کردن روشن بودن vpn استفاده میکنه ؟ ( طبق گزارشات دوستان، این استثنا کردن جواب داده، ولی باید بیشتر روش کار کنید )

سپاس از راهنماییت 
1 - بله درسته 
![image](https://github.com/user-attachments/assets/95f4355b-b374-4032-8af9-161286311f05)

2 - والا آخرین ورژن سینگ باکس رو نصب کردم.
![image](https://github.com/user-attachments/assets/fce001b7-ce27-4c4c-84e9-e4d65c970eeb)

در مورد گزینه ی سوم : اینو دقیقا نمیدونم "بیشتر کار کردن یعنی چه کارایی " ممنون میشم بیشتر راهنماییم کنی یا اگر چیزی هست که شما میدونی بگی منم تست کنم ، دمت گرم

و یک موضوع دیگه اینکه چرا اسم پیکیج های استثنا شده بیشتری که اضافه میکنم رو اگر بخواهم مثلا یکیشونو پاک کنم نمیشه  ؟ 🤔

**Comment by alireza0** [comment]
دوستانی که قبلت زحمت کشیدن و روش کار کردن تمام بسته ها و ارتباطات رو چک میکردن تا مطمئن بشن که این نرم افزار داره مسیر درستی رو طی میکنه. باید با یک سرور خالی تست کنید.
پاک کردن تنظیماتی که دستی اضافه کردین با خود backspace یا delete کیبورد امکانپذیره.
