### ISSUE TITLE
خطای not authorise بعد از نصب

### ISSUE THREAD

**Issue by habibrazmi** [alireza0/s-ui#32]
سلام پنل نصب کردم بدون درخواست یوزر و پسورد وارد پنل میشه و هر دقیقه خطای قرمز Not authorized  میده

**Comment by alireza0** [comment]
درود بر شما
این مشکل برای اینه که session شما به اتمام رسیده.
میتونید از گزینه logout برای خروج استفاده کنید.
در نسخه بعدی به صورت اتوماتیک از صفحه اصلی خارج خواهد شد.

**Comment by alireza0** [comment]
این مشکل در نسخه جدید حل شده. لطفا بروزرسانی کنید
