### ISSUE TITLE
hysteria2 port part supports the "multi-port" 

### ISSUE THREAD

**Issue by amaliasal** [alireza0/s-ui#320]
**Describe the solution you'd like**
When I set the hysteria2 Client Side’s Multi Domain in Inbounds, the port can support ‘multi-port’.

**Describe alternatives you've considered**

https://hysteria.network/docs/developers/URI-Scheme/
Examples:
hysteria2://letmein@example.com:123,5000-6000/?insecure=1&obfs=salamander&obfs-password=gawrgura&pinSHA256=deadbeef&sni=real.example.com
or  just use 5000-6000
hysteria2://letmein@example.com:5000-6000/?insecure=1&obfs=salamander&obfs-password=gawrgura&pinSHA256=deadbeef&sni=real.example.com

I would appreciate it if it could be supported. Thank you.

**Comment by TheyCallMeSecond** [comment]
sing-box core doesn't support multiport, you can use multiport only with hysteria core

**Comment by alireza0** [comment]
To use multi-inbound client, you should use the benefit of subscription.
