### ISSUE TITLE
Hardcoded admin:admin

### ISSUE THREAD

**Issue by iambabyninja** [alireza0/s-ui#322]
Hello, @alireza0 
Dear friend,
Could you explain the reason behind using admin:admin as the default access credentials for the panel?

https://github.com/alireza0/s-ui/blob/419cce250f9b03c0b700f55f9da63e4564689014/backend/database/db.go#L23

Any scanner like Censys/Fofa/etc. will show thousands of panels with the default port and admin:admin credentials

I understand that this is the user’s responsibility, but maybe it’s worth considering assigning at least a default password on their behalf?

Thanks!

**Comment by alireza0** [comment]
Hello @iambabyninja

Thank you for your inquery and consideration.
I am trying to turn the dificulties of usages to a simple web solution with a bash script or docker setup.
In both solutions for users with basic knowledges it is very hard to find/check assiged password.
This solution is such a normal behaviour in all simple applications. Even if it is not admin:admin, password is writen down in their docs.

Scanners you mentioned has their own strategies and tests.
In this panel we are using default path as well. Scanners are always checking root path!
