### ISSUE TITLE
مشکل در اجرای پنل در  "Manual run"

### ISSUE THREAD

**Issue by HajPasha** [alireza0/s-ui#324]
با سلام و وقت بخیر خدمت علیرضا عزیز،

ابتدا می‌خواستم از شما بابت زحماتی که برای ساخت این پنل بی‌نظیر کشیده‌اید، تشکر کنم.  
من علاقه‌مند بودم که تغییراتی در پنل اعمال کنم تا آن را بهبود بخشم. طبق دستورالعمل، از قسمت "Manual run + contribution" استفاده کردم، اما به مشکلی برخوردم و پنل به درستی اجرا نمی‌شود.

در محیط اوبونتو 24.04 به این خطا رسیدم:
![image](https://github.com/user-attachments/assets/31775166-68eb-40e3-9836-7cd14b2986f9)

همچنین، در محیط ویندوز نیز با این خطا مواجه شدم:
![image](https://github.com/user-attachments/assets/7d60504b-395d-445c-b81d-68c4cd3c415c)

زمانی که سعی می‌کنم پنل را از طریق دستور `npm run dev` اجرا کنم، این ارور را دریافت می‌کنم:
![image](https://github.com/user-attachments/assets/51db6d05-4ab3-4311-8abb-eca974551c71)

این خطاها در پنل و در CLI به نمایش درآمده‌اند:
![image](https://github.com/user-attachments/assets/88dd6ef6-c787-42b3-ba28-04c705c42062)

اگر ممکن است راهنمایی کنید که چگونه می‌توانم این مشکل را رفع کنم.

با تشکر فراوان

**Comment by alireza0** [comment]
پکیج ها برای ubuntu 24 هنوز کامل نیستند و بسیاری از پکیج های پایه ای هنوز این نسخه رو پشتیبانی نمیکنند.
در مورد ویندوز هم همینطوره. باید منتظر بروزرسانی پکیج ها باشیم. میتونید با ubuntu 22 تست کنید.

در مورد خطای فرانت، باید شما یک backend پشت زمینه داشته باشید که بتونید فرانت رو جدا اجرا کنید.

**Comment by tinybug-m** [comment]
same error on ubuntu 22 

# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
2024/11/03 17:39:47 s-ui 1.1.0
2024/11/03 17:39:47 open bin/config.json: permission denied




__@__:~/Documents/test000000000000000000000/s-ui-main$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

**Comment by tinybug-m** [comment]
# on root

root@tinybug:/home/tinybug/Documents/test000000000000000000000/s-ui-main# ./runSUI.sh 

> frontend@1.1.0 build
> vue-tsc --noEmit && vite build

vite v5.4.10 building for production...
✓ 625 modules transformed.
dist/index.html                                    0.57 kB │ gzip:   0.37 kB
dist/assets/Vazirmatn-UI-NL-Regular.woff2         21.84 kB
dist/assets/materialdesignicons-webfont.woff2    403.22 kB
dist/assets/materialdesignicons-webfont.woff     587.98 kB
dist/assets/materialdesignicons-webfont.ttf    1,307.66 kB
dist/assets/materialdesignicons-webfont.eot    1,307.88 kB
dist/assets/ecdd403a6e21394f.css                 717.63 kB │ gzip: 102.72 kB
dist/assets/0f03770baf366acf.js                1,342.42 kB │ gzip: 410.69 kB
✓ built in 22.14s
Backend
go: downloading github.com/gabriel-vasile/mimetype v1.4.6
/root/go/pkg/mod/github.com/go-playground/validator/v10@v10.22.1/baked_in.go:25:2: github.com/gabriel-vasile/mimetype@v1.4.6: Get "https://proxy.golang.org/github.com/gabriel-vasile/mimetype/@v/v1.4.6.zip": dial tcp: lookup proxy.golang.org on 127.0.0.53:53: read udp 127.0.0.1:44192->127.0.0.53:53: i/o timeout
2024/11/03 18:10:21 s-ui 1.1.0

2024/11/03 18:10:21 /home/tinybug/Documents/test000000000000000000000/s-ui-main/backend/service/setting.go:82 record not found
[0.091ms] [rows:0] SELECT * FROM `settings` WHERE key = "timeLocation" ORDER BY `settings`.`id` LIMIT 1

2024/11/03 18:10:21 /home/tinybug/Documents/test000000000000000000000/s-ui-main/backend/service/setting.go:82 record not found
[0.101ms] [rows:0] SELECT * FROM `settings` WHERE key = "trafficAge" ORDER BY `settings`.`id` LIMIT 1
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

2024/11/03 18:10:21 template: pattern matches no files: `html/index.html

**Comment by alireza0** [comment]
In `build.sh` it is defined to build front-end and then copy the `dist/` files to `/backend/web/html/`.
You should make sure that these files are in the correct folder

> dist/index.html 0.57 kB │ gzip: 0.37 kB
> dist/assets/Vazirmatn-UI-NL-Regular.woff2 21.84 kB
> dist/assets/materialdesignicons-webfont.woff2 403.22 kB
> dist/assets/materialdesignicons-webfont.woff 587.98 kB
> dist/assets/materialdesignicons-webfont.ttf 1,307.66 kB
> dist/assets/materialdesignicons-webfont.eot 1,307.88 kB
> dist/assets/ecdd403a6e21394f.css 717.63 kB │ gzip: 102.72 kB
> dist/assets/0f03770baf366acf.js 1,342.42 kB │ gzip: 410.69 k

**Comment by tinybug-m** [comment]
I see the bug in the ./build.sh script. It appears to be missing a * after /dist/. Additionally, I noticed that s-ui never asked me for a username and password, so now s-ui is running, but I can't log in.

I apologize if my questions seem basic, but your assistance would be greatly appreciated.

Thank you!

**Comment by tinybug-m** [comment]
> In `build.sh` it is defined to build front-end and then copy the `dist/` files to `/backend/web/html/`. You should make sure that these files are in the correct folder
> 
> > dist/index.html 0.57 kB │ gzip: 0.37 kB
> > dist/assets/Vazirmatn-UI-NL-Regular.woff2 21.84 kB
> > dist/assets/materialdesignicons-webfont.woff2 403.22 kB
> > dist/assets/materialdesignicons-webfont.woff 587.98 kB
> > dist/assets/materialdesignicons-webfont.ttf 1,307.66 kB
> > dist/assets/materialdesignicons-webfont.eot 1,307.88 kB
> > dist/assets/ecdd403a6e21394f.css 717.63 kB │ gzip: 102.72 kB
> > dist/assets/0f03770baf366acf.js 1,342.42 kB │ gzip: 410.69 k

hello again brother i just send a pull request for fixing /build.sh problem 

thanks for help

**Comment by tinybug-m** [comment]
After manually installing and running S-ui (version 1.1.0):

ruby

root@tinybug:/home/tinybug/Documents/projects/s-ui/s-ui# ./sui 
2024/11/04 12:18:15 s-ui 1.1.0

When I log into the panel, I see that Sing Box is off. I am attempting to run S-ui manually to assist with the front-end development project, but the Sing Box status is preventing me from proceeding effectively.

Any guidance on how to ensure Sing Box is running would be greatly appreciated!

**Comment by alireza0** [comment]
You should download the proper s-ui release file depends on you system arch.
After extract, You can copy bin folder to the root of project.
Then:
```bash
cd bin
./runSingbox.sh
```
