### ISSUE TITLE
docker: sing-box  | FATAL[0000] read config at config.json: open config.json: no such file or directory

### ISSUE THREAD

**Issue by jeff47** [alireza0/s-ui#325]
**Describe the bug**
I'm using the docker compose setup as in the readme.  The GUI crashes and restarts in a loop, perhaps due to this error in the sing-box container:

**s-ui errors**:
```
(0x14f4300,0xc000041300)
(0x14f4300,0xc00022dae0)
(0x14f4300,0xc000522bd0)
(0x14f4300,0xc0005aa5e0)
(0x14f4300,0xc000041300)
(0x14f4300,0xc00046b230)
(0x14f4300,0xc000041ec0)
(0x14f4300,0xc000041300)
(0x14f4300,0xc000041310)
(0x14f4300,0xc0002180f0)
(0x14f4300,0xc000041300)
(0x14f4300,0xc00021a100)
and so on...
```
**sing-box error**:
```
sing-box  | FATAL[0000] read config at config.json: open config.json: no such file or directory
```

**Expected behavior**
There are no instructions etc on what to put in the initial config.json or where to place it.  Indeed, if I was comfortable crafting the config file for sing-box from scratch, I wouldn't be looking for a GUI!  :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04, Docker version 27.3.1, build ce12230

**Comment by alireza0** [comment]
It seems you are using a wrong configuration.
Please reset your config and each time provide us full data.
If it has same problem please ask a system admin for checking your setup.
