### ISSUE TITLE
اضافه شدن باتن ری استارت هسته

### ISSUE THREAD

**Issue by Me-verner** [alireza0/s-ui#328]
سلام متاسفانه گاهی اوقات هسته کرش می‌کنه حالا به هر دلیلی و تنها راهش اینه که مشکل رو از تو پنل حل کرد و رفت توی سرور از طریق منوی s-ui اون رو ری‌استارت کرد :)
متاسفانه توی پنل فقط گزینه ری استارت اپ هست که فکر می‌کنم فقط برای ری استارت کردن پنل هستش نه هسته اگه میشه یه گزینه هم برای ریستارت کردن هسته بذارید؛ تا در مواقع ضروری نیاز نباشه که مدام به سرور مراجعه کنیم.
ممنون از شما

**Comment by Me-verner** [comment]
و یک سوال دیگه آیا همچین چیزی توی پنل وجود داره ولی هنوز اضافه نشده باشه لطفاً اگر درخواستی از سمت پنل وجود داره بفرمایید که به چه صورت هست چون من هر چقدر گشتم چیزی پیدا نکردم

**Comment by setarehirani** [comment]
اشکالاتی وجود داره که خیلی باعث کرش کردن میشه، مثل ایجاد کاربر زمانی که با همون پروکسی وصل هستی، یا اینترنتت وسط این کار اگه قطع بشه، گاهی باعث undefined شدن همه ی پسورد ها توی کانفیگ میشه، راه درست کردنشم تغییری در کاربران هست، کلا به نظرم رفع باگهایی که باعث کرش شدن میشه مهمتر از دکمه ی ریستارت هست.

**Comment by roozbehalamdari** [comment]
> اشکالاتی وجود داره که خیلی باعث کرش کردن میشه، مثل ایجاد کاربر زمانی که با همون پروکسی وصل هستی، یا اینترنتت وسط این کار اگه قطع بشه، گاهی باعث undefined شدن همه ی پسورد ها توی کانفیگ میشه، راه درست کردنشم تغییری در کاربران هست، کلا به نظرم رفع باگهایی که باعث کرش شدن میشه مهمتر از دکمه ی ریستارت هست.

دقیقا با شما موافقم یه همچین باگ هایی واقعا آزار دهنده هستند امیدوارم علیرضا جان ورژن جدید رو هرچی زودتر بده بیرون و ما هم کلی لذت ببریم ، البته این هم در نظر داشته باشیم که واقعا جای خالی اون دکمه خالیه 😉

**Comment by Me-verner** [comment]
> اشکالاتی وجود داره که خیلی باعث کرش کردن میشه، مثل ایجاد کاربر زمانی که با همون پروکسی وصل هستی، یا اینترنتت وسط این کار اگه قطع بشه، گاهی باعث undefined شدن همه ی پسورد ها توی کانفیگ میشه، راه درست کردنشم تغییری در کاربران هست، کلا به نظرم رفع باگهایی که باعث کرش شدن میشه مهمتر از دکمه ی ریستارت هست.

درود وقتی که من چنین چیزی رو بیان کردم یعنی اینکه تمامی این موارد را تست کردم حتی با وجود رفع اشکال داخل پنل.. همچنان هسته به کرش کردن متعدد ادامه میده تا زمانی که به صورت فورس ری استارت بشه.
 پس این چیزی نیستش که به صورت خودکار حل بشه و گاهی اوقات نیاز هست که به صورت دستی و اجباری ریستارت انجام بشه.

**Comment by Me-verner** [comment]
> > اشکالاتی وجود داره که خیلی باعث کرش کردن میشه، مثل ایجاد کاربر زمانی که با همون پروکسی وصل هستی، یا اینترنتت وسط این کار اگه قطع بشه، گاهی باعث undefined شدن همه ی پسورد ها توی کانفیگ میشه، راه درست کردنشم تغییری در کاربران هست، کلا به نظرم رفع باگهایی که باعث کرش شدن میشه مهمتر از دکمه ی ریستارت هست.
> 
> دقیقا با شما موافقم یه همچین باگ هایی واقعا آزار دهنده هستند امیدوارم علیرضا جان ورژن جدید رو هرچی زودتر بده بیرون و ما هم کلی لذت ببریم ، البته این هم در نظر داشته باشیم که واقعا جای خالی اون دکمه خالیه 😉

امیدوارم هرچه سریع‌تر یه آپدیت جدید داشته باشیم و امکانات ضروری و پایه‌ای که نیاز هستش رو شامل بشه

**Comment by alireza0** [comment]
دکمه ریستارت در صفحه اصلی اضافه شد.
منتظر نسخه جدید باشید
