### ISSUE TITLE
  Failed to get logs  اجرا نشدن هسته sing box روی کانتینر داکر 

### ISSUE THREAD

**Issue by alizxamax** [alireza0/s-ui#329]
سلام و خسته نباشید 
من نسخه جدید s-ui رو روی کانتینر داکر نصب کردم ولی هسته singbox اجرا نمیشه 
![Screenshot (9)](https://github.com/user-attachments/assets/8a27861e-6d09-429f-b392-e73a12f8a6e3)
![Screenshot (10)](https://github.com/user-attachments/assets/e41dd0ff-4742-459f-92a4-f8ab85b1060d)

**Comment by joismine** [comment]
same issue

**Comment by alizxamax** [comment]
من از کانتینر ابر اروان استفاده میکنم

**Comment by alizxamax** [comment]
من از کانتینر ابراروان استفاده میکنم و s-ui رو از اول نصب کردم 


_2024/10/29 18:43:20 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:43:10 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:43:00 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:50 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:40 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:30 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:20 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:10 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
2024/10/29 18:42:00 WARNING - Get stats failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"_

من پنل x-ui شما رو با همین روش نصب کردم و بدون مشکل کار میکنه اما sui کار نمیکنه
متاسفانه x-ui هم پروتکل هایی که من نیاز دارم هم نداره

**Comment by alireza0** [comment]
این لاگی که فرستادید مربوط به کانتینر s-ui میشه.
لطفا لاگ کانتینر sing-box رو بفرستید.
کانتینر کلاد ها محل مناسبی برای اجرای دو کانتینر مرتبط نیست.

پروژه x-ui از یک کانتینر استفاده میکنه و ارتباطی با کانینتر دیگه نداره.

**Comment by alizxamax** [comment]
نه منظوز من این بود که من x-ui روی یک کانتینر دیگر نصب کردم و مشکلی نداشت و به همون شکل روی یک کانتینر جدید s-ui رو نصب کردم
![image](https://github.com/user-attachments/assets/bdc15fca-7988-4db6-99de-d19aa65d375c)

**Comment by alireza0** [comment]
عرض من هم همین بود که نمیشه از سرویس کانتینر ابرآروان برای s-ui استفاده کرد.
چون باید یک فولدر اشتراکی با کانتینر sing-box داشته باشه.

**Comment by alizxamax** [comment]
بله 
خیلی ممنون بابت پاسخگویی 
پنل شما خیلی به من کمک کرده تا حالا  🙏
