### ISSUE TITLE
سرتفکیتد

### ISSUE THREAD

**Issue by saeedbigdeli** [alireza0/s-ui#33]
سلام با این کد به من سرتیفکیتد نمیده و با کدهای دیگه هم میگیرم پنل دیگه باز نمیشه

**Comment by alireza0** [comment]
درود بر شما
ممکنه شما توی سروتون پکیج snapd رو نداشته باشید.
در این صورت باید قبل از اجرای دستورات پنل دستور زیر رو برای گرفتنش بزنید:
```bash
sudo apt install snapd -y
```

**Comment by shahinkhorshidfar** [comment]
https://github.com/alireza0/s-ui/issues/33#issue-2141041446

**Comment by mohalel** [comment]
درود بر شما 
امیدوارم یه روز به درستی زحمات شما رو جبران کنیم
مشکل من هم دقیقا این هست. اول snapd رو نصب کردم. سرتیفیکیشن هم گرفتم که توی این مسیر نصب شد:
/etc/letsencrypt/live/سابـدامین/...
این مسیر رو به پنل دادم
پذیرفته شد اما به محض ری استارت پنل با خطای 403 access denied مواجه شدم
فایلهای سرت رو به پوشه ای که در روت ساختم هم انتقال دادم اما فایده نداشت
