### ISSUE TITLE
faild to tunnel 

### ISSUE THREAD

**Issue by tinybug-m** [alireza0/s-ui#331]
hello dear 

i have an Iran server which has S-UI panel v1.0.0 

tunneled two servers one turkey and one France to my Iran server with this method :

1-create an inbound with the same port as my config on out of country server
2-create an outbound with my config from outside country 
3-rulling the inbound to route to the outbound 

for 24 hours it was working but then turkey tunnel stopped working 

notice : in turkey server i have got a X-UI panel 
notice 2 : when i tunnel France to turkey its working but in Iran its stopped 

only log i found is here:
Oct 29 18:32:20 Blog runSingbox.sh[3089]: ERROR[1668] [500459384 31.1s] inbound/vless[Turkey-TCP]: process connection from 2.147.55.134:48613: download: unknown version: 72

thank you for your great S-UI it has alot of bugs but i like it

**Comment by tinybug-m** [comment]
log update i think my turkey is getting blocked by sonsorship 

but when i use dekodemodoor tunnel its working in X-UI panel on both servers

Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [3385726409 0ms] inbound/vless[Turkey-TCP]: inbound connection from 2.147.55.134:20357
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [2154007228 0ms] inbound/vless[Turkey-TCP]: [sNQDgKpT] inbound connection to 10.10.34.35:443
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [2154007228 0ms] outbound/vless[Turkey-42833]: outbound connection to 10.10.34.35:443
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [2571107796 0ms] inbound/vless[Turkey-TCP]: inbound connection from 2.147.55.134:20356
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [738457786 0ms] inbound/vless[Turkey-TCP]: [sNQDgKpT] inbound connection to 10.10.34.35:443
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [738457786 0ms] outbound/vless[Turkey-42833]: outbound connection to 10.10.34.35:443
Oct 29 18:48:23 Blog runSingbox.sh[3089]: ERROR[2631] [320223974 9.96s] inbound/vless[Turkey-TCP]: process connection from 2.147.55.134:20344: download: unknown version: 72
Oct 29 18:48:23 Blog runSingbox.sh[3089]: ERROR[2631] [2531951122 8.3s] inbound/vless[Turkey-TCP]: process connection from 2.147.55.134:20347: download: unknown version: 72
Oct 29 18:48:23 Blog runSingbox.sh[3089]: ERROR[2631] [3205981592 7.99s] inbound/vless[Turkey-TCP]: process connection from 2.147.55.134:20348: download: unknown version: 72
Oct 29 18:48:23 Blog runSingbox.sh[3089]: ERROR[2631] [2674278836 9.98s] inbound/vless[Turkey-TCP]: process connection from 2.147.55.134:20343: download: unknown version: 72
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [2154007228 42ms] outbound/vless[Turkey-42833]: outbound connection to 10.10.34.35:443
Oct 29 18:48:23 Blog runSingbox.sh[3089]: INFO[2631] [738457786 45ms] outbound/vless[Turkey-42833]: outbound connection to 10.10.34.35:443

**Comment by alireza0** [comment]
Here we are not providing conectivity solutions. It is only about panel.

**Comment by tinybug-m** [comment]
Hi Alireza thanks for answering me 
okey but i like to know direct inbound works exaclty like a dekodemodoor ? so if is it there is a problem in panel !

**Comment by tinybug-m** [comment]
> Here we are not providing conectivity solutions. It is only about panel.

Hi Alireza thanks for answering me
okey but i like to know direct inbound works exaclty like a dekodemodoor ? so if is it there is a problem in panel !
