### ISSUE TITLE
یک سوال در مورد ف ولدر var

### ISSUE THREAD

**Issue by roozbehalamdari** [alireza0/s-ui#332]
درود ، ببخشید علیرضا جان یه سوال داشتم 

من دیشب متوجه شدم سی پی یو سرور مدام روی 98% به بالا بود و همش قرمز بود ، اومدم با دستور آپدیت و آپگرید سرور رو آپدیت کنم که دیدم هارد کاملا پر شده !  با یه دستور چک کردم ببینم کدوم فولدر یا فایل سایز بیشتری رو گرفته دیدم توی فولدر var دو تا فولدر هست که خیلی حجمشون بالا بود اومدم فولدر /var/log رو فایل های قدیمی تر از 7 روز گذشته اش رو پاک کردم که دیدم سی پی یو کلا آزاد شد و خیلی خوب شد 
حالا سوالم اینه : 
1 - آیا اگر فایل های این دو تا فولدری که توی عکس مشخص کردم رو پاک کنم سرور یا پنل به مشکل میخورن ؟ 
2 - دستوری هست که بشه براش مشخص کرد مثلا لاگ های var رو بیشتر از مثلا 1 گیگ شد پاک کنه یا مثلا هفته ای یک بار پاک کنه فایل های داخلش رو ؟ 
ببخشید اگر اینجا پرسیدم چون تجربه ی شما بیشتره خواستم راهنماییم کنی ♥

![image](https://github.com/user-attachments/assets/749d8a4f-b9ed-4558-90f5-5045226350a1)![image](https://github.com/user-attachments/assets/17226ae0-401e-40a0-9074-a78075b6ac69)

**Comment by alireza0** [comment]
درود بر شما
برای سوالات اینچنینی میتونید جستجو کنید، از chat-gpt بپرسید و یا با یک ادمین سیستم صحبت کنید.

این دو پوشه سیستم هستند و پاک کردنش مشکل سازه.
برای پاک کردن داده های غیر لازم در زمان های متوالی میتونید از cron استفاده کنید و یا برای لاگ ها از logrotate استفاده کنید
