### ISSUE TITLE
Hope to add a feature for periodic traffic reset

### ISSUE THREAD

**Issue by lingbaoboy** [alireza0/s-ui#336]
I hope to add a feature for periodic traffic reset. Most VPS services have a monthly traffic limit, and any unused traffic does not carry over to the next billing cycle, so traffic starts from zero in the next cycle. Currently, the panel allows setting user or inbound traffic limits and expiration dates for traffic, but for individual users, this feature is quite cumbersome. For example, if I set a traffic limit of 100GB (while the VPS has a monthly limit of 200GB) without an expiration date, I would need to log into the panel to reset the traffic when the 100GB is used up in two months. The ideal situation would be to set a 100GB traffic limit and specify a billing cycle to reset on the Nth day of each month. Then, on the Nth day, the used traffic should automatically reset.

**Comment by alireza0** [comment]
In panel, it will add more unnecessary complexity.
We had a bad experience in x-ui before for this feature.

Instead:
You can run a crontab to apply traffic reset in database manually.

**Comment by lingbaoboy** [comment]
Instead:
You can run a crontab to apply traffic reset in database manually.

Can you tell me how to do it specifically?

**Comment by alireza0** [comment]
It depends on your system. It is better to consult with a System Admin.
