### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by smcrack** [alireza0/s-ui#338]
`docker compose up -d` error
Container s-ui Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": stat ./entrypoint.sh: no such file or directory: unknown

**Comment by alireza0** [comment]
Please follow the instruction in repo's main page correctly.
Also in the future please provide sufficient information
