### ISSUE TITLE
مشکل هتزنر با گوگل و خطای 403

### ISSUE THREAD

**Issue by fmazaheri** [alireza0/s-ui#346]
سلام
من s-ui رو روی سرورهای هتزنر ران کردم و همه چی خوبه. تنها مشکل سرویس های گوگل مثل ادز و آنالیتیکز و اینهاست که باز نمیشن و خطای ۴۰۳ میدن.
اینجا یه راه حل خوندم
https://github.com/Gozargah/Marzban/discussions/734
و خواستم ببینم آیا میشه روی s-ui اجراشون کرد.
تو قسمت Outbands و basic یه چیزهایی دیدم ولی چون خیلی بلد نیستم نمی‌دونم باید چه تغییراتی بدم.
با تشکر

**Comment by alireza0** [comment]
درود بر شما
توی خروجی direct با فعال کردن Domain strategy در Dial Options میتونید استراتژی رو تغییر بدید.
