### ISSUE TITLE
The Shadowtls configuration problem

### ISSUE THREAD

**Issue by nicelic** [alireza0/s-ui#348]
I see that sui can configure the shadowtls, but when I go in to configure, shadowtls v3 can only configure a handshake domain name (v3 does not require a password), there are no other options to configure shadowtls, all are general options, and the same is true for dial-up options. Shadowtls v2 only has an additional password option compared to shadowtls v3. 
Feature suggestion: Can you add an option to directly configure the sing-box code at the inbound? Some proxies that need sing-box can add their own inbound codes. For example, UUID can first add a user, then copy a uuid from the user and paste it into your own configuration options.

**Comment by alireza0** [comment]
In S-UI user configuration will be added by client configuration. When you define a client with shadowtls inbound in inbounds list, panel will add the user/password to the inbound.
Shadotls clients has not UUID and only user/password needed for authentication.
[ref](https://sing-box.sagernet.org/configuration/inbound/shadowtls)
