### ISSUE TITLE
استفاده از پنل پشت کلادفلر

### ISSUE THREAD

**Issue by neomn** [alireza0/s-ui#349]
سلام . وقت بخیر
پنل رو با دامنه بردم پشت کلادفلر ولی کافیگ ها با پورت های https پشتیبانی شده توسط کلادفلر متصل نمیشن 
قبلا با پنل های دیگه این کارو انجام دادم و مشکلی نبود ولی این پنل رو نتونستم. کسی موفق شده این کار رو انجام بده ‌؟‌

**Comment by Arman-nsb** [comment]
هر پروتکلی پشت cdn کار نمیده. مثلا hysteria حتما باید مقدار آدرس به آی پی سرور اشاره کنه بدون cdn.

**Comment by neomn** [comment]
> هر پروتکلی پشت cdn کار نمیده. مثلا hysteria حتما باید مقدار آدرس به آی پی سرور اشاره کنه بدون cdn.

اینو میدونستم. برا من هیچکدوم کار نمیده. ولی پنل های دیگه رو میبرم پشت سی دی ان اوکیه

**Comment by Arman-nsb** [comment]
من تست کردم مشکلی نداشته با vless ws tls پشت کلودفلر. (ssl رو با دستورات cli خود s-ui گرفتم و ست کردم رو پنل و اینابند)

**Comment by alireza0** [comment]
درود بر شما
بردن سرویس پشت کلادفلر ( مخصوصا نسخه رایگان ) محدودیت های زیادی داره.
شما از هر پورتی نمیتونید استفاده کنید.
شما از هر پروتکلی نمیتونید استفاده کنید.
تنظیمات دیگه هم نباید با روش کار کلادفلر مغایرت داشته باشه.

**Comment by neomn** [comment]
@alireza0 
پرت های https کلادفلر که اینها هستن
443
2053
2083
2087
2096
8443
من همه رو تست کردم با کانفیگ های مختلف ولی جواب نگرفتم 
آموزش های زیادی هم تو یوتیوب ولی هیچکدوم پشت سی دی ان رو کامل توضیج نداه. 
منبعی هست که توضیح داده باشه ؟

**Comment by alireza0** [comment]
منبع زیاده
باید جستجو کنید

**Comment by mahboobhameh-tech** [comment]
> درود بر شما بردن سرویس پشت کلادفلر ( مخصوصا نسخه رایگان ) محدودیت های زیادی داره. شما از هر پورتی نمیتونید استفاده کنید. شما از هر پروتکلی نمیتونید استفاده کنید. تنظیمات دیگه هم نباید با روش کار کلادفلر مغایرت داشته باشه.

علیرضای عزیز مهندس بزرگ واقعا خسته نباشید شاهکار کردید با این پنل 
اما داداش واقعا من هر کاری کردم نتونستم vless-tls-ws   راه اندازی کنم تو پنل ایکس یو ای  راه اندازی کردم بدون هیچ مشکلی هم تو پنتل اس یو ای فکر کنم ب خاطر اینکه flow  پیشفرض فعال میشه کار نمیکنه ولی vless-tcp -tls  کار می کنه لطفا یه راهنمایی دقیق بکنید ممنونم
