### ISSUE TITLE
创建shadowTLS后无法使用

### ISSUE THREAD

**Issue by sjkhsl** [alireza0/s-ui#356]
创建shadowTLS后无法使用，提示`ERROR[0015] [332209514 3ms] inbound/
tun[ol: missing supported outbound,
closing packet connection`，查询各种资料，singbox配置shadowTLS有一个`detour`字段，来创建一个shadowsocks得入站，应该是将数据转发到`detour`入站的意思？然后我又创建了一个shadowsocks入站列表，在shadowTLS中开启转发，然后选中shadowsocks入站列表，可是还是提示`ERROR[0015] [332209514 3ms] inbound/
tun[ol: missing supported outbound,
closing packet connection`，这个提示是缺少一个出站？可是配置shadowsocks出站更加不对了～

**Comment by alireza0** [comment]
Please provide us your configuration

**Comment by sjkhsl** [comment]
> Please provide us your configuration

如何提供配置文件？配置文件的路径是什么？

**Comment by alireza0** [comment]
Configuration file is here:
```
/usr/local/s-ui/bin/config.json
```

But it is enough to share your configuration in GUI as screen shoots (considering security)

**Comment by sjkhsl** [comment]
![Snipaste_2024-11-16_09-28-19](https://github.com/user-attachments/assets/f2fa254b-5fb5-4971-9215-26192b16d7ce)
![Snipaste_2024-11-16_09-29-27](https://github.com/user-attachments/assets/bb129e6a-685b-43be-9958-386b7ff306b5)

设置转发到入站，和不设置转发，都无法通信。

**Comment by sjkhsl** [comment]
> Configuration file is here:
> 
> ```
> /usr/local/s-ui/bin/config.json
> ```
> 
> But it is enough to share your configuration in GUI as screen shoots (considering security)

请帮我看一看上述配置有问题吗？

**Comment by sjkhsl** [comment]
> The error you mentioned is not related to this inbound. But related to `tun` inbound configuration.

不确定日志提示是否和shadowTLS有关，但是这个配置无法使用，我的配置有问题吗？

**Comment by alireza0** [comment]
I can't see any problem in pictures. But it is clear that ShadowTLS inbound is not the first one. And errors showed that it is related to first inbound and this inbound type is TUN.
I have tested your configuration and works fine here.

**Comment by sjkhsl** [comment]
> I can't see any problem in pictures. But it is clear that ShadowTLS inbound is not the first one. And errors showed that it is related to first inbound and this inbound type is TUN. I have tested your configuration and works fine here.

配置shadowtls时需不需要配置一个shadowsocks的转发入站？多次测试无法使用，不知道问题出在哪里～

**Comment by alireza0** [comment]
In documentation, there is no need to define a detour for shadowTLS. In my tests, it works fine without any needs of using another protocol like shadowsocks.
