### ISSUE TITLE
自定义tls路径问题

### ISSUE THREAD

**Issue by sjkhsl** [alireza0/s-ui#357]
tls路径可以访问/root路径吗？如果不可以，怎么授权？

**Comment by alireza0** [comment]
It is a question which should be answered by a system admin and not panel.
But your answer is:
s-ui should run with root user and this user has access to all pathes.
If you are using another user to run s-ui, just give proper access to the folder.

**Comment by sjkhsl** [comment]
> It is a question which should be answered by a system admin and not panel. But your answer is: s-ui should run with root user and this user has access to all pathes. If you are using another user to run s-ui, just give proper access to the folder.

是通过root安装的s-ui面板，然后自行通过acme申请证书，将证书和私钥放置在/root/下，在面板中设置证书和私钥路径后，不确定是否生效，能在面板的tls管理中加入证书路径设置后是否成功的验证信息？

**Comment by alireza0** [comment]
If you installed it via bash script on root user, panel has access to all paths.
Just don't forget to use full path like this:
```
/root/.acme.sh/example.com/example.com.cer
/root/.acme.sh/example.com/examle.com.key
```

**Comment by sjkhsl** [comment]
> If you installed it via bash script on root user, panel has access to all paths. Just don't forget to use full path like this:
> 
> ```
> /root/.acme.sh/example.com/example.com.cer
> ```
> 
> And
> 
> ```
> /root/.acme.sh/example.com/examle.com.key
> ```

证书的格式支持crt吗？

**Comment by alireza0** [comment]
Your answer is [here](https://github.com/acmesh-official/acme.sh/issues/157#issuecomment-211677165)
