### ISSUE TITLE
Subscription port Not required

### ISSUE THREAD

**Issue by jocelen** [alireza0/s-ui#360]
**Is your feature request related to a problem? Please describe.**
I don't want to expose the port number in the subscription link, and hope that the port can be configured without

**Describe the solution you'd like**
When I set the subscription configuration in version 1.1.0, the port number is required, which means that the subscription QR-Code link must have the port number.

**Describe alternatives you've considered**
I don't want to expose the port number in the link, so I did path forwarding in nginx. However, the port number is required, so the port will definitely be exposed. I hope to set it to be an optional configuration. If it is set to empty, there will be no port number.

**Additional context**
Thank you for your contribution, I will continue to use and give feedback

**Comment by sjkhsl** [comment]
在面板-设置-订阅-地址里填写127.0.0.1就可以了啊，这样只监听本地！

**Comment by alireza0** [comment]
Just use your final URI in `Subscription URI` in subscription setting.
QR-codes will be updated accordingly
