### ISSUE TITLE
Chinese localization inaccurate

### ISSUE THREAD

**Issue by jocelen** [alireza0/s-ui#361]
**Describe the bug**
Chinese localization has problems, "编辑1" -> "编辑"
![edit1](https://github.com/user-attachments/assets/57cdd83a-fcd6-4723-80c0-4fdcd860a0b9)

**Additional context**
Thank you for your contribution

**Comment by alireza0** [comment]
Thank you for your report. I will fix this typo soon

**Comment by alireza0** [comment]
It was on client page for all languages just for debugging porposes which should be deleted.
It is fixed now and won't show on next release.
