### ISSUE TITLE
关于同用户配置及路由配置的问题

### ISSUE THREAD

**Issue by sjkhsl** [alireza0/s-ui#365]
经测试同用户不能创建相同协议的入站列表，后创建的无法连接，至少vless是这样。
路由列表中创建新的路由规则，指定入站和指定出站无法起作用，入站连接走的默认出站，不会走指定出站。

![Snipaste_2024-11-18_16-39-16](https://github.com/user-attachments/assets/286e4807-321f-430e-89d3-af2a32569ce5)

**Comment by alireza0** [comment]
The order of rules plays an important role. Packet may match to the previous rule.
You can change the priority of rules by drag and drop (version 1.1.0 and above).

**Comment by sjkhsl** [comment]
> The order of rules plays an important role. Packet may match to the previous rule. You can change the priority of rules by drag and drop (version 1.1.0 and above).

哦哦，忽略了规则顺序，我在试一试～
