### ISSUE TITLE
Disable Panel Access

### ISSUE THREAD

**Issue by MehranVZ** [alireza0/s-ui#369]
How can I disable the panel so that entering the server IP address doesn't open up the panel?

**Comment by alireza0** [comment]
Just change the panel listen ip in the panel configuration to 127.0.0.1

**Comment by MehranVZ** [comment]
Thanks for the quick response. I can understand what you mean but there would be a little problem! If I change the panel listen IP to localhost, how can i later change it back to 0.0.0.0/0 so that i can access it again in the future?

**Comment by alireza0** [comment]
Tou can use ssh tunnel ( port forward ) to access the panel.

Another solution for temporary blocking access is using iptables.

There are lots of solutions for block/permit access. You can ask a system admin or simply google or ask chatGPT
