### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by sinazlf** [alireza0/s-ui#370]
ارادت ارور زیر تو لاگ مشاهده میشه ممنون میشم راه حلشو بگید
`Nov 25 17:14:13 boring-attraction-cloned.aeza.network sui[901683]: 2024/11/25 17:14:13 http: TLS handshake error from 127.0.0.1:52426: read tcp 127.0.0.1:20>
Nov 25 17:14:37 test.network sui[901683]: 2024/11/25 17:14:37 http: TLS handshake error from 127.0.0.1:35798: read tcp 127.0.0.1:20>
Nov 25 17:16:26 test.network sui[901683]: 2024/11/25 17:16:26 http: TLS handshake error from 127.0.0.1:39472: read tcp 127.0.0.1:20>
Nov 25 17:18:01 test.network sui[901683]: 2024/11/25 17:18:01 http: TLS handshake error from 127.0.0.1:59860: read tcp 127.0.0.1:20>
Nov 25 17:18:11 test.network sui[901683]: 2024/11/25 17:18:11 http: TLS handshake error from 127.0.0.1:49882: read tcp 127.0.0.1:20>
Nov 25 17:18:42 test.network sui[901683]: 2024/11/25 17:18:42 http: TLS handshake error from 127.0.0.1:60320: read tcp 127.0.0.1:20>
Nov 25 17:24:20 test.network sui[901683]: 2024/11/25 17:24:20 http: TLS handshake error from 127.0.0.1:58600: read tcp 127.0.0.1:20>
Nov 25 17:26:01 test.network sui[901683]: 2024/11/25 17:26:01 http: TLS handshake error from 127.0.0.1:45992: read tcp 127.0.0.1:20>
Nov 25 17:34:33 test.network sui[901683]: 2024/11/25 17:34:33 http: TLS handshake error from 127.0.0.1:42458: read tcp 127.0.0.1:20>
Nov 25 17:34:36 test.network sui[901683]: 2024/11/25 17:34:36 http: TLS handshake error from 127.0.0.1:42476: read tcp 127.0.0.1:20>
`

**Comment by alireza0** [comment]
درود بر شما
برقراری ارتباط امن برای پنل و سابسکرپشن با https توسط پکیج crypto/tls انجام میشه و ترجیح من این بوده که خطاهای این ارتباط مستقیم به خروجی نرم افزار (stdout) بره.
این خطا زمانی بوجود میاد که پروسه برقراری ارتباط tls به درستی انجام نمیشه. این میتونه به دلایل مختلف ایجاد بشه. یکی از اونها فیلترینگ و ارتباط ناقص کاربر میتونه باشه. ولی مهمترین دلیلش اسکنرها و تسترهای مختلف هستن که مخصوصا وفتی پشت پراکسی هایی مثل کلادفلر هستید، به تعداد زیاد مشاده میشه.
راه حل خاصی براش نیست! میتونیم اون رو توی لاگ های پنل بیاریم ( که به دلیل بی اهمیت بودن ترجیح من نبوده ) یا نادیده بگیریم و یا با محدودیت های مختلف مثل نرم افزارهای امنیتی جلوی این تلاش ها رو بگیریم.
