### ISSUE TITLE
مشکل در مسدود سازی دامنه ها و ip های داخل ایران از سمت سرور

### ISSUE THREAD

**Issue by biaselectronic** [alireza0/s-ui#376]
بادرود، خسته نباشید
برای مستقیم کردن دامنه ها و ایپی های ایران از داخل پنل مشکلی ندارم ولی برای تنظیم فایل ads برای بلاک کردن ایپی های ایران ارور دریافت می کنم لطفا راهنمایی کنید:

![Screenshot 2024-12-01 095214](https://github.com/user-attachments/assets/e52fc3d5-2c06-4530-8f3d-728fde7f94ad)

تنظمیات:
![Screenshot 2024-12-01 095248](https://github.com/user-attachments/assets/791b6d28-942c-48cc-9480-2753cb4d3a1b)

![Screenshot 2024-12-01 095259](https://github.com/user-attachments/assets/1bcc2705-c651-46ce-abb6-b15990f78c3a)

**Comment by tinybug-m** [comment]
hello dear 

just change Ruleset outbound to `direct` and its going to fix 

and if you wonder why its because to S-UI can download the Ruleset 
and for rule you should set outbout to block

**Comment by HajPasha** [comment]
با توجه به اسکرین شاتی که فرستادید  در قسمت Outbound به جای تگ "Block" باید از تگ "Direct" استفاده کرد 
به همین دلیل کانفیگ شما میخواهد آن Ruleset را دانلود و اجرا کند اما به به خاطر اینکه از تگ بلاک استفاده کردید دسترسی اینترنت ان را قطع کرده اید به همین دلیل ارور خواهد داد
