### ISSUE TITLE
naive only can use ip?

### ISSUE THREAD

**Issue by bigm0re** [alireza0/s-ui#38]
![CopyQ cBwzaa](https://github.com/alireza0/s-ui/assets/45556726/069fb51c-95c8-447e-bd40-d866002648e2)
![CopyQ XoDaJO](https://github.com/alireza0/s-ui/assets/45556726/3ffa68fe-b309-44f5-8bc6-a094c7997a4c)

If you use a domain name, singbox cannot be started.

**Comment by alireza0** [comment]
Service could only start with an IP. Domain is not related to IP/Port of a service
