### ISSUE TITLE
Does it have the capability to support server-side traffic routing?

### ISSUE THREAD

**Issue by harrisonyao** [alireza0/s-ui#381]
Hi there, 

I have set up a new proxy server using s-ui V1.1.0, and I also have a SOCKS5 proxy server. I want to forward certain special domain requests received by the s-ui proxy server to the SOCKS5 proxy server for data processing. I have configured the relevant SOCKS5 outbounds and corresponding selectors in the config.json, as well as the corresponding rules in the routing section. However, the results are not as expected. When I access those special domains, the requests are not forwarded to the SOCKS5 server as I hoped. Here is an excerpt of my configuration. Please provide some assistance, thank you.

{
   "log": {
     "level": "debug",
     "disabled": false,
     "timestamp": true,
     "output": "/root/logs/s-ui.log"
   },
   "dns": {
     "servers": []
   },
   "ntp": {
     "enabled": true,
     "server": "time.apple.com",
     "server_port": 123,
     "interval": "30m"
   },
   "inbounds": [
     {
       "type": "hysteria2",
       "users": [
         {
           ...
         }
         
       ],
       "tag": "hysteria2-1234",
       "listen": "::",
       "listen_port": 1234,
       "ignore_client_bandwidth": true,
       "obfs": {
         "type": "salamander",
         "password": "hello1234"
       }
     }
   ],
   "outbounds": [
     {
       "tag": "direct",
       "type": "direct"
     },
     {
       "type": "dns",
       "tag": "dns-out"
     },
     {
        "tag": "us_home_out",
        "type": "selector",
        "outbounds": [
            "US_HOMEIP"
        ],
        "default": "US_HOMEIP"
     },
     {
       "type": "socks",
       "version": "5",
       "tag": "US_HOMEIP",
       "username": "...",
       "password": "...",
       "server": "...",
       "server_port": ...,
       "domain_strategy": "prefer_ipv4",
       "fallback_delay": "300ms"
     }
   ],
   "route": {
     "rules": [
       {
         "protocol": "dns",
         "outbound": "dns-out"
       },
       {
          "rule_set": [
              "OpenAI.srs",
              "TikTok.srs"
          ],
          "outbound": "us_home_out"
       }
     ],
     "rule_set": [
       {
         "tag": "OpenAI.srs",
         "type": "remote",
         "format": "binary",
         "url": "https://raw.githubusercontent.com/tangnahuaite/sing-box_Route-rules/main/rule_srs/OpenAI.srs",
         "download_detour": "direct",
         "update_interval": "1d"
       },
       {
         "tag": "TikTok.srs",
         "type": "remote",
         "format": "binary",
         "url": "https://raw.githubusercontent.com/tangnahuaite/sing-box_Route-rules/main/rule_srs/TikTok.srs",
         "download_detour": "direct",
         "update_interval": "1d"
       }
     ],
     "final": "direct"
   },
   "experimental": {
     "v2ray_api": {
       "listen": "127.0.0.1:1080",
       "stats": {
         "enabled": true,
         "inbounds": [
           ...
         ],
         "outbounds": [
           "direct",
           "US_HOMEIP"
         ],
         "users": [
           ...
         ]
       }
     }
   }
 }

**Comment by harrisonyao** [comment]
> Hello @harrisonyao The problem is that you did not define any routing rule for your scenario. Please define a rule and use your defined rule-sets there

Thanks @alireza0 , but I was defined a route rule in my config.json that was shown in the first post, I re-post it again :
`
{
    "log": {
        "level": "debug",
        "disabled": false,
        "timestamp": true,
        "output": "/root/logs/s-ui.log"
    },
    "dns": {
        "servers": []
    },
    "ntp": {
        "enabled": true,
        "server": "time.apple.com",
        "server_port": 123,
        "interval": "30m"
    },
    "inbounds": [
        {
            "type": "hysteria2",
            "users": [
                {}
            ],
            "tag": "hysteria2-1234",
            "listen": "::",
            "listen_port": 1234,
            "ignore_client_bandwidth": true,
            "obfs": {
                "type": "salamander",
                "password": "hello1234"
            }
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        },
        {
            "tag": "us_home_out",
            "type": "selector",
            "outbounds": [
                "US_HOMEIP"
            ],
            "default": "US_HOMEIP"
        },
        {
            "type": "socks",
            "version": "5",
            "tag": "US_HOMEIP",
            "username": "...",
            "password": "...",
            "server": "...",
            "server_port": 12345,
            "domain_strategy": "prefer_ipv4",
            "fallback_delay": "300ms"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "rule_set": [
                    "OpenAI.srs",
                    "TikTok.srs"
                ],
                "outbound": "us_home_out"
            }
        ],
        "rule_set": [
            {
                "tag": "OpenAI.srs",
                "type": "remote",
                "format": "binary",
                "url": "https://raw.githubusercontent.com/tangnahuaite/sing-box_Route-rules/main/rule_srs/OpenAI.srs",
                "download_detour": "direct",
                "update_interval": "1d"
            },
            {
                "tag": "TikTok.srs",
                "type": "remote",
                "format": "binary",
                "url": "https://raw.githubusercontent.com/tangnahuaite/sing-box_Route-rules/main/rule_srs/TikTok.srs",
                "download_detour": "direct",
                "update_interval": "1d"
            }
        ],
        "final": "direct"
    },
    "experimental": {
        "v2ray_api": {
            "listen": "127.0.0.1:1080",
            "stats": {
                "enabled": true,
                "inbounds": [],
                "outbounds": [
                    "direct",
                    "US_HOMEIP"
                ],
                "users": []
            }
        }
    }
}
`

**Comment by alireza0** [comment]
If your rule-sets contain Domain names, you need to define `sniffing` in inbound to detect domain names from connections.

**Comment by harrisonyao** [comment]
> If your rule-sets contain Domain names, you need to define `sniffing` in inbound to detect domain names from connections.

Oh yes, I forgot this property, that's ok now after open it, thanks @alireza0
