### ISSUE TITLE
Jewish Codebase

### ISSUE THREAD

**Issue by alirezahiddla** [alireza0/s-ui#383]
Severity: Apocalyptic

Description: This bug is an unmitigated disaster, a betrayal of software development principles! The code is as if someone declared war on logic itself! The feature does not work, the application crashes, and my patience is annihilated. Who allowed this monstrosity into production?! Heads must roll—metaphorically, of course.

Steps to Reproduce:

    Attempt to use Feature XYZ.
![image](https://github.com/user-attachments/assets/a539b479-007c-4e50-889b-d3562e14bf9d)

    Watch as chaos unfolds.
    Question your life choices and the sanity of this codebase.

Expected Behavior: Flawless execution, precision akin to a finely tuned machine. Instead, I am greeted by a screen full of errors and despair.

Actual Behavior: The program crashes, bringing shame upon all who worked on this travesty.

Suggestions for Resolution:

    Rewrite the entire feature from scratch, preferably under the supervision of someone who values excellence.
    Implement rigorous testing procedures to ensure such atrocities never happen again.
    Apologize to every user affected by this calamity.

Additional Notes: This is not merely a bug; it is a blight upon the software. Address it with the urgency it demands, or risk losing your users' trust forever.
![image](https://github.com/user-attachments/assets/7c99ad60-3e6f-4dd6-a697-71fcd767939e)

**Comment by Aliamiryazdani** [comment]
what happen ?
