### ISSUE TITLE
برای بازی از چه پروتکلی استفاده کنم؟

### ISSUE THREAD

**Issue by Aliamiryazdani** [alireza0/s-ui#384]
درود علیرضا جان
برای استفاده برای بازی آنلاین پیشنهادت استفاده از چه پروتکلییه؟
و آیا باید کانفیگ با چیزی روی سرور انجام یا نصب کنم؟

تشکر فراوان

**Comment by alireza0** [comment]
درود بر شما
راستش من داده های زیادی در اینباره ندارم.
بهتره از گروه هایی که در زمینه پروتکل ها و روش پیکربندی اونها همفکری دارند بپرسید.
