### ISSUE TITLE
Is there a plan for change panel username and password?

### ISSUE THREAD

**Issue by Misaka-blog** [alireza0/s-ui#39]
**Is your feature request related to a problem? Please describe.**
The plan for change panel default username and password for improve safety

**Additional context**
Please do it, otherwise the user who used this panel are so dangerous

**Comment by wxyttty** [comment]
Currently, you can modify the username and password in s-ui.db, which are stored in plain text.

**Comment by leic4u** [comment]
I forgot my s-ui panel password, how can I reset my password? 😅😅
