### ISSUE TITLE
Thank you very much for developing such a useful panel. Now there is a question, how to periodically clear the traffic to 0

### ISSUE THREAD

**Issue by hedsbj** [alireza0/s-ui#390]
see subject

**Comment by VortexRedDev** [comment]
client -> Edit client  -> Vulome , Expriy        ?

**Comment by hedsbj** [comment]
This means that the account will be deactivated after it expires. What I
want is to be like our mobile phone data package, which will be stopped
immediately after the monthly data is used up, and will start again next
month or cycle.

VortexRedDev ***@***.***> 于2024年12月18日周三 17:34写道：

**Comment by hedsbj** [comment]
There is another problem. If the user is not associated with any inbounds, the sing-box will stop working.

**Comment by alireza0** [comment]
Specific actions should be done by external app which could communicate with s-ui's api.
