### ISSUE TITLE
انتخاب پایگاه داده

### ISSUE THREAD

**Issue by r0zbeh** [alireza0/s-ui#392]
اگر امکانش باشه در بخش تنظیمات انتخاب کرد که از چه پایگاه داده ای استفاده بشه !وبشه Ip , port  پایگاه های اس کیو ال رو وارد کرد یا از پیشفرض استفاده کرد . 
و اینکه با این کار بشه چندین پنل رو به یک پایگاه داده وصل کرد که حالت Node بگیرن ! فکر کنم اینطوری کارایی پنل بیشتر بشه

**Comment by alireza0** [comment]
سیستم مولتی نود یه مدل تجاریه و احتمالا توی نسخه تجاری s-ui به زودی ارائه میشه.
هنوز برنامه اش رو نچیدم و مطمئن نیستم، ولی اصولا دیتابیسش دیگه اینقدر ساده نیست.
پنل ساده، فقط کاربرد شخصی داره.
