### ISSUE TITLE
نصب روی پردازنده‌های ARM

### ISSUE THREAD

**Issue by Nima786** [alireza0/s-ui#4]
سلام، لطفاً نصب روی سرورهایی با معماری ARM رو هم میسر کنید، من تست کردم عملیات نصب انجام میشه ولی پنل بالا نمیاد، احتمالا چون این معماری رو هنوز پشتیبانی نمیکنه.

**Comment by alireza0** [comment]
درود بر شما
اگر از linux/arm یا linux/arm64 استفاده میکنید، پشتیبانی میشه و راحت باید کار کنه.
لاگ سرویس s-ui و یا نتیجه اجرای دستی رو برای من بفرستید.
```bash
/usr/local/s-ui/sui
```

**Comment by Nima786** [comment]
سلام، متوجه نشدم دقیقا ، منظورتون اینه فایلی که در اون مسیر هست رو براتون بفرستم؟ چون یک فایل حجیم تقریباً نزدیک سی مگ هست .

**Comment by alireza0** [comment]
اون فایل همون فایلی هسته که از ریلیز دریافت میکنید.
لاگ سرویس رو از این دستور بگیرید:
```bash
journalctl -u s-ui
```

**Comment by Nima786** [comment]
ممنون، این اسکرین از لاگ هست.
![Uploading Screenshot_20240216-102344.png…]()

**Comment by alireza0** [comment]
سپاسگزارم از اطلاعاتتون
حتما بررسی میکنم

**Comment by payamss** [comment]
برای منم همینطور ،روی x64 نصب شد ولی روی آرم مشکل داره. لاگ همینه اول فکر کردم بخاطر اینه که رو داکر دارم نصب میکنم ولی دیدم نه مشکل مثل ایشون روی آرم هست

**Comment by alireza0** [comment]
در نسخه جدید این مشکل برطرف شده و شما میتونید از مدلهای مختلف پردازنده استفاده کنید.
