### ISSUE TITLE
tuic

### ISSUE THREAD

**Issue by mehdi7arfand10** [alireza0/s-ui#44]
سلام خسته نباشید
با پروتکل tuic کانفیگ میسازم و پینگ خیلی پایینی میگیرم ولی برام کار نمیکنه!! مثلا توی توییتر رفرش میشه ولی عکس و فیلم رو باز نمیکنه، همینطور اینستاگرام و یوتیوب..
میشه بفرمایید مشکل از کجاست؟

**Comment by alireza0** [comment]
درود بر شما
به شخصه داده های زیادی در این باره نداره.
بیشتر میتونه مشکل فیلترینگ باشه

**Comment by mehdi7arfand10** [comment]
> درود بر شما به شخصه داده های زیادی در این باره نداره. بیشتر میتونه مشکل فیلترینگ باشه

ممنون که جواب دادین🙏
میتونه مشکل از DNS باشه؟
اینستاگرام رو الان خوب باز میکنه ولی توییتر، یوتیوب و سایتها رو باز نمیکنه..
من از این پروتکل روی اسکریپت های دیگ دارم استفاده میکنم و خوب کار میکنه ولی میخوام از پنل شما استفاده کنم بخاطره اینکه از چندین پروتکل میشه استفاده کرد..
روی پروتکل های دیگه هم تست کردم به همین شکله، پینگ میده ولی چیزی رو باز نمیکنه..
برای استفاده شخصی میخوام ولی متأسفانه نتونستم اوکی کنم هنوز، اگ بتونین راهنماییم کنین عالی میشه

**Comment by mehdi7arfand10** [comment]
مشکل از dns توی برنامه بود استاد
سلامت باشید🙏
