### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sinaNJN** [alireza0/s-ui#49]
سلام - بعد از نصب ورژن جدید این مشکل رو در اجرا دارم.

[ERR] Failed to start s-ui, Probably because it takes longer than two seconds to start, Please check the log information later

پنل ران شده و استارته ولی فقط صفحه سفید میده چیزی نمیاد

**Comment by alireza0** [comment]
درود بر شما
برای ارسال گزارش باگ اول از اینکه این مشکل وجود دارد آگاه باشید.
پس از اون، با ارسال همه داده ها، و با دانش مناسب به بخشی که به درستی کار نمیکنه، ایراد رو اینجا بنویسید.
سپاسگزارم
