### ISSUE TITLE
Add a reality feature, it will be perfect

### ISSUE THREAD

**Issue by xgzxmytx** [alireza0/s-ui#50]

**Comment by alireza0** [comment]
Some parts of this panel is not implemented yet.
It will be completed step by step.

**Comment by leic4u** [comment]
Looking forward to it.

**Comment by 8MiYile** [comment]
@alireza0 Can't wait to use this feature, of course it would be nice if the interface looked like the 3x-ui project!

**Comment by alireza0** [comment]
It is already implemented
