### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by Rulio723** [alireza0/s-ui#51]
May I ask if it is possible to add an insurance option on the Hystereria2 inbound option

**Comment by alireza0** [comment]
What is insurance?

**Comment by Rulio723** [comment]
![image](https://github.com/alireza0/s-ui/assets/61340513/3b734a04-e56c-4ae3-b4c0-f6dc3e453e68)

**Comment by alireza0** [comment]
It is about client parameter which should be configured in client app.
Client side configurations is not implemented yet in this app.

P.S. Due to security reasons some client will not accept it via link

**Comment by Rulio723** [comment]
ok
