### ISSUE TITLE
Outbounds and rules sections are not editable

### ISSUE THREAD

**Issue by m2tts2001** [alireza0/s-ui#52]
Outbound and rule sections are not editable. They are just pages without any buttons.

**Comment by alireza0** [comment]
It is not implemented yet. But you can change them in json file in /usr/local/s-ui/bin/config.json

**Comment by xgzxmytx** [comment]
Do you have a Telegram group

**Comment by alireza0** [comment]
No! I have no time to manage it

**Comment by alireza0** [comment]
It is already implemented
