### ISSUE TITLE
The panel doesn't load in the browser after installation

### ISSUE THREAD

**Issue by nima1300** [alireza0/s-ui#53]

**Comment by ycq0431** [comment]
When I upgraded from version 0.0.1 to the latest version, the panel will not load in the browser. Just install version 0.01. what happened?

**Comment by alireza0** [comment]
Did you try to use default path?
/app/ ?

**Comment by zhisibi** [comment]
me too

**Comment by zhisibi** [comment]
the new url is :
http://Ip:2095/app
