### ISSUE TITLE
direct access to sing-box core config

### ISSUE THREAD

**Issue by gorbesiah** [alireza0/s-ui#54]
سلام
اول ممنونم ازت بابت این پنل کاربردی و جذاب و امیدوارم سریعتر از مراحل آزمایشی رد بشه و به نسخه های پایدار و کاربردی برسه.
اگر مثل پنل x-ui امکان ویرایش خود کانفیگ هسته سینگ باکس باشه خیلی عالی میشه.
و اینکه مسیر سایر فایل‌های کانفیگ هم در لاگ یا در منو مشخص باشه جالب میشه.

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم
با توجه به وقتی که باید بگذاریم، کم کم بخش ها اضافه میشه.
خوبی این پنل اینه که میتونید به صورت دستی، بخش های مختلف کانفیگ سینگباکس رو تغییر بدید.
به جز بخش users از inbounds، بقیه بخش ها سرجاشون میمونن.
فایل رو میتونید در آدرس زیر ببینید و تغییر بدید:

```bash
/usr/local/s-ui/bin/config.json
```

**Comment by gorbesiah** [comment]
خیلی عالیه، ممنونم واقعا
برای هسته hysteria2 هم میتونیم تنظیمات دلخواه رو دستی وارد کنیم؟ 
و برای وارپ روی hysteria2 ظاهرا باید از socks5 استفاده کرد، تداخلی با سایر کانفیگ‌ها نداره؟

**Comment by alireza0** [comment]
> برای هسته hysteria2 هم میتونیم تنظیمات دلخواه رو دستی وارد کنیم؟

بله. ولی اگر تنظیمی هست که به درد همه میخوره، بفرمایید که من بتونم برای همه فعالش کنم.


> و برای وارپ روی hysteria2 ظاهرا باید از socks5 استفاده کرد، تداخلی با سایر کانفیگ‌ها نداره؟

متوجه نشدم ربط این سه تا با هم چیه!

**Comment by gorbesiah** [comment]
> بله. ولی اگر تنظیمی هست که به درد همه میخوره، بفرمایید که من بتونم برای همه فعالش کنم.
در حال تست و بررسی هستم ولی یه قابلیت خوب، فعال کردن بلاک آدرس‌های داخل ایران با خود خسته هیستریاست که تو داکیومنت های این لینک آورده 
https://github.com/bootmortis/iran-hosted-domains/blob/main/README.fa.md


> متوجه نشدم ربط این سه تا با هم چیه!
وقتی از هسته Hyseria (هیستریا) استفاده میکنیم برای استفاده از وبسایت‌های Ai (هوش مصنوعی) و برخی وبسایت ها مثل گوگل و توییتر نیاز به WARP (وارپ) هست. اینطور که فهمیدم دوتا راه هست برای انجامش. 
اول اینکه چون هیستریا از Wireguard (وایرگارد) پشتیبانی نمیکنه با socks5 (ساکس) به وارپ وصلش کنیم یا
حالت دوم که دوباره با socks کل ترافیک رو به هسته sing-box (سینگ-باکس) یا هسته x-ray (ایکس-ری) انتقال بدیم و بعد با routing (روتینگ) توی این هسته‌ها ترافیک رو مدیریت کنیم و از وارپ با هسته وایرگارد یا حالت دیگه استفاده کنیم.

**Comment by gorbesiah** [comment]
اینطور که من متوجه شدم شما دیگه هسته خود هیستریا رو نصب نمیکنید و مستقیما از خود کانفیگ singbox (سینگ باکس) استفاده میکنید.
امکانی هست که بتونیم هسته hysteria2 (هیستریا) رو نصب کنیم و مدیریت کاربران رو به پنل بسپاریم؟

**Comment by alireza0** [comment]
همه جای این رپو نوشته شده که این پنل یک پوسته گرافیکی برای سینگ-باکس هست.
پس قرار نیست هسته دیگه ای اضافه بشه و به محدودیت ها و توانایی های همین هسته محدود میشه.
