### ISSUE TITLE
connection refuse 

### ISSUE THREAD

**Issue by mohamadm0meni** [alireza0/s-ui#55]
سلام استاد 
کانفیگ ساختم ولی وقتی میخوام ازش استفاده کنم ارور connetction refuse  میدهد 
راه حل چیست ؟
فایروال هم چک کردم خاموش بود مشکلی از این بابت نداشت

**Comment by mohamadm0meni** [comment]
![photo_2024-03-03_21-36-05](https://github.com/alireza0/s-ui/assets/77540335/144cc3ae-ccdf-4805-908e-ad6f20141df
 کانفیگ tuic

**Comment by mohamadm0meni** [comment]
![photo_2024-03-03_21-36-05](https://github.com/alireza0/s-ui/assets/77540335/a9ac2e30-bb42-4be0-aa83-3bde3dd32b97)
کانفیگ توییک هست

**Comment by mohamadm0meni** [comment]
![image](https://github.com/alireza0/s-ui/assets/77540335/c8aa817b-4229-4b2a-9bea-bb79a8930c2c)

**Comment by alireza0** [comment]
با این تنظیم هسته سینگ باکس رو هم از کار انداختید.
در سینگباکس، برای توییک، استفاده از tls اجباریه و شما تنظیم نکردین!
لطفا در صورت وجود مشکل، لاگ سینگباکس و نوع نرم افزار کلاینت رو هم بفرمایید

**Comment by nima1300** [comment]
به چه صورتی بایستی TLS رو فعال کنم؟

**Comment by alireza0** [comment]
به صورت پیشفرض فعال هست. فقط باید آدرس درست فایل گواهی ها رو وارد کنید.

**Comment by nima1300** [comment]
خیلی ممنون ، چند پست قبل دیدم که my.cert و my.key رو وارد کردید ، همین هست ؟ یا چیز دیگه ای باید وارد کنم؟

**Comment by alireza0** [comment]
آدرس فایل در سرور شما باید باشه. این داده هایی که گفتین تنها برای نمونه است.

**Comment by nima1300** [comment]
ممنون ، در Ubuntu 20 توی کدوم فولدر ساخته می شود؟

**Comment by mohamadm0meni** [comment]
![image](https://github.com/alireza0/s-ui/assets/77540335/4d0411a4-6283-436d-9b4f-2ae8ec9537a6)
استاد اگر ممکنه یک فرمول پیشنهادی بهمون برای ساختن کانفیگ tuic بدین بازم tls گرفتم ولی کار نمیکنه 
روی ubuntu 22.04  hetzner هست

**Comment by mohamadm0meni** [comment]
![image](https://github.com/alireza0/s-ui/assets/77540335/2e6fa08d-076d-49bc-a25a-d61761ccfda5)
@alireza0

**Comment by mohamadm0meni** [comment]
> با این تنظیم هسته سینگ باکس رو هم از کار انداختید. در سینگباکس، برای توییک، استفاده از tls اجباریه و شما تنظیم نکردین! لطفا در صورت وجود مشکل، لاگ سینگباکس و نوع نرم افزار کلاینت رو هم بفرمایید

برنامه nekobox بود 
![image](https://github.com/alireza0/s-ui/assets/77540335/806c6b5d-d409-4787-b5fa-04a8f3f9bf0a)
![image](https://github.com/alireza0/s-ui/assets/77540335/90759de7-ba91-4eea-be0a-8c9b7e3a0a70)

**Comment by alireza0** [comment]
نمیدونم چرا این تنظیمات رو به این شکل انجام دادین ولی نتیجه نشون میده که شاید دلیلش رو نمیدونید.
۱. اگر از cipherSuites استفاده نمیکنید، حتما غیر فعالش کنید. حالت اتوماتیک روی خیلی از پروتکل ها باعث خطا میشه. احتمالا در نسخه بعد حالت اتوماتیک رو برمیدارم.
۲. باز گذاشتن تنظیماتی که استفاده نمیکنید اکیدا توصیه نمیشه. حتما اونها رو غیر فعال کنید. در مثال شما بخش listen همه مواردش فعاله ولی فقط از استراتژی dns استفاده کردین.
۳. دلیل اینکه توی sni دامنه متفاوتی دادین چیه ؟ این کار مشکل ایجاد میکنه و باید سمت کاربر از allow insecure استفاده کنید. هم توصیه نمیشه و هم مشکلات امنیتی داره.
درستش اینه که یا sni نداشته باشید و یا دقیقا معادل اون چیزی باشه که براش گواهی گرفتین.

در مورد اینکه چی جواب میده و چی مشکل داره باید اجازه بدیم دوستانی که تست میگیرن در شرایط مختلف نتایج رو اعلام کنن.
