### ISSUE TITLE
docker install s-ui

### ISSUE THREAD

**Issue by wstxwd007** [alireza0/s-ui#58]
WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"

**Comment by wstxwd007** [comment]
OK,thanks.

**Comment by RayWangQvQ** [comment]
same issue

**Comment by cainiao-123** [comment]
Same

**Comment by alireza0** [comment]
It is already fixed

**Comment by mxyhi** [comment]
WARNING - Get stats failed:  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:1080: connect: connection refused"
still have
