### ISSUE TITLE
Admin Dashboard: Add Search to Clients Tab

### ISSUE THREAD

**Issue by ErfanTech** [alireza0/s-ui#6]
The client tab in the admin dashboard lacks a search feature. This makes it difficult for admins to quickly find specific clients.

Feature Request Details:
1. **Search Bar**: Add a simple search bar to the client tab.
   
2. **Filtering**: Allow filtering by client attributes like name or ID.
   
3. **Real-Time Results**: Display search results instantly as admins type.
   
4. **Easy to Use**: Keep the search feature simple and intuitive.

Adding this search functionality will make it easier for admins to manage clients efficiently.

**Comment by alireza0** [comment]
To be clear, it is not designed for huge number of clients as far as I know about problems may happens in this situations.
Let time passed to see if needed.

BTW: All the informations are provided in eash tile. IMHO using Ctrl+F is enough now.

**Comment by alireza0** [comment]
Please keep the issue open to check it in proper time.
The `low periority` tag is for considering in proper time.
Thank you

**Comment by ErfanTech** [comment]
Understood, i'll keep the issue open for further evaluation.

**Comment by ErfanTech** [comment]
> .
![Screenshot (905)](https://github.com/alireza0/s-ui/assets/108360299/ccb89e71-486b-4c94-acea-8635aef0784e)
