### ISSUE TITLE
بستن آیپی و دامنه ی ایران

### ISSUE THREAD

**Issue by mehdi7arfand10** [alireza0/s-ui#60]
درود استاد خسته نباشید
میخواستم ببینم در حال حاضر آیا راه حلی هست که بشه دامنه و آیپی ایران رو ببندم؟

**Comment by mehdi7arfand10** [comment]
> درود بر شما اگر با تنظیم فایل جیسون برای سینگ باکس آشنایی دارید میتونید به صورت دستی توی فایلش اضافه کنید. یکی از مزیت های این پنل اینه که تغییرات مستقیم از این فایل خونده و در اون ذخیره میشه. تنها بخشی که نمیتونید تغییر بدید و اتوماتیک باید انجام بشه، در حال حاضر فقط بخش کاربران هر ورودی است.

اگه لطف کنید بگین کدوم فایل رو باید ادیت بزنم باقیش رو انجام میدم، از json پنل x-ui کمک میگیرم در کنار chatgpt😁
دم شما گرم واقعا♥️♥️

**Comment by mehdi7arfand10** [comment]
> درود بر شما اگر با تنظیم فایل جیسون برای سینگ باکس آشنایی دارید میتونید به صورت دستی توی فایلش اضافه کنید. یکی از مزیت های این پنل اینه که تغییرات مستقیم از این فایل خونده و در اون ذخیره میشه. تنها بخشی که نمیتونید تغییر بدید و اتوماتیک باید انجام بشه، در حال حاضر فقط بخش کاربران هر ورودی است.

![IMG_20240305_013348](https://github.com/alireza0/s-ui/assets/132158452/fe73a900-4ecd-4582-8876-491a9a2499a5)
قسمت route rules باید اضافه کنم، درسته؟

**Comment by alireza0** [comment]
بله
ولی روشش با xray فرق داره. به اسناد خود سینگ باکس مراجعه کنید

**Comment by mehdi7arfand10** [comment]
> بله ولی روشش با xray فرق داره. به اسناد خود سینگ باکس مراجعه کنید

متاسفانه موفق نشدم درستش کنم، اگه زحمتی نیست براتون میشه کد قسمت route رو برام بفرستین که جایگزینش کنم🙏
خانوادم استفاده میکنن و با سرور میرن توی سایت و برنامه های ایرانی، برای همین خیلی مهمه برام که اینو درست کنم

**Comment by generalkeen** [comment]
> > بله ولی روشش با xray فرق داره. به اسناد خود سینگ باکس مراجعه کنید
> 
> متاسفانه موفق نشدم درستش کنم، اگه زحمتی نیست براتون میشه کد قسمت route رو برام بفرستین که جایگزینش کنم🙏 خانوادم استفاده میکنن و با سرور میرن توی سایت و برنامه های ایرانی، برای همین خیلی مهمه برام که اینو درست کنم

درود بر شما. من تخصصی توی این زمینه ندارم اما یه پیشنهاد دارم براتون. از وارپ توی اوتباند استفاده کنید. با وارپ نگرانی‌ای برای این موضوعی که فرمودید نخواهید داشت. من در حال حاضر دارم از X-UI استفاده میکنم و روی اوتباند وارپ رو ست کردم و خیالم از این بابت راحته.
