### ISSUE TITLE
نحوه ایجاد کانفیگ

### ISSUE THREAD

**Issue by Aramousa** [alireza0/s-ui#65]
ممنون از لطف شما . امیدوارم موفق باشید.
من بروی سرورم نصب کردم . اما چطور میتونم کانفیگ ها رو بسازم ؟. دقیقا نمیدونم تنظیمات بایستی چی باشند ؟ آیا منبعی دارید که بتونم از روی اون Inbounds ها رو بسازم ؟
ممنون میشم اگر راهنمایی کنید .
همینطور اگر بتونم نحوه پیاده سازی رو یاد بگیرم میتونم در مستند کردن پروژه هم کمک کنم .
زنده و پاینده باشی آقا

**Comment by amirmbi** [comment]
سلام دوست عزیز  @Aramousa 

علیرضا این پنل را بر هسته سینگ باکس نوشته شده است. به طور خلاصه شما ابتدا INBOUND ایجاد می کنی و بعدش هر کدام از این INBOUND ها را به یک یوزر خاص می تونی متصل کنید که با لینک سابکریپش بر روی نرم افزار NEKOBOX کار می کنند. 

این هم یک ویدیو یوتیوب از ایمان:

https://youtu.be/Vwg5OOI8J_w?si=3gwOy2UBqPbbkmj_

**Comment by Aramousa** [comment]
> سلام دوست عزیز @Aramousa
> 
> علیرضا این پنل را بر هسته سینگ باکس نوشته شده است. به طور خلاصه شما ابتدا INBOUND ایجاد می کنی و بعدش هر کدام از این INBOUND ها را به یک یوزر خاص می تونی متصل کنید که با لینک سابکریپش بر روی نرم افزار NEKOBOX کار می کنند.
> 
> این هم یک ویدیو یوتیوب از ایمان:
> 
> https://youtu.be/Vwg5OOI8J_w?si=3gwOy2UBqPbbkmj_

من دقیقا همین کارها رو میکنم . بعد از اضافه کردن این کانفیگ ها روی نرم افزار  Fair هیچ کدوم از کانفیگها کار نمیکنه.
لازم به ذکره که من سرورم رو روی کلادفلر پروکسی کردم تا IP سرورم  از بیرون دیده نشه و با نام دامنه به پنلم وصل شدم .

**Comment by amirmbi** [comment]
دوست عزیز 

گوشی شما آندورید هست یا آیفون. در مورد آیفون حتما از NEKOBOX استفاده کنید. 

از لینک زیر NEKOBOX را دانلود کنید:
https://github.com/Matsuridayo/NekoBoxForAndroid/releases

برای گوشی آیفون هم نرم افزار Streisand: 
https://apps.apple.com/us/app/streisand/id6450534064

اگه میشه توضیح بدید چه نوع کانفیگی می سازید که کار نمی کنه ؟

همچنین علرضا عزیز می فرمایند که قدم به قدم که کانفیگ ایجاد می کنید وضعیت هسته SING-BOX رو چک کنید، دستورات زیر:

systemctl status sing-box
journalctl -u sing-box

**Comment by roozbehalamdari** [comment]
> دوست عزیز
> 
> گوشی شما اندورید هست یا آیفون. در مورد اندروید حتما از NEKOBOX استفاده کنید.
> 
> از لینک زیر NEKOBOX را دانلود کنید: https://github.com/Matsuridayo/NekoBoxForAndroid/releases
> 
> برای گوشی آیفون هم نرم افزار Streisand: https://apps.apple.com/us/app/streisand/id6450534064
> 
> اگه میشه توضیح بدید چه نوع کانفیگی می سازید که کار نمی کنه ؟
> 
> همچنین علرضا عزیز می فرمایند که قدم به قدم که کانفیگ ایجاد می کنید وضعیت هسته SING-BOX رو چک کنید، دستورات زیر:
> 
> systemctl status sing-box journalctl -u sing-box

درود خوبین ؟ برای هیستریا روی اندورید با Fake DNS توی خود برنامه اکی میشه بدون مشکل ، ولی آیفون متاسفانه اینستا و واتس اپ همش لودینگ میزنه و هیچی باز نمیشه ، DNS هم براش گذاشتم توی خود Streisand ولی جواب نمیده راه حلتون چیه  ؟

**Comment by mojairio** [comment]
سلام
کانفیگهایی که روی پنل ۱.۳۷ میسازم فقط روی ورژن های خاصی از سینگباکس اندروید اجرا متصل میشه، مشکل از کجاست؟
