### ISSUE TITLE
docker bug

### ISSUE THREAD

**Issue by Hmdrf** [alireza0/s-ui#66]
**Describe the bug**
سلام وقتی با داکر نصب می کنم هسته سینگ باکس ران نمی شه 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alireza0** [comment]
خود پنل در حال حاضر در مرحله تست هست و داکر هم بیشتر برای تست بکار میره.
اگر میتونید با یک docker-compose مناسب این بخش ها رو به هم متصل کنید میتونید برای خودتون استفاده کنید.
در غیر اینصورت باید منتظر تغییراتی باشید که هنوز به دلیل رفع نشدن وابستگی ها در حالت انتظار هستند.
بعد از برطرف شدن وابستگی ها میشه یک راه حل کامل براش ارائه کرد.
