### ISSUE TITLE
چرا داده‌های سینگ‌باکس اجرا خیر هست برای من‌

### ISSUE THREAD

**Issue by uzer0098** [alireza0/s-ui#67]
چرا داده‌های سینگ‌باکس اجرا خیر هست برای من‌

![5656565](https://github.com/alireza0/s-ui/assets/88993534/9fc12069-55e2-4f20-952a-df66f7c02235)

این خطا تو لاگ ها دلیلش چیه؟
![IMG_6053](https://github.com/alireza0/s-ui/assets/88993534/44708b9b-9370-4ab8-a066-de6aee624d93)

**Comment by alireza0** [comment]
آخرین خط خطایی که ارسال کردین توضیح مشکل شماست.
اینباند اولی که درست کردین، بخش گواهی براش تنظیم نشده.

**Comment by uzer98** [comment]
چرا برای توییک تو اسکریپتی که ساختین نیاز به دامین و گواهی ssl هست اما تو اسکریپت های دیگه که توییک میشه ساخت(البته بصورت تک یوزر) نیاز به گواهی ssl و دامین نیست؟

**Comment by alireza0** [comment]
این نیاز توسط sing-box به صورت کلی گذاشته شده و در صورتی که رعایت نشه، کل هسته از کار میافته.

**Comment by PesareIran250** [comment]
من با پنل s-ui اومدم vless معمولی ساختم بازم برام کار نمیکنه

**Comment by PesareIran250** [comment]
و این خطا تو لاگ s-ui دارم
![error-sui](https://github.com/alireza0/s-ui/assets/114500209/93578e34-ee98-41c7-88fa-e6d698bd6466)

**Comment by alireza0** [comment]
در این لاگها خطایی مرتبط با اینباند وجود نداره
