### ISSUE TITLE
امکاناتی برای بهبود اسکریپت

### ISSUE THREAD

**Issue by uzer98** [alireza0/s-ui#69]
یکسری امکانات اگه در اپدیت های اینده اضافه کنید خوبه

۱- امکان بکاپ و ریستور دیتابیس
۲- امکان بکاپ و ریستور اینباندها و یوزرها
۳- امکان بستن کانفیگ ها روی ای پی و دامین ایران،چین، روس و ...
۴- امکان بستن نمایش  تبلیغات یوتیوب برای کانفیگ ها
۵- امکان بستن تورنت و seppdtest
۶- امکان روتینگ برای اینباندها یا یوزرهای خاص
۷- امکان دریافت گزارشات در ربات تلگرامی (مصرف یوزر و ...)

**Comment by alireza0** [comment]
اجازه بدید دوره تست تمام بشه و کلاینت ها این پروتکل ها رو ساپورت کنند، کم کم همه موارد اضافه میشه.

**Comment by alireza0** [comment]
بعضی از این امکانات اضافه شده و بعضی هم در لیست اجرا هستند
