### ISSUE TITLE
please support websocket in shadowsocks

### ISSUE THREAD

**Issue by ydqsbfsyi** [alireza0/s-ui#70]
Please support 'websocket' network in shadowsocks, which at least includes 'type' and 'path' options.

**Comment by alireza0** [comment]
Shadowsocks in Sing-box does not support transmision.
[Ref](https://sing-box.sagernet.org/configuration/inbound/shadowsocks/)

**Comment by ydqsbfsyi** [comment]
> Shadowsocks in Sing-box does not support transmision. [Ref](https://sing-box.sagernet.org/configuration/inbound/shadowsocks/)

Thank you.
