### ISSUE TITLE
اجرا نمیشه

### ISSUE THREAD

**Issue by ali6344** [alireza0/s-ui#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

سلام
بعد از نصب وقتی میخوام وارد پنل شم اجرا نمیشه

**Comment by alireza0** [comment]
https://github.com/alireza0/s-ui/issues/74#issuecomment-1996012159

**Comment by ali6344** [comment]
یله ممنونم
فقط مشگل اینجاس اپ وقتی گانگت میزنم فیلد میشه

[https://cdn.discordapp.com/attachments/556063419501903883/1218579078722879608/Screenshot_20240316-184659_v2rayNG.jpg?ex=66082d34&is=65f5b834&hm=50ef43dfb529df0f4dd4cd68e36abb399de4f511cb18c912d601495f82e2b531&](url)

**Comment by ali6344** [comment]
https://cdn.discordapp.com/attachments/556063419501903883/1218579078722879608/Screenshot_20240316-184659_v2rayNG.jpg?ex=66082d34&is=65f5b834&hm=50ef43dfb529df0f4dd4cd68e36abb399de4f511cb18c912d601495f82e2b531&

**Comment by alireza0** [comment]
داده های شما برای بررسی خیلی کمه
