### ISSUE TITLE
white 

### ISSUE THREAD

**Issue by sinaNJN** [alireza0/s-ui#74]
سلام.
بعد نصب - حتی پورت های دیگ هم زدم میخوام وارد پنل بشم فقط صفح
ه سفید میاد 
علت چیه؟

**Comment by alireza0** [comment]
درود بر شما
علتش اصلیش اینه که
۱. به پرسش ها و داده های زمان نصب دقت نکردین
۲. توی ایشو ها سوالات جواب داده شده رو بررسی نکردین
۳. به مشخصات نسخه دقت نکردین

جواب شما اینه که باید مسیر ( پیشفرض /app/ تنظیم شده ) رو هم توی مرورگر بزنید.
