### ISSUE TITLE
Sing-box subscription config

### ISSUE THREAD

**Issue by gorbesiah** [alireza0/s-ui#79]
سلام علیرضا جان
ممنون بابت زحماتی که کشیدی و این پنل فوق‌العاده رو راه‌اندازی کردی🙏
اگر امکانی باشه که پنل به صورت پیش فرض کانفیگ سابسکریپشن(subscription) سینگ-باکس (sing-box) تولید کنه امکانات خیلی بیشتری برای مدیریت این باندها بهمون میده.
از مدیریت اتصال به کانفیگ‌ها به صورت اتوماتیک تا تنظیم مسیردهی درخواست‌ها.

ممنون🙏

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی و پیشنهاد شما

پیش از اینکه این ویژگی افزوده بشه، باید بخش های خروجی و مسیریابی آماده بشه.
بسیاری از ویژگی هایی که انجام نشده، نیازمند زمان و پیشرفت نرم افزار های کلاینته.

**Comment by alireza0** [comment]
این ویژگی اضافه شده و در نسخه بعد قابل استفاده خواهد بود.
