### ISSUE TITLE
Add or how to enable the port hopping feature for the hysteria2 protocol.

### ISSUE THREAD

**Issue by 2363476152** [alireza0/s-ui#81]
“Can the port hopping feature of the Hysteria2 protocol be added? Or if the s-ui panel already has this feature, how can it be activated?

**Comment by alireza0** [comment]
Hysteria2 is supported by Sing-Box and could be added in inbounds page.
The only difference is that it is mandatory to define TLS.

**Comment by leic4u** [comment]
I guess that s-ui couldn't listen on multi ports.

So maybe you should enable the port hopping with iptables.

Just like the usage provided in [hysteria2 docs](https://v2.hysteria.network/docs/advanced/Port-Hopping/#server).
