### ISSUE TITLE
حذف نشدن inboundهای حذف شده از کاربران

### ISSUE THREAD

**Issue by amooerfan** [alireza0/s-ui#85]
۱. در قسمت اینباند‌ها چند اینباند ایجاد کردم و در کاربران به هر کاربر اختصاص دادم.
بعد از حذف کردن اینباندها همچنان در کاربر ایجاد شده اینباند‌ها قبلی وجود دارد و امکان حذف کردن آن نیست. (مثال تصویر: اینباند vmess امکان حذف شدن از کاربر را ندارد در حالی که دیگر چنین اینباندی وجود ندارد.)
اما QrCode آن‌ را نشان نمی‌دهد.

۲.در قسمت کاربران چند یوزر ساختم و نمیدانم با انجام دادن چه کاری ناگهان از هر کاربر چند کاربر تکراری با همان نام‌ها ایجاد شد که به صورت دستی تک به تک حذف شدند.

![Screenshot 2024-03-22 105334](https://github.com/alireza0/s-ui/assets/23645580/0716a92a-4a13-4313-8468-5aa50b66e8ec)

**Comment by alireza0** [comment]
۱. به صورت نرمال باید با حذف اینباند، از همه کاربران باید حذف بشه. لطفا شرایط تست خودتون رو بفرمایید ( مروگر، خطای کنسول، نوع کانفیگ و ... )
۲. به صورت نرمال، با هر کلیک برای اضافه کردن کاربر باید فقط یک کاربر ایجاد بشه.

روال چک کردن کاربر برای عدم ایجاد کاربر مشابه وجود نداره، سعی میکنم اضافه کنم.

**Comment by alireza0** [comment]
مشکلات برطرف شدند و در نسخه بعد اعمال میشوند.
