### ISSUE TITLE
فیدبک کلی

### ISSUE THREAD

**Issue by oneoneishere** [alireza0/s-ui#86]
ضمن تشکر مجدد از بابت تمام زحماتی که کشیدید و میکشید، بعد از استفاده مداوم طی این چند وقت اخیر خواستم یه فیدبک کلی بدم

از خیلی جهات راضیم از پنل مخصوصا به خاطر امکان مدیریت اکانتها به صورت سابسکریپشن و کاربر محور بودن عالیه، نقصی که  روی ایکس یو آی به شدت اذیت کننده است ولی اینجا رفع شده

چند مورد هم برای بهبود عرض کنم:

۱) بعضی مواقع علیرغم تنظیم آدرس مجزای سابسکریپشن موقع کپی لینک سابسکریپشن همچنان آدرس خود پنل رو برمیداره، البته همیشه نیست

۲) یه مورد فوق‌العاده در مورد نسخه های اخیر ایکس‌یو‌آی که هست، بخش اکسترنال پراکسیه که به شدت کاربردی هست، برای وقتی ریورس پراکسی میذاریم، روی این پنل هم به شدت احساس نیاز کردم، خیلی ممنون میشم اگر جزو اولویتهای بالا قراره بگیره برای افزودن در آپدیتهای  بعدی، مخصوصا که این پنل جایی برای وارد کردن آدرس سرور نداره و اونو اتومات برمیداره

۳) از نظر من بعضی جاها مبهمه مثلا همین بخش آدرس در ساخت اینباکس ها، به جای listen to  نوشته شده آدرس، باتوجه به جدید بودن پنل و نبود داکیومنت های کافی، اوایل باعث سردرگمی و بروز مشکلات میشد برام، فکر میکنم بقیه کاربران هم چنین مشکلاتی رو تجربه کنن

۴)وقتی تم پنل رو دارک میکنیم دکمه های تقویم محو میشن، یعنی رنگشون متناسب با تم کلی تغییر نمیکنه و قابل تشخیص نیست، نوشته های دکمه ها فقط با تم روشن قابل تشخیص هست

۵) یه موردی که هم ایکس‌یو‌آی داره هم این پنل اینه که موقع ساخت و ویرایش کاربر قبل از ذخیره نهایی تعداد روزها مشخص نیست، بعد از سیو مشخص میشه چند روز تنظیم شده، ای کاش اون تعدادی که بعد از ذخیره نمایش داده میشه به محض انتخاب تو همون پنجره تنظیمات کاربر نمایش داده بشه تا کم و زیادش قابل تنظیم باشه، یا اینکه مثل ربات تلگرامی ایکس‌یو‌آی امکان افزودن ۱ ماه و ۳ ماه و ..‌ باشه تا راحت بشه تنظیم کرد، یا هردو، در هر حال با تقویم صرف کمی سخته

۶) امکان بکاپ گیری از فایلها و تنظیمات پنل و همچنین ربات تلگرامی رو برای این پنل نمیدونم کی اضافه میکنید ولی به شدت و مشتاقانه منتظرش هستم

۷) نمیدونم در برنامه دارید یا نه ولی اگر در آینده امکان اضافه کردن نود هم باشه که دیگه محشر میشه😍

۸) یه موردی هم دیدم نمیدونم دقیقا به چی مربوط میشه، حدس خودم به هسته میره، من روی هسته خود هیستریا۲ سرور کانفیگ کردم خیلی روان و عالی کار میکنه فقط حیف امکان مدیریت کاربران خیلی ضعیفه و امکان مدیریت حجم وجود نداره، روی این پنل اون دو مورد رفع شده، ولی علیرغم پینگ پایین روی هیستریا۲، عملکردش چندان خوب نیست، من که خیلی ضعیفتر از سرور هیستریا۲ با هسته خود هیستریا دیدم

۹) امکان تنظیم وارپ هم که مثل ایکس‌یو‌آی اضافه بشه اونم عالی میشه، که به احتمال زیاد توی برنامه دارید🙏

۱۰) یه امکان خیلی خوبی که ایکس‌یو‌آی داره نمایش میزان کل ترافیک مصرفی توسط سرور هست، اونم روی این اضافه بشه خیلی خوب میشه

۱۱) نمیدونم این طبیعیه یا نه ولی با انجام برخی تغییرات هسته سینگ‌باکس از کار میفته، از جمله فعال کردن UDP Options

**Comment by alireza0** [comment]
درود بر شما
سپاسگزارم از همراهی شما

اینجا به ترتیب به موارد جواب میدم:
۱. بعضی مواقع برای من شفاف نیست و نمیتونم اون مواقعی که برای شما رخ میده رو بدون ارائه مدارک لازم پیدا کنم!
۲. درنسخه هایی که الان به شکل تست گذاشتم، هدف حرکت بازار به سمت هسته جدید و پشتیبانی از اونه. خدمات اضافی برای راحت کردن یک سری تنظیمات خیلی در این مرحله اولویت نداره.
۳. یکی از مواردی که باید حتما در نظر بگیرید اینه که چون پنل دیگه ای اینجوری نوشته نباید حتما این پنل هم همینحوری بنویسه! باید بدونین که از پایه یه نرم افزار متفاوت نوشته شده.
۴. بله این باگ رو خودم هم دیدم و مربوط به افزونه تاریخ میشه و در زمان مناسب باید روش کار کنم.
۵. بازگشت به پاسخ شماره ۲
۶. بازگشت به پاسخ شماره ۲
۷. هدف هر دو پنل x-ui و s-ui استفاده در یک سرور بوده و تمرکز روی تنوع تنظیمات و درست کار کردن سروره. بهتره برای اون کار از نرم افزار دیگری استفاده بشه که اگر وقت بشه میشه توی پروژه متفاوت انجام بشه
۸. نحوه کار و تنظیم سینگ باکس با هسته های اصلی کمی متفاوته و خوبی ها و بدی های خودش رو داره. با روش سعی و خطا باید بهترین روش رو ایجاد کنید.
۹. بازگشت به پاسخ شماره ۲
۱۰. بازگشت به پاسخ شماره ۲
۱۱. این یک باگه که درست شده و توی نسخه بعد حل میشه.

هنوز تا کلاینت ها این امکانات رو پشتیبانی کنند راه زیادی داریم و نمیشه گفت که بهینه سازی به چه سمتی پیش بره.
کم کم با پیشرفت نرم افزارهای سمت کاربر میتونیم گزارش های بیشتری داشته باشیم و بر پایه تجربه کاربرها، روی ویژگی های جدید کار کنیم.
