### ISSUE TITLE
WAITING FOR NEW VERSION

### ISSUE THREAD

**Issue by josbu** [alireza0/s-ui#87]
WAITING FOR NEW VERSION

**Comment by alireza0** [comment]
What do you need from new version?!
There are not enough changes to be ready for new release.

**Comment by drzazi** [comment]
> What do you need from new version?! There are not enough changes to be ready for new release.

Hi, it will be better to support reality.

**Comment by josbu** [comment]
want import the ssl path from the panel just one click

**Comment by alireza0** [comment]
In the last version you can find TLS menu for this request
