### ISSUE TITLE
will s-ui support multiple node mode?

### ISSUE THREAD

**Issue by zhimiaoli** [alireza0/s-ui#91]
**Is your feature request related to a problem? Please describe.**
some other application like v2board or sspanel ,can manage multiple nodes, will s-ui consider add this feature?

s-ui is far better than x-ui ,and has great potential, thanks for providing this nice software.

**Comment by alireza0** [comment]
Thank you for your good words.
So far, it supports using other panel's links and subscriptions only.
Using node needs fixed configuration which is not the goal of s-ui/x-ui.
BTW, it is in starting phase and needs more time to find out what could be useful for users.
