### ISSUE TITLE
Subdomain with number character

### ISSUE THREAD

**Issue by gorbesiah** [alireza0/s-ui#93]
برای ساخت هیستریا ساب دامنه‌هایی که شامل کارکتر شماره هستند باعث ایجاد این ارور میشن:

```
Mar 30 11:04:23 ip-172-26-4-137 runSingbox.sh[17397]: FATAL[0000] decode config at config.json: inbounds[0].listen: ParseAddr("se7en.EXAMPLE.COM"): unexpected character (at "se7en.EXAMPLE.COM")
```

**Comment by alireza0** [comment]
توی فیلد listen فقط ip سرور قرار میگیره و نه دامنه.
اگر خالی باشه روی همه ip های سرور اجرا میشه

**Comment by gorbesiah** [comment]
> توی فیلد listen فقط ip سرور قرار میگیره و نه دامنه. اگر خالی باشه روی همه ip های سرور اجرا میشه

کاملا  درست میگی علیرضا جان
اینطور که من ازت سوال پرسیدم تو چنتا ایشو دیگه و ایشوهای دیگه رو خوندم مشکل اکثر دوستان آشنا نبودن به خود هسته سینگ‌باکس هست نه پنل.
به هرصورت ازت ممنونم بابت وقتی که میزاری و توضیح میدی.
