### ISSUE TITLE
دایرکت شدن به 10.10.34.35 در هیستریا

### ISSUE THREAD

**Issue by NimaTarlani** [alireza0/s-ui#96]
سلام. 
دوتا مسئله
یک اینکه وقتی اینباند هیستریا میسازم, تلگرام خوب کار میکنه و پینگ میده داخل نکوباکس ولی گوگل و اسپید تست و... رو باز نمیکنه
این یک خط لاگ از سرور 
> Apr 03 00:44:31 offbeat-current.aeza.network runSingbox.sh[1707]: INFO[0197] [2466996594 0ms] inbound/hysteria2[in-12638]: [nima] inbound connection to 10.10.34.35:443

اینو باید چطوری فیکس کنم از سمت سرور.

و دومی اینه که حتما allow insecure رو باید دستی روشنش کنم داخل اپ.
امکانش هست داخل تنظیمات اینباند این گزینه رو هم اضافه کنین که بشه اضافش کرد؟

**Comment by alireza0** [comment]
درود بر شما
مشکل اولتون اینه که dns گوشی رو از کانفیگ رد نمیکنید.
برای بخش دوم، اینباند سرور نمیتونه مقدار allowinsecure رو داشته باشه. کلاینت شما هم دریافت این پارامتر از سرور رو پشتیبانی نمیکنه.

**Comment by NimaTarlani** [comment]
این dns رو چطوری باید رد کرد؟
چون با یه پنل دیگه موقتا کار میکنم و داره جواب میده ولی به شدت داره اذیت میکنه. مثل مال شما امکانات خیلی زیاد نداره. 

و همون پنله `insecure=1` تو کانفیگ اضافه کرده که موقع اضافه کردن به کلاینت روشن میکنه. اینکارو هم میشه کرد یا نه؟

و اینکه من دارم رو یه پروژه ای کار میکنم و نیاز دارم به api پنل شما
تونستم یه سری قسمتارو اوکی کنم بدون api ولی قسمتی که بتونم مثلا حجم مصرفی کاربر رو در بیارم رو نمیتونم
امکانش هست یه راهکار بدین بابت این موضوع؟
 
 خیلی ممنونم 3>

**Comment by NimaTarlani** [comment]
دی ان اس رو داخل nekobox تغییر میدم به 1.1.1.1 درست میشه اون دایرکت شدن یه 10.10.34.35
ولی خب از سمت پنل نمیشه اینو درستش کرد؟

**Comment by m3hdiclub** [comment]
> این dns رو چطوری باید رد کرد؟ چون با یه پنل دیگه موقتا کار میکنم و داره جواب میده ولی به شدت داره اذیت میکنه. مثل مال شما امکانات خیلی زیاد نداره.
> 
> و همون پنله `insecure=1` تو کانفیگ اضافه کرده که موقع اضافه کردن به کلاینت روشن میکنه. اینکارو هم میشه کرد یا نه؟
> 
> و اینکه من دارم رو یه پروژه ای کار میکنم و نیاز دارم به api پنل شما تونستم یه سری قسمتارو اوکی کنم بدون api ولی قسمتی که بتونم مثلا حجم مصرفی کاربر رو در بیارم رو نمیتونم امکانش هست یه راهکار بدین بابت این موضوع؟
> 
> خیلی ممنونم 3>

از توی برنامه ای که استفاده میکنی میتونی DNS رو تغییر بدی
واسه insecure هم باید جلوی کانفیگ اینو بذاری
&allow_insecure=1

**Comment by alireza0** [comment]
مشکل اعلام شده مربوط به نرم افزار کلاینت میشه.
در مورد Allow Insecure در حال حاضر توی اولویت ها نیست و در نسخه های بعدی با ویژگی های جدید باید بهش فکر بشه.
