### ISSUE TITLE
درخواست اضافه کردن چندتا موضوع

### ISSUE THREAD

**Issue by m3hdiclub** [alireza0/s-ui#98]
درود استاد
میشه قابلیت ریست کردن ترافیک رو اضافه کنین؟
نمیشه کاری کرد که حجم فایل دیتابیس کمتر بشه؟ خیلی حجم فایل بکاپ زیاد میشه در صورتی که توی x-ui کمتر از یک مگابایت میشد.
وقتی یکی از کاربرا رو ادیت میزنم کلا هسته واسه 1-2 دقیقه غیرفعال میشه و از کار میوفته.

**Comment by alireza0** [comment]
درود بر شما
داده های کاربرها و خیلی از داده های دیگه نوشته میشه و باید هر چند ماه پاک بشه. حذف اونها در بروزرسانی های آتی افزوده میشه.
ولی این ویژگی به هسته وابسته نیست و زمان اون به دلیل مشکلات هسته با ریستارت شدنه. زمانی که کاربر زیادی دارید، سینگباکس برای ریستارت زمان بیشتری میخواد.
