### ISSUE TITLE
دلیل غیر فعال شدن هسته

### ISSUE THREAD

**Issue by m3hdiclub** [alireza0/s-ui#99]
درود
هر چند ساعت هسته غیرفعال میشه و با دستور s-ui
sing-box و s-ui
رو ریستارت میکنم و دوباره اوکی میشه..
پنل بالا میاد ولی کانفیگ کار نمیکنه، بعد از اینکه با دستورهای بالا ریستارت میکنم درجا اوکی میشه.
میشه راهنماییم کنین که مشکل از چیه؟

**Comment by m3hdiclub** [comment]
حالت autostart
s-ui و sing-box
رو هم فعال کردم ولی بازم مشکلم حل نشد و بعد از چند ساعت غیرفعال شد.

**Comment by alireza0** [comment]
درود بر شما
بدون لاگ نمیشه کمکی کرد
